### ISSUE TITLE
REWRITE规则订阅地址

### ISSUE THREAD

**Issue by ktownag** [elecV2/elecV2P#1]
大佬您好，之前有个版本好像可以直接导入QuanX的订阅地址，比如https://github.com/nzw9314/QuantumultX/raw/master/Get_Cookie_Remote.conf
现在不行了。
另外，希望能够考虑以后支持TASK远程订阅

**Comment by elecV2** [comment]
> 大佬您好，之前有个版本好像可以直接导入QuanX的订阅地址，比如https://github.com/nzw9314/QuantumultX/raw/master/Get_Cookie_Remote.conf
> 现在不行了。
> 另外，希望能够考虑以后支持TASK远程订阅

后面 JS文件 不带目录或http的订阅应该还是可以直接用的，需要先手动下载一下对应JS文件。远程JS 还在调试中，现在运行第一次会自动下载，运行第二正常工作。

TASK的远程订阅不考虑，以后可能会通过 JS+定时任务的方式实现。
