### ISSUE TITLE
运行脚本提示：API请求失败，请检查网路重试

### ISSUE THREAD

**Issue by wuliaodongfeng** [elecV2/elecV2P#10]
如题，n1，docker安装，换了好几个脚本都出现这个情况

**Comment by elecV2** [comment]
测试运行？ TASK 运行？远程链接脚本？本地脚本?哪个地方提示 API 请求失败？

一句请求失败，我怎么猜的出问题在哪？只能告诉你，检查一下网络重试。

在 JSMANAGE 页面，模拟网络请求，填写请求失败的 API 对应的 url，选择服务器 axios ，如果不能访问就去 SETTING 界面设置代理。

> 如题，n1，docker安装，换了好几个脚本都出现这个情况
