### ISSUE TITLE
多次在宝塔上反向代理总是找不到网页，想问问如果是宝塔上的PM2可以运行吗？

### ISSUE THREAD

**Issue by 810517583** [elecV2/elecV2P#100]
宝塔上可以成功运行index.js，并且监听8000端口，依旧没有界面。顺便问问NODEJS模式是不是就不能弄anyproxy了？

**Comment by 810517583** [comment]
![image](https://user-images.githubusercontent.com/8052916/123929549-7b91cb80-d9c1-11eb-8f00-d5099c240daf.png)

**Comment by 810517583** [comment]
![image](https://user-images.githubusercontent.com/8052916/123929607-8fd5c880-d9c1-11eb-81bd-b38bf9eef190.png)

**Comment by elecV2** [comment]
可以使用 anyproxy。

（不懂宝塔，其他问题无法解答
