### ISSUE TITLE
安卓咨询？

### ISSUE THREAD

**Issue by biewenwoshishui021** [elecV2/elecV2P#101]
我termux抢安装了elecv2p，安装部署时发现，v2p仅貌似支持nodejs  14 ，我现在是nodejd 12.18.3的版本，termux里也没有pkg update 把node升级到14的办法。

咨询一下，termux上到底能用v2p吗？有没有解决办法？谢谢！

**Comment by elecV2** [comment]
1. 想办法升级 nodejs
2. 尝试一下修改 package.json 里的 engines 字段
3. 放弃
