### ISSUE TITLE
安卓termux报端口错误

### ISSUE THREAD

**Issue by MavonCmc** [elecV2/elecV2P#102]
1:54:34 0|elecV2P  | [webSocket  error][2021-07-05 11:54:34.739] websocket error Error: listen EACCES: permission denied 0.0.0.0:80
11:54:34 0|elecV2P  |     at Server.setupListenHandle [as _listen2] (net.js:1301:21)
11:54:34 0|elecV2P  |     at listenInCluster (net.js:1366:12)
11:54:34 0|elecV2P  |     at Server.listen (net.js:1452:7)
11:54:34 0|elecV2P  |     at module.exports (/data/data/com.termux/files/home/elecV2P/webmodule.js:88:10)
11:54:34 0|elecV2P  |     at Object.<anonymous> (/data/data/com.termux/files/home/elecV2P/index.js:4:1)
11:54:34 0|elecV2P  |     at Module._compile (internal/modules/cjs/loader.js:1063:30)
11:54:34 0|elecV2P  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
11:54:34 0|elecV2P  |     at Module.load (internal/modules/cjs/loader.js:928:32)
11:54:34 0|elecV2P  |     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
11:54:34 0|elecV2P  |     at Object.<anonymous> (/data/data/com.termux/files/home/.config/yarn/global/node_modules/pm2/lib/ProcessContainerFork.js:33:23)
11:54:34 0|elecV2P  |     at Module._compile (internal/modules/cjs/loader.js:1063:30)
11:54:34 0|elecV2P  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
11:54:34 0|elecV2P  |     at Module.load (internal/modules/cjs/loader.js:928:32)
11:54:34 0|elecV2P  |     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
11:54:34 0|elecV2P  |     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
11:54:34 0|elecV2P  |     at internal/main/run_main_module.js:17:47 {
11:54:34 0|elecV2P  |   code: 'EACCES',
11:54:34 0|elecV2P  |   errno: -13,
11:54:34 0|elecV2P  |   syscall: 'listen',
11:54:34 0|elecV2P  |   address: '0.0.0.0',
11:54:34 0|elecV2P  |   port: 80
11:54:34 0|elecV2P  | }

扫描了一下端口，并没被占用，config.js改端口，还是一样的错误。

**Comment by elecV2** [comment]
permission denied

改端口在 script/Lists/config.json
