### ISSUE TITLE
N1运行不了，安装后容器一直在重启中

### ISSUE THREAD

**Issue by 86xqs** [elecV2/elecV2P#104]
按照最终推荐使用命令添加后，容器启动不了，一直重启，状态一直都是“Restarting (1) 50 seconds ago”。

**Comment by elecV2** [comment]
N1 应该是使用 arm64 的镜像

PS: 如果基础的安装问题不能通过说明文档和网络搜索解决，建议还是直接放弃吧。之后会碰到更多的问题，不值得

**Comment by 86xqs** [comment]
> N1 应该是使用 arm64 的镜像 PS: 如果基础的安装问题不能通过说明文档和网络搜索解决，建议还是直接放弃吧。之后会碰到更多的问题，不值得

方法二下面不是写着支持arm64和arm32吗
