### ISSUE TITLE
进入目录运行yarn的时候一堆warning，会有影响吗？

### ISSUE THREAD

**Issue by kanvenzeng** [elecV2/elecV2P#108]
yarn install v1.22.5
info No lockfile found.
[1/5] Validating package.json...
[2/5] Resolving packages...
warning anyproxy > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning anyproxy > clipboard-js@0.3.6: Please migrate to https://github.com/lgarron/clipboard-polyfill
warning anyproxy > request > har-validator@5.1.5: this library is no longer supported
warning anyproxy > request > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
warning anyproxy > pug > pug-code-gen > constantinople > babel-types > babel-runtime > core-js@2.6.12: core-js@<3.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
warning pm2 > @pm2/io > @opencensus/propagation-b3 > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
warning pm2 > @pm2/io > @opencensus/core > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
warning pm2 > @pm2/io > @opencensus/propagation-b3 > @opencensus/core > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
[3/5] Fetching packages...
info fsevents@2.3.2: The platform "linux" is incompatible with this module.
info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning "anyproxy > svg-inline-react@1.0.3" has unmet peer dependency "react@^0.14.0 || ^15.0.0".
[5/5] Building fresh packages...
success Saved lockfile.
Done in 23.17s.

这些warning可以解决吗？谢谢！

**Comment by elecV2** [comment]
没
不可以
不客气

**Comment by kanvenzeng** [comment]
> 没 不可以 不客气

谢谢大佬！
