### ISSUE TITLE
后台网页自适应问题

### ISSUE THREAD

**Issue by EchoChan314** [elecV2/elecV2P#109]
屏幕缩放100%的时候后台页面显示正常，其它百分比，后台页面显示就不正常了。

**Comment by EchoChan314** [comment]
另一个问题，在task页面，提示获取任务列表数量错误
![image](https://user-images.githubusercontent.com/5077551/127006906-202f36c3-92e2-40b0-a93d-d11209e8ee0c.png)

**Comment by elecV2** [comment]
缩放问题最好能提供截图，以及说明使用设备及缩放比例等。

task 这个已记录，晚点修复

**Comment by EchoChan314** [comment]
![image](https://user-images.githubusercontent.com/5077551/127088483-d6d3501b-eeb9-441c-b464-426305caf1e8.png)
当前是150%
![image](https://user-images.githubusercontent.com/5077551/127088556-181211f8-ff96-4b9d-98fe-b995f287596c.png)
当前是100%

都是在只修改系统缩放并且没有修改网页缩放的情况下。

**Comment by elecV2** [comment]
这种应该属于正常情况。表格内容有一个最小宽度，当显示页面小于这个最小宽带时，会出现左右滚动条。

**Comment by EchoChan314** [comment]
![image](https://user-images.githubusercontent.com/5077551/127101140-1c66f4b4-e124-4faa-99a7-af833ad4bec5.png)
再反馈一个bug，点获取内容的时候，会自动添加一个同样的任务订阅。

**Comment by EchoChan314** [comment]
再提个建议，既然多选的时候已经有删除的选项，现在删除的位置是不是可以换成手动执行当前的任务。（毕竟有些定时任务更新后需要手动执行一次）
![image](https://user-images.githubusercontent.com/5077551/127523392-64ef1653-baeb-462a-b067-3d81b0e27d60.png)

**Comment by elecV2** [comment]
> ![image](https://user-images.githubusercontent.com/5077551/127101140-1c66f4b4-e124-4faa-99a7-af833ad4bec5.png)
> 再反馈一个bug，点获取内容的时候，会自动添加一个同样的任务订阅。

简单测试了下，好像并不存在这个问题。等下个版本更新，如果问题还继续存在的话，可以新开一个 issue，说明你所使用的浏览器及问题复现的步骤。

**Comment by elecV2** [comment]
> 再提个建议，既然多选的时候已经有删除的选项，现在删除的位置是不是可以换成手动执行当前的任务。（毕竟有些定时任务更新后需要手动执行一次）
> ![image](https://user-images.githubusercontent.com/5077551/127523392-64ef1653-baeb-462a-b067-3d81b0e27d60.png)

这个暂时还是保持原有
