### ISSUE TITLE
重新启动的问题

### ISSUE THREAD

**Issue by minv5** [elecV2/elecV2P#11]
2.8.5还是有过半个小时会所有脚本重新启动的问题

**Comment by elecV2** [comment]
下次重启，使用 docker logs elecv2p -f  命令，找到重启之前的错误信息，截图或复制发过来吧

> 2.8.5还是有过半个小时会所有脚本重新启动的问题

**Comment by minv5** [comment]
不知道是op的问题还是arm64的问题，同样的配置，x86能打开pc端的boxjs，也能正常抓取任何ck，但是我的抓取ck就显示网络异常！

**Comment by elecV2** [comment]
﻿捋一下自己的步骤有没有问题。
1. 安装证书。如果不是使用自签证书，容器重建后每次都会生成新的根证书，需要重新安装信任。
2. 代理端口是否正确。（这部分太复杂，具体谷歌）
3. 抓的时候，打开 8002 那个端口的界面，和 docker logs ，看一下显示什么错误，然后对照解决



> 不知道是op的问题还是arm64的问题，同样的配置，x86能打开pc端的boxjs，也能正常抓取任何ck，但是我的抓取ck就显示网络异常！

**Comment by minv5** [comment]
更新需要重新生成吗？还有证书和自签证书啥区别？

**Comment by minv5** [comment]
抓取的时候，有的正常有的就是显示网络异常，而且anyproxy也没有显示错误

**Comment by elecV2** [comment]
更新后会自动生成， docker logs 最开始会显示 a new xxxxxxx rootCA xxx generated 啥的。
谷歌。
﻿
> 更新需要重新生成吗？还有证书和自签证书啥区别？

**Comment by minv5** [comment]
话说能不能tg里面说啊？

**Comment by minv5** [comment]
[runJSFile  error][2020-12-08 14:20:53.864]: run https://github.com/photonmang/quantumultX/raw/master/cache/qqread.js error: download fail! Parse Error: Duplicate Content-Length
[utilsFile  error][2020-12-08 14:20:53.865]: no such js file qqread.js
[runJSFile  error][2020-12-08 14:20:53.866]: don't have any code to run
