### ISSUE TITLE
大佬task面板应该适配下显示不全

### ISSUE THREAD

**Issue by dong0108** [elecV2/elecV2P#112]
大佬task面板应该适配下显示不全
![微信截图_20210805101650](https://user-images.githubusercontent.com/76082553/128280420-aff7c12e-cad8-43b3-8064-6936373b5f97.png)

**Comment by dong0108** [comment]
![微信截图_20210805102233](https://user-images.githubusercontent.com/76082553/128280930-a7ec5210-31a8-4e79-a151-7f0ec7514176.png)

**Comment by elecV2** [comment]
- 每个人使用的设备不一样，此类问题的反馈最好能附上你当前设备和屏幕分辨率相关信息。
- 默认必需保证表格内输入框的最小宽度，当宽度大于屏幕宽度时，可左右滚动进行查看。

**Comment by dong0108** [comment]
佬，1920*1080笔记本

**Comment by elecV2** [comment]
1920 不应该有这个问题啊🤔，你是不是调整了系统或浏览器的默认分辨率，比如125%？（下个版本应该会在这方面有一些优化

**Comment by dong0108** [comment]
佬，系统和浏览器都没调整，等下个版本吧

**Comment by elecV2** [comment]
这个问题在新的版本应该已解决，如果问题继续存在，欢迎重开 issue。
