### ISSUE TITLE
已解决

### ISSUE THREAD

**Issue by huanzhiyi** [elecV2/elecV2P#113]
报错日志
standard_init_linux.go:228: exec user process caused: exec format error

安装命令
version: '3.3'
services:
  elecv2p:
    image: elecv2/elecv2p
    container_name: elecv2p
    restart: always
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "8100:80"
      - "8101:8001"
      - "8102:8002"
    volumes:
      - "/elecv2p/JSFile:/usr/local/app/script/JSFile"
      - "/elecv2p/Lists:/usr/local/app/script/Lists"
      - "/elecv2p/Store:/usr/local/app/script/Store"
      - "/elecv2p/Shell:/usr/local/app/script/Shell"
      - "/elecv2p/rootCA:/usr/local/app/rootCA"
      - "/elecv2p/efss:/usr/local/app/efss"

**Comment by elecV2** [comment]
arm32 平台就使用 arm32的镜像，改 image 那一行。
（PS: 如果不能通过说明文档和搜索解决基础的安装问题，建议直接放弃。后面会碰到更多的问题，会浪费你很多时间，不值得

**Comment by huanzhiyi** [comment]
嗯 没看清楚 所以后面改了题目 已经解决
