### ISSUE TITLE
运行生成的日志文件太大了，可以设置自动清理吗？

### ISSUE THREAD

**Issue by Jace-y** [elecV2/elecV2P#114]

**Comment by Jace-y** [comment]
保留最新1-3天的日志

**Comment by elecV2** [comment]
默认自带了一个 deletelog.js ，可以自己设置一个定时任务进行清理。（我记得默认的任务订阅里面就有这个，直接添加就好了

**Comment by jim114042** [comment]
新的里没有默认清理日志的任务了  如果添加？

**Comment by jim114042** [comment]
> 默认自带了一个 deletelog.js ，可以自己设置一个定时任务进行清理。（我记得默认的任务订阅里面就有这个，直接添加就好了

新的里没有默认清理日志的任务了 如果添加？

**Comment by Jace-y** [comment]
JSFILE 文件夹里有deletelog.js ，任务里添加上去就行
