### ISSUE TITLE
anyproxy抓包后看不到里面的header和body等具体内容

### ISSUE THREAD

**Issue by fanfan008** [elecV2/elecV2P#115]
大佬，反馈一个问题，最近v2p抓包后，anyproxy里看不到里面的header和body等具体内容，点了没反应，之前一直正常的。
    看到tg群里好几个人都说遇到了这个问题，说明不是个例了，反正多重启几次有时候就能解决这个问题。希望大佬后期更新解决一下这个问题。
![Uploading IMG_20210805_135850_695.jpg…]()

**Comment by shenmadouyaowen** [comment]
一样

**Comment by UTSOURCE** [comment]
我的有时候可以有时候不行

**Comment by elecV2** [comment]
这种情况一般出现在什么时候？
如果是隔天的话，看一下定时任务中是否使用了 deletelog.js 。该 JS 默认会删除已抓包数据的缓存，导致内容无法查看。
你可以手动修改该 js 中 CONFIG clearanyproxycache 为 false。

如是是抓包之后马上就无法查看相关信息了，这个问题暂时无法解决（因为目前还没碰到过

**Comment by huanzhiyi** [comment]
> 这种情况一般出现在什么时候？
> 如果是隔天的话，看一下定时任务中是否使用了 deletelog.js 。该 JS 默认会删除已抓包数据的缓存，导致内容无法查看。
> 你可以手动修改该 js 中 CONFIG clearanyproxycache 为 false。
> 
> 如是是抓包之后马上就无法查看相关信息了，这个问题暂时无法解决（因为目前还没碰到过

请问是不能删除anyproxy的日志吗 如果日志过多要怎么删除

**Comment by CenBoMin** [comment]
@huanzhiyi 正常是deletelog.js这个是晚上11点多左右的定时任务，意思应该是你可以在执行定时任务之前查看……一个是不要隔天就当天，或者调整你的定时任务的corn，三天执行一次或者一个礼拜执行一次

**Comment by huanzhiyi** [comment]
> 一个是不要隔天就

好的 明白了 感谢解答
