### ISSUE TITLE
升级到3.4.5版本,使用 -env 关键字进行声明报错

### ISSUE THREAD

**Issue by CenBoMin** [elecV2/elecV2P#116]
测试使用的是https://raw.githubusercontent.com/elecV2/elecV2P/master/script/JSFile/exam-js-env.js范例文档

[taskRunJS   info][2021-08-15 22:11:20.490] run exam-js-env.js result: {"error":"$env is not defined"}
[funcTask    info][2021-08-15 22:11:20.489] TASK: 新的任务 117 started
[exam-...js error][2021-08-15 22:11:20.486] exam-js-env.js:5
let name = $env.name || 'elecV2P'       // 使用 $env 来获取临时环境变量(v3.4.5 之后)
           ^

ReferenceError: $env is not defined

**Comment by CenBoMin** [comment]
软更新升级会报错,试了一下docker拉3.4.5的镜像就可以了

**Comment by elecV2** [comment]
软更新和Docker 更新应该是一样的。如果有问题，可能是软更新的设置有误，比如 noupdate 那一项屏蔽了一些关键脚本(script)的更新。
