### ISSUE TITLE
持久化存储创建容器，容器自带的js和list不会自动复制到本地存储中

### ISSUE THREAD

**Issue by wj36149** [elecV2/elecV2P#12]
![Snipaste_2020-12-08_12-56-36](https://user-images.githubusercontent.com/48109441/101441878-160ebc80-3955-11eb-8f7c-6121773eb33a.jpg)
log里会一起报错无list文件。

**Comment by minv5** [comment]
重新装

**Comment by elecV2** [comment]
﻿你持久化存储的的使用的映射的什么？每个文件夹单独分开的，还是 script 整个文件夹？

如果本地缺少了，就手动去 GITHUB 复制进去（具体操作谷歌）

> 
> log里会一起报错无list文件。

**Comment by wj36149** [comment]
> 
> ﻿你持久化存储的的使用的映射的什么？每个文件夹单独分开的，还是 script 整个文件夹？ 如果本地缺少了，就手动去 GITHUB 复制进去（具体操作谷歌）
> […](#)
> log里会一起报错无list文件。

谢谢，解决了。
