### ISSUE TITLE
请问“elecV2P 内存使用情况”的各项是什么，是否需要清理，谢谢

### ISSUE THREAD

**Issue by Sinclair-Liu** [elecV2/elecV2P#120]
下面是我的v2p某时的数值：
rss: 127.95 MB
heapTotal: 89.76 MB
heapUsed: 83.77 MB
external: 310.36 MB
arrayBuffers: 309.43 MB

**Comment by elecV2** [comment]
谷歌。
不用。（暂时也没办法清理
