### ISSUE TITLE
希望能在面板上打开修改除了 JS 和 COOKIE 以外的其他类型

### ISSUE THREAD

**Issue by Oreomeow** [elecV2/elecV2P#121]
https://github.com/Oreomeow/checkinpanel
如上，我把 py 签到项目移植到了 elecV2P 上，同时保留 `config.json`  这种获取参数的方法，另外还加入了 `.env` 这种。
发现在实行的过程中，打开替换这些文件还有 py 文件不如 js 和 cookie 等方便
是否有机会未来增加对 py 等文件的支持呢？

**Comment by elecV2** [comment]
之后肯定会的添加对其他文本文件进行编辑的功能，不过时间未知。主要是还没找到一个适合的在线编辑器，又不想自己造轮子（懒）。

目前的话，可以在EFSS界面下载，然后本地编辑，然后再上传上去。步骤确实麻烦了点，但以后的其他文本编辑应该都是在这个界面（如果有的话）。

**Comment by Oreomeow** [comment]
> 之后肯定会的添加对其他文本文件进行编辑的功能，不过时间未知。主要是还没找到一个适合的在线编辑器，又不想自己造轮子（懒）。 目前的话，可以在EFSS界面下载，然后本地编辑，然后再上传上去。步骤确实麻烦了点，但以后的其他文本编辑应该都是在这个界面（如果有的话）。

已经更新了，win Edge 体验良好，能不能优化一下 iPad Safari 编辑呢

**Comment by Oreomeow** [comment]
> > 之后肯定会的添加对其他文本文件进行编辑的功能，不过时间未知。主要是还没找到一个适合的在线编辑器，又不想自己造轮子（懒）。 目前的话，可以在EFSS界面下载，然后本地编辑，然后再上传上去。步骤确实麻烦了点，但以后的其他文本编辑应该都是在这个界面（如果有的话）。
> 
> 已经更新了，win Edge 体验良好，能不能优化一下 iPad Safari 编辑呢

具体表现为打开很慢且无法使用（可以简单编辑即可

**Comment by elecV2** [comment]
编辑器打开很慢还是整个EFSS页面？首次打开需要加载几个编辑器的远程文件，之后应该会好些。
不能用如果是指移动设备没有右键功能的话，这个正在研究中。
