### ISSUE TITLE
may run timeout of 60000ms

### ISSUE THREAD

**Issue by airdge** [elecV2/elecV2P#136]
有些脚本需要定时,调用了setTimeout
```
async wait(t) {
        return new Promise(e => setTimeout(e, t))
    }
```
假如脚本59分运行,等到整点运行时候就会报错 may run timeout of 60000ms
设置里的JS 运行相关设置
timeout设置为0,还是会被超时中断

**Comment by elecV2** [comment]
这个提醒应该是在运行 shell 指令或者minishell 的情况下可能会出现，跟运行 JS 没什么关系。

如果是定时任务运行的话在后面加 -timeout=0。比如 node xxx.js -timeout=0，具体可以看 TASK 页面下的说明文档。

如果是在其他情况下出现这个问题，需要更详细的说明一下使用情况，才能定位问题。
