### ISSUE TITLE
3.4.9task定时无法修改

### ISSUE THREAD

**Issue by paopaoya** [elecV2/elecV2P#137]
添加任务时可以保存到/Lists/task.list
但是修改定时 时间时 task.list文件的编辑时间会变 然而cron时间不会变
再次刷新task页面 cron和添加任务时一样
无法修改cron

**Comment by elecV2** [comment]
简单测试了一下，不存在你说的这个问题。（修改正在运行的任务需要重新点击一次开始

如果你确定问题继续存在，麻烦说一下你的详细操作步骤，我看下能不能复现这个问题
