### ISSUE TITLE
运行脚本错误

### ISSUE THREAD

**Issue by minv5** [elecV2/elecV2P#14]
![image](https://user-images.githubusercontent.com/54812955/101504197-e5a73c80-39ad-11eb-9e09-01551b085140.png)
这种是？

**Comment by minv5** [comment]
==============📣系统通知📣==============
企鹅读书4
获取更新body: 成功🎉
[qqreads.js  info][2020-12-09 15:10:00.882]: 
🔔企鹅读书, 结束! 🕛 0.018 秒
[qqreads.js error][2020-12-09 15:10:00.916]: $httpClient {"url":"https://mqqapi.reader.qq.com/mqq/page/config?router=%2Fpages%2Fbook-read%2Findex&options=","headers":{"ywsession":"o1dahnlohmsqbq6qvmymajkvwno42sj3","Cookie":"ywguid=906784605;ywkey=ywKG8UW8tUki;platform=ios;channel=mqqmina;mpVersion=0.32.5;qq_ver=8.4.17;os_ver=iOS 14.2;mpos_ver=1.21.0;platform=ios;openid=47ACF4749B460222E42DF15FE9B3EABE","Connection":"keep-alive","Accept":"*/*","Host":"mqqapi.reader.qq.com","User-Agent":"QQ/8.4.17.638 CFNetwork/1206 Darwin/20.1.0","Referer":"https://appservice.qq.com/1110657249/0.32.5/page-frame.html","Accept-Language":"zh-cn","Accept-Encoding":"gzip, deflate, br","mpversion":"0.32.5","Content-Type":"application/x-www-form-urlencoded; charset=UTF-8"}} timeout of 5000ms exceeded
[qqreads.js error][2020-12-09 15:10:00.918]: $httpClient {"url":"https://mqqapi.reader.qq.com/mqq/red_packet/user/treasure_box_video","headers":{"ywsession":"o1dahnlohmsqbq6qvmymajkvwno42sj3","Cookie":"ywguid=906784605;ywkey=ywKG8UW8tUki;platform=ios;channel=mqqmina;mpVersion=0.32.5;qq_ver=8.4.17;os_ver=iOS 14.2;mpos_ver=1.21.0;platform=ios;openid=47ACF4749B460222E42DF15FE9B3EABE","Connection":"keep-alive","Accept":"*/*","Host":"mqqapi.reader.qq.com","User-Agent":"QQ/8.4.17.638 CFNetwork/1206 Darwin/20.1.0","Referer":"https://appservice.qq.com/1110657249/0.32.5/page-frame.html","Accept-Language":"zh-cn","Accept-Encoding":"gzip, deflate, br","mpversion":"0.32.5","Content-Type":"application/x-www-form-urlencoded; charset=UTF-8"},"timeout":60000} timeout of 5000ms exceeded
[AnyProxy Log][2020-12-09 15:10:00]: received request to: POST mqqapi.reader.qq.com/log/v4/mqq/track
[AnyProxy Log][2020-12-09 15:10:01]: received request to: GET mqqapi.reader.qq.com/mqq/user/init
[AnyProxy Log][2020-12-09 15:10:01]: received request to: GET mqqapi.reader.qq.com/mqq/v1/bookShelfInit
[AnyProxy Log][2020-12-09 15:10:01]: received request to: GET mqqapi.reader.qq.com/mqq/page/config?router=%2Fpages%2Fbook-read%2Findex&options=
[AnyProxy Log][2020-12-09 15:10:01]: received request to: GET mqqapi.reader.qq.com/mqq/red_packet/user/page?fromGuid=
[qqreads.js error][2020-12-09 15:10:01.032]: $httpClient {"url":"https://mqqapi.reader.qq.com/mqq/v1/bookShelfInit","headers":{"ywsession":"o1dahnlohmsqbq6qvmymajkvwno42sj3","Cookie":"ywguid=906784605;ywkey=ywKG8UW8tUki;platform=ios;channel=mqqmina;mpVersion=0.32.5;qq_ver=8.4.17;os_ver=iOS 14.2;mpos_ver=1.21.0;platform=ios;openid=47ACF4749B460222E42DF15FE9B3EABE","Connection":"keep-alive","Accept":"*/*","Host":"mqqapi.reader.qq.com","User-Agent":"QQ/8.4.17.638 CFNetwork/1206 Darwin/20.1.0","Referer":"https://appservice.qq.com/1110657249/0.32.5/page-frame.html","Accept-Language":"zh-cn","Accept-Encoding":"gzip, deflate, br","mpversion":"0.32.5","Content-Type":"application/x-www-form-urlencoded; charset=UTF-8"}} timeout of 5000ms exceeded
[qqreads.js error][2020-12-09 15:10:01.036]: $httpClient {"url":"https://mqqapi.reader.qq.com/mqq/page/config?router=%2Fpages%2Fbook-read%2Findex&options=","headers":{"ywsession":"o1dahnlohmsqbq6qvmymajkvwno42sj3","Cookie":"ywguid=906784605;ywkey=ywKG8UW8tUki;platform=ios;channel=mqqmina;mpVersion=0.32.5;qq_ver=8.4.17;os_ver=iOS 14.2;mpos_ver=1.21.0;platform=ios;openid=47ACF4749B460222E42DF15FE9B3EABE","Connection":"keep-alive","Accept":"*/*","Host":"mqqapi.reader.qq.com","User-Agent":"QQ/8.4.17.638 CFNetwork/1206 Darwin/20.1.0","Referer":"https://appservice.qq.com/1110657249/0.32.5/page-frame.html","Accept-Language":"zh-cn","Accept-Encoding":"gzip, deflate, br","mpversion":"0.32.5","Content-Type":"application/x-www-form-urlencoded; charset=UTF-8"}} timeout of 5000ms exceeded
[qqreads.js error][2020-12-09 15:10:01.038]: $httpClient {"url":"https://mqqapi.reader.qq.com/mqq/user/init","headers":{"ywsession":"o1dahnlohmsqbq6qvmymajkvwno42sj3","Cookie":"ywguid=906784605;ywkey=ywKG8UW8tUki;platform=ios;channel=mqqmina;mpVersion=0.32.5;qq_ver=8.4.17;os_ver=iOS 14.2;mpos_ver=1.21.0;platform=ios;openid=47ACF4749B460222E42DF15FE9B3EABE","Connection":"keep-alive","Accept":"*/*","Host":"mqqapi.reader.qq.com","User-Agent":"QQ/8.4.17.638 CFNetwork/1206 Darwin/20.1.0","Referer":"https://appservice.qq.com/1110657249/0.32.5/page-frame.html","Accept-Language":"zh-cn","Accept-Encoding":"gzip, deflate, br","mpversion":"0.32.5","Content-Type":"application/x-www-form-urlencoded; charset=UTF-8"},"timeout":60000} timeout of 5000ms exceeded
[qqreads.js error][2020-12-09 15:10:01.040]: $httpClient https://mqqapi.reader.qq.com/mqq/user/init cb error: TypeError: Cannot read property 'user' of undefined
    at evalmachine.<anonymous>:356:40
    at evalmachine.<anonymous>:707:4232
    at /usr/local/app/script/context.js:113:23
    at <anonymous>
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at runNextTicks (node:internal/process/task_queues:62:3)
    at processTimers (node:internal/timers:496:9)
[AnyProxy Log][2020-12-09 15:10:01]: received request to: GET mqqapi.reader.qq.com/mqq/user/init
[AnyProxy Log][2020-12-09 15:10:01]: received request to: GET mqqapi.reader.qq.com/mqq/v1/bookShelfInit
[AnyProxy Log][2020-12-09 15:10:01]: received request to: GET mqqapi.reader.qq.com/mqq/page/config?router=%2Fpages%2Fbook-read%2Findex&options=
[AnyProxy Log][2020-12-09 15:10:01]: received request to: GET mqqapi.reader.qq.com/mqq/red_packet/user/page?fromGuid=
[AnyProxy Log][2020-12-09 15:10:01]: received request to: POST mqqapi.reader.qq.com/log/v4/mqq/track
[AnyProxy Log][2020-12-09 15:10:01]: received request to: POST mqqapi.reader.qq.com/log/v4/mqq/track
[AnyProxy Log][2020-12-09 15:10:01]: received request to: GET mqqapi.reader.qq.com/mqq/user/init
[AnyProxy Log][2020-12-09 15:10:01]: received request to: GET mqqapi.reader.qq.com/mqq/v1/bookShelfInit
[AnyProxy Log][2020-12-09 15:10:01]: received request to: GET mqqapi.reader.qq.com/mqq/page/config?router=%2Fpages%2Fbook-read%2Findex&options=
[AnyProxy Log][2020-12-09 15:10:01]: received request to: GET mqqapi.reader.qq.com/mqq/red_packet/user/treasure_box_video
[AnyProxy Log][2020-12-09 15:10:01]: received request to: GET mqqapi.reader.qq.com/mqq/red_packet/user/treasure_box_video
[AnyProxy Log][2020-12-09 15:10:01]: received request to: POST mqqapi.reader.qq.com/log/v4/mqq/track
[AnyProxy Log][2020-12-09 15:10:01]: received request to: GET mqqapi.reader.qq.com/mqq/red_packet/user/treasure_box_video
[AnyProxy Log][2020-12-09 15:10:01]: received request to: GET mqqapi.reader.qq.com/mqq/user/init
[AnyProxy Log][2020-12-09 15:10:01]: received request to: GET mqqapi.reader.qq.com/mqq/v1/bookShelfInit
[AnyProxy Log][2020-12-09 15:10:01]: received request to: GET mqqapi.reader.qq.com/mqq/page/config?router=%2Fpages%2Fbook-read%2Findex&options=
[AnyProxy Log][2020-12-09 15:10:01]: received request to: POST mqqapi.reader.qq.com/log/v4/mqq/track
[elecV2P     info][2020-12-09 15:10:01.477]: match rewrite rules: https:\/\/mqqapi\.reader\.qq\.com\/log\/v4\/mqq\/track https://raw.githubusercontent.com/ziye12/JavaScript/master/Task/qqreads.js
[runJSFile notify][2020-12-09 15:10:01.479]: run qqreads.js from rule
[qqreads.js  info][2020-12-09 15:10:01.486]: 
🔔企鹅读书, 开始!
[qqreads.js  info][2020-12-09 15:10:01.500]: [企鹅读书4] 获取更新body: 成功,qqreadbodyVal: {"common":{"appid":1450024394,"areaid":5,"qq_ver":"8.4.17","os_ver":"iOS 14.2","mp_ver":"0.32.5","mpos_ver":"1.21.0","brand":"iPhone","model":"iPhone XS<iPhone11,2>","screenWidth":375,"screenHeight":812,"windowWidth":0,"windowHeight":0,"openid":"47ACF4749B460222E42DF15FE9B3EABE","guid":906784605,"session":"o1dahnlohmsqbq6qvmymajkvwno42sj3","scene":1007,"source":"wza0007wzb0005","hasRedDot":"false","missions":-1,"caseID":-1},"dataList":[{"click1":"bookDetail_bottomBar_read_C","click2":"qqauthorize_addRCS_succ_C","route":"pages/book-read/index","refer":"pages/book-detail/index","options":{"bid":"31808365","cid":"1"},"dis":1607497800208,"ext6":59,"eventID":"bookRead_show_I","type":"shown","ccid":1,"bid":"31808365","bookStatus":0,"bookPay":1,"chapterStatus":0,"ext1":{"font":18,"bg":0,"pageMode":1},"from":"bookLib2_bookList_bookClick_C_0_31808365"}]}
[qqre...js notify][2020-12-09 15:10:01.502]: 企鹅读书4 获取更新body: 成功🎉  
[utilsFeed notify][2020-12-09 15:10:01.503]: add feed item 企鹅读书4 获取更新body: 成功🎉
[utilsFeed notify][2020-12-09 15:10:01.503]: bark notify: 企鹅读书4 获取更新body: 成功🎉
[qqreads.js  info][2020-12-09 15:10:01.504]: 
==============📣系统通知📣==============
企鹅读书4
获取更新body: 成功🎉
[qqreads.js  info][2020-12-09 15:10:01.505]: 
🔔企鹅读书, 结束! 🕛 0.019 秒
[elecV2P     info][2020-12-09 15:10:01.519]: match rewrite rules: https:\/\/mqqapi\.reader\.qq\.com\/log\/v4\/mqq\/track https://raw.githubusercontent.com/ziye12/JavaScript/master/Task/qqreads.js
[runJSFile notify][2020-12-09 15:10:01.521]: run qqreads.js from rule
[qqreads.js  info][2020-12-09 15:10:01.528]: 
🔔企鹅读书, 开始!
[qqreads.js  info][2020-12-09 15:10:01.541]: [企鹅读书4] 获取更新body: 成功,qqreadbodyVal: {"common":{"appid":1450024394,"areaid":5,"qq_ver":"8.4.17","os_ver":"iOS 14.2","mp_ver":"0.32.5","mpos_ver":"1.21.0","brand":"iPhone","model":"iPhone XS<iPhone11,2>","screenWidth":375,"screenHeight":812,"windowWidth":0,"windowHeight":0,"openid":"47ACF4749B460222E42DF15FE9B3EABE","guid":906784605,"session":"o1dahnlohmsqbq6qvmymajkvwno42sj3","scene":1007,"source":"wza0007wzb0005","hasRedDot":"false","missions":-1,"caseID":-1},"dataList":[{"click1":"bookDetail_bottomBar_read_C","click2":"qqauthorize_addRCS_succ_C","route":"pages/book-read/index","refer":"pages/book-detail/index","options":{"bid":"31808365","cid":"1"},"dis":1607497801106,"ext6":59,"eventID":"bookRead_show_I","type":"shown","ccid":1,"bid":"31808365","bookStatus":0,"bookPay":1,"chapterStatus":0,"ext1":{"font":18,"bg":0,"pageMode":1},"from":"bookLib2_bookList_bookClick_C_0_31808365"}]}
[qqre...js notify][2020-12-09 15:10:01.542]: 企鹅读书4 获取更新body: 成功🎉  
[utilsFeed notify][2020-12-09 15:10:01.543]: add feed item 企鹅读书4 获取更新body: 成功🎉
[utilsFeed notify][2020-12-09 15:10:01.543]: bark notify: 企鹅读书4 获取更新body: 成功🎉
[qqreads.js  info][2020-12-09 15:10:01.544]: 
==============📣系统通知📣==============
企鹅读书4
获取更新body: 成功🎉
[qqreads.js  info][2020-12-09 15:10:01.545]: 
🔔企鹅读书, 结束! 🕛 0.017 秒
/usr/local/app/node_modules/brotli/build/encode.js:3
1<process.argv.length?process.argv[1].replace(/\\/g,"/"):"unknown-program");b.arguments=process.argv.slice(2);"undefined"!==typeof module&&(module.exports=b);process.on("uncaughtException",function(a){if(!(a instanceof y))throw a;});b.inspect=function(){return"[Emscripten Module object]"}}else if(x)b.print||(b.print=print),"undefined"!=typeof printErr&&(b.printErr=printErr),b.read="undefined"!=typeof read?read:function(){throw"no read() available (jsc?)";},b.readBinary=function(a){if("function"===
                                                                                                                                                                                                                              ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "TypeError: Cannot read property 'readTime' of undefined".] {
  code: 'ERR_UNHANDLED_REJECTION'

**Comment by elecV2** [comment]
服务器超时问题无法解决。

个别脚本 async function 引起的重启，暂时无法解决，只能去优化对应脚本。
