### ISSUE TITLE
启动不了

### ISSUE THREAD

**Issue by Chase2179** [elecV2/elecV2P#143]
<img width="1155" alt="截屏2021-11-09 下午10 36 55" src="https://user-images.githubusercontent.com/74200740/140946867-e5e27baf-ff2e-450d-a8b6-8d77051af358.png">

设备：r2s openwrt dockerman

之前可以这样，一点问题没有。今天就不行，启动不了。不知道是不是我哪里不对
docker run --restart=always \
  -d --name elecv2p \
  -e TZ=Asia/Shanghai \
  -e port=8888 \
  -v /elecv2p/JSFile:/usr/local/app/script/JSFile \
  -v /elecv2p/Lists:/usr/local/app/script/Lists \
  -v /elecv2p/Store:/usr/local/app/script/Store \
  -v /elecv2p/Shell:/usr/local/app/script/Shell \
  -v /elecv2p/rootCA:/usr/local/app/rootCA \
  -v /elecv2p/efss:/usr/local/app/efss \
  --net host \
  elecv2/elecv2p:latest

**Comment by mzucan** [comment]
@Chase2179 你好，解决了吗。我用上一个版本是正常的，新版本安装完了就启动不了了，和你一样的问题
