### ISSUE TITLE
websocket 已断开，正在尝试重新连接

### ISSUE THREAD

**Issue by Sinclair-Liu** [elecV2/elecV2P#144]
<img width="728" alt="Snipaste_2021-11-11_23-31-27" src="https://user-images.githubusercontent.com/26570936/141325913-c5f05df9-e6cf-4cfd-976f-efe3660a5abb.png">

请问有无办法调试解决呢，Thanks♪(･ω･)ﾉ

**Comment by elecV2** [comment]
这种情况通常是某个脚本运行错误，导致 elecV2P 重启。只能自行根据 errors.log 或 后台运行日志调试解决。
