### ISSUE TITLE
随机延迟参数

### ISSUE THREAD

**Issue by Oreomeow** [elecV2/elecV2P#148]
- 由于不想总在同一时间发起请求，能不能设置一个随机延迟任务的参数，之前想通过随机定时来实现，但是又不想修改文件（容易出错
- 看了一下倒计时的方法，0 999 x，可能需要 double 任务实现

**Comment by Oreomeow** [comment]
不过又想到一个方案
0 1 79200(22 h)
false
设置一个任务每天 0 点启动所有任务

**Comment by elecV2** [comment]
cron 定时基于第三方库 node-cron，不方便进行修改。
目前的话只能通过 cron+倒计时的方式去实现。

**Comment by Oreomeow** [comment]
好的，谢谢 e大，那就走那个方案了
