### ISSUE TITLE
如何开启docker持久化存储

### ISSUE THREAD

**Issue by Stdocdure** [elecV2/elecV2P#149]
大佬们好：
        前几天我更新了docker镜像重启容器后发现我的抓包数据全部丢失了，我研究文档后发现大佬说要么备份要么开启持久化存储，我现在想咨询一下如何开启持久化存储功能。

**Comment by dmcslt** [comment]
使用 -v 映射目录

**Comment by Stdocdure** [comment]
> 使用 -v 映射目录

感谢大佬，我是群晖看来没有图形化设置方法了，下班以后我研究一下吧。
