### ISSUE TITLE
:sparkles: 自动更新 JSON 订阅任务到定时任务中

### ISSUE THREAD

**Issue by Oreomeow** [elecV2/elecV2P#151]
json 中新增了任务后自动添加到定时任务中

不想自己写，希望大佬能实现下，加个开关嘻嘻

**Comment by elecV2** [comment]
个人不是很喜欢自动更新^_^，而且现在应该可以写一个专门的脚本，通过 $task 相关功能实现这个需求。

不过加开关这个还是可以考虑的

**Comment by Teeoo** [comment]
🤣以实现部分更新

**Comment by Oreomeow** [comment]
@Teeoo 看到了抓住一个是一个
