### ISSUE TITLE
版本号3.5.5报no list default.list错误

### ISSUE THREAD

**Issue by baigougou** [elecV2/elecV2P#153]
环境:甲骨文vps x64设备 docker安装
问题表现:在3.5.3下面报 no list default.list错误,升级到3.5.5报同样的错误甚至还报了no list filter.list错误超长的脚本因为报错导致脚本不能正常执行 
无奈只能发帖求助 跑的是中青的脚本  
[utilsFile  error][2021-12-15 11:31:17.328] no list default.list
[utilsFile  error][2021-12-15 11:32:31.641] no list default.list
[utilsFile  error][2021-12-15 11:32:35.652] no list filter.list

3.5.3报错
[utilsFile  error][2021-12-15 09:03:44.926] no list default.list
[utilsFile  error][2021-12-15 09:12:57.402] no list default.list
[utilsFile  error][2021-12-15 09:15:58.306] no list default.list
[utilsFile  error][2021-12-15 10:01:53.320] no list default.list
[utilsFile  error][2021-12-15 10:17:57.818] no list default.list
[utilsFile  error][2021-12-15 10:31:23.737] no list default.list

**Comment by Teeoo** [comment]
这不是正常的么,检查下你映射的Lists目录里面看看对应的文件存在不

**Comment by baigougou** [comment]
> 这不是正常的么,检查下你映射的Lists目录里面看看对应的文件存在不

看了下没有这个文件
