### ISSUE TITLE
cron 7-59/12 * * * *  不是从第7分钟开始算，后台日志中显示是第12、24、36分钟执行的

### ISSUE THREAD

**Issue by jim114042** [elecV2/elecV2P#154]
cron 7-59/12 * * * *  任务执行规则不是 第7、19、31、43、55分钟执行任务
而是第12、24、36、48分钟执行任务

![image](https://user-images.githubusercontent.com/20591941/146299324-6d774e3d-0d0b-45c1-a695-11ebc6f8b679.png)

![image](https://user-images.githubusercontent.com/20591941/146299199-a90852eb-2925-4324-b143-b92144f17310.png)
![image](https://user-images.githubusercontent.com/20591941/146299237-9a00855c-5822-485f-8cc9-6de47ef7f975.png)
![image](https://user-images.githubusercontent.com/20591941/146299273-3b4d2a8b-2a28-4a10-b170-636792b549bb.png)
![image](https://user-images.githubusercontent.com/20591941/146299299-cc653489-2150-4099-993d-40e68fc33fc4.png)

**Comment by jim114042** [comment]
cron 也不支持 7/12 * * * *的格式

**Comment by elecV2** [comment]
建议先去好好学习一下 cron 的时间格式。

**Comment by jim114042** [comment]
> 建议先去好好学习一下 cron 的时间格式。

不是想抬杠
Linux 里cron也是这么写啊  7/12 * * * *不是从7分开始 每隔12分钟执行一次吗？
