### ISSUE TITLE
神了个奇

### ISSUE THREAD

**Issue by Teeoo** [elecV2/elecV2P#155]
newversion: "3.5.3"
version: "3.5.5"

**Comment by Teeoo** [comment]
cat package.json 

"version": "3.5.5",

cat config.json

"version": "3.5.2",
"newversion": "3.5.3"

所以说我到底改相信谁:(

**Comment by elecV2** [comment]
package.json

config.json 是你修改配置后保存才会有变化，可以随便更改，或直接删除。

**Comment by Teeoo** [comment]
所以说我获取最新版本版本号应该从哪里获取呢

**Comment by elecV2** [comment]
elecV2P 的最新版本以 Github上的package.json 为准。
自建的 elecV2P，后台版本以本机上的 package.json 为准。前台版本写死在前端代码里。

API的话，可以看一下初始化设置里的检测更新，那里会返回正确的版本信息（如果我没记错的话

**Comment by Teeoo** [comment]
🤣难怪我那个小红点怎么写都不对不是这里问题就是哪里问题
