### ISSUE TITLE
关于看看赚任务底部不显示任务信息的问题

### ISSUE THREAD

**Issue by tianrui521** [elecV2/elecV2P#158]
1. 一开始手机正常抓包，稳定运行了几天后想在把看看赚的未完成任务做完但是发现手机点击去底部没有任务提示显示了 导致无法抓到body，原有的body还是正常自动执行中。请教大佬们这个问题是怎么造成的呢？是证书问题还是网络问题 还是账户被黑了呢？如何破解此问题？

**Comment by Stdocdure** [comment]
老哥，我也是这个情况，从上个版本开始的这种问题，我也正好想上来反馈，请开发大佬详查。

**Comment by Stdocdure** [comment]
> 老哥，我也是这个情况，从上个版本开始的这种问题，我也正好想上来反馈，请开发大佬详查。

今天更新了新版本问题依旧。

**Comment by 737712963** [comment]
这个V2P有什么关系

**Comment by elecV2** [comment]
与项目本身无关的 issue.
