### ISSUE TITLE
运行脚本出错

### ISSUE THREAD

**Issue by wudongdefeng** [elecV2/elecV2P#159]
[RunJDT...js info][2022-01-05 20:29:07.221] ❌ 蒙牛, 失败! 原因: Error [ERR_REQUIRE_ESM]: require() of ES Module /data/data/com.termux/files/home/elecV2P/node_modules/got/dist/source/index.js from /data/data/com.termux/files/home/elecV2P/script/JSFile/jd_rush_mn.js not supported.

Error [ERR_REQUIRE_ESM]: require() of ES Module /data/data/com.termux/files/home/elecV2P/node_modules/got/dist/source/index.js from /data/data/com.termux/files/home/elecV2P/script/JSFile/meituan.js not supported.
Instead change the require of index.js in /data/data/com.termux/files/home/elecV2P/script/JSFile/meituan.js to a dynamic import() which is available in all CommonJS modules.
    at Object.initGotEnv (/data/data/com.termux/files/home/elecV2P/script/JSFile/meituan.js:14:108292)

**Comment by elecV2** [comment]
1. 重启
2. 重装
3. 放弃（或者提供更详细的错误脚本信息

**Comment by wudongdefeng** [comment]
更新前是好的，更新3.8就报错了，之前是3.5
File/jd_rush_mn.js cwd: script/JSFile
[RunJDT...js info][2022-01-08 15:24:41.449] start run command: node /data/data/com.termux/files/home/elecV2P/script/JSFile/jd_rush_mn.js cwd: script/JSFile
[schedule    info][2022-01-08 15:24:41.450] 蒙牛 finished
[funcExec    info][2022-01-08 15:24:41.584] 🔔蒙牛, 开始!
[RunJDT...js info][2022-01-08 15:24:41.585] 🔔蒙牛, 开始!
[funcExec    info][2022-01-08 15:24:41.587] ====================共4个京东账号Cookie=========
[RunJDT...js info][2022-01-08 15:24:41.587] ====================共4个京东账号Cookie=========
[funcExec    info][2022-01-08 15:24:41.669] ==================脚本执行- 北京时间(UTC+8)：1/8/2022, 3:24:41 PM=====================
[RunJDT...js info][2022-01-08 15:24:41.671] ==================脚本执行- 北京时间(UTC+8)：1/8/2022, 3:24:41 PM=====================
[funcExec    info][2022-01-08 15:24:41.729] ❌ 蒙牛, 失败! 原因: Error [ERR_REQUIRE_ESM]: require() of ES Module /data/data/com.termux/files/home/elecV2P/node_modules/got/dist/source/index.js from /data/data/com.termux/files/home/elecV2P/script/JSFile/jd_rush_mn.js not supported.
Instead change the require of index.js in /data/data/com.termux/files/home/elecV2P/script/JSFile/jd_rush_mn.js to a dynamic import() which is available in all CommonJS modules.!
[RunJDT...js info][2022-01-08 15:24:41.730] ❌ 蒙牛, 失败! 原因: Error [ERR_REQUIRE_ESM]: require() of ES Module /data/data/com.termux/files/home/elecV2P/node_modules/got/dist/source/index.js from /data/data/com.termux/files/home/elecV2P/script/JSFile/jd_rush_mn.js not supported.               Instead change the require of index.js in /data/data/com.termux/files/home/elecV2P/script/JSFile/jd_rush_mn.js to a dynamic import() which is available in all CommonJS modules.!
[funcExec    info][2022-01-08 15:24:41.733] 🔔蒙牛, 结束!  🕛 0.151 秒                                                [RunJDT...js info][2022-01-08 15:24:41.733] 🔔蒙牛, 结束!  🕛 0.151 秒
[funcExec    info][2022-01-08 15:24:41.743] command: node https://ghproxy.com/https://raw.githubusercontent.com/wudongdefeng/tem-update/master/jd_rush_mn.js finished
[RunJDT...js info][2022-01-08 15:24:41.743] command: node https://ghproxy.com/https://raw.githubusercontent.com/wudongdefeng/tem-update/master/jd_rush_mn.js finished
[eAxios    notify][2022-01-08 15:24:53.387] elecV2P v3.5.8 is the lastest version
