### ISSUE TITLE
shell系统变量问题

### ISSUE THREAD

**Issue by szh7379** [elecV2/elecV2P#161]
shell命令node环境，修改环境变量后无法立即生效，重启v2p没用，貌似必须系统注销用户或者关机，再重新登录/开机才会读取修改后的变量，不知道变量保存在哪里了，没法自己修改。

**Comment by elecV2** [comment]
windows 吗？

nodejs 默认环境变量 process.env

可以通过脚本自行更改，比如 process.env.myenv = "My Env"。(不推荐这么做。

建议使用 -env 参数，给脚本增加临时变量。
在说明文档 04-JS 和 06-task 中有简单的说明（搜关键字 env

**Comment by szh7379** [comment]
是的，Windowsi😂

**Comment by elecV2** [comment]
> 是的，Windows😂
> 
> 不过不是想要临时变量，比如cookie过期，需要保持很长时间，直接写入更好

没理解你说这个需求。如果是要长时间保存一个变量的话，建议保存到 JSMANAGE/脚本管理 store/cooike 常量中，然后通过 $store.get 读取。
