### ISSUE TITLE
更新失败

### ISSUE THREAD

**Issue by xzhqhfe** [elecV2/elecV2P#162]
[softu...js error][2022-02-09 16:18:45.849] 获取 elecV2P 软更新文件列表失败 $axios get https://api.github.com/repos/elecv2/elecv2p/git/trees/master?recursive=1 Error: Request failed with status code 403
[softup...js info][2022-02-09 16:18:44.386] $axios post /webhook Error: Request failed with status code 403
[soft...js result][2022-02-09 16:19:05.677] softupdate.js 返回值为空
[softup...js info][2022-02-09 16:18:44.342] 开始获取更新文件列表
[softup...js info][2022-02-09 16:18:44.331] 向 webhook 端口发送保存当前任务列表的指令
[softup...js info][2022-02-09 16:18:44.328] 所有默认依赖已安装
[softup...js info][2022-02-09 16:18:44.327] module rss installed
[softup...js info][2022-02-09 16:18:44.326] module pm2 installed
[softup...js info][2022-02-09 16:18:44.325] module node-cron installed
[softup...js info][2022-02-09 16:18:44.323] module formidable installed
[softup...js info][2022-02-09 16:18:44.322] module cheerio installed
[softup...js info][2022-02-09 16:18:44.320] module axios installed
[softup...js info][2022-02-09 16:18:44.319] module anyproxy installed
[softup...js info][2022-02-09 16:18:44.317] module adm-zip installed
[softup...js info][2022-02-09 16:18:44.315] 开始检测默认依赖是否安装
[softup...js info][2022-02-09 16:18:44.282] 检测到有新的版本: 3.5.9
[softup...js info][2022-02-09 16:18:44.280] elecV2P 当前版本: 3.5.6 最新版本: 3.5.9
[softup...js info][2022-02-09 16:18:43.581] 开始获取 elecV2P 最新版本号...

是哪里的问题啊？之前一直好好的。

**Comment by elecV2** [comment]
403是github拒绝访问，可能是网络或线路问题，隔段时间再尝试一下吧。（如果问题还存在话，欢迎继续反馈

**Comment by goargelj** [comment]
> 403是github拒绝访问，可能是网络或线路问题，隔段时间再尝试一下吧。（如果问题还存在话，欢迎继续反馈

我3.56更新也遇到一样的问题。https://api.github.com/repos/elecv2/elecv2p/git/trees/master?recursive=1 这个地址浏览器访问是正常的

**Comment by elecV2** [comment]
更新的网络请求是从你服务器发出的，跟浏览器能不能访问没太大关系

**Comment by goargelj** [comment]
> > 403是github拒绝访问，可能是网络或线路问题，隔段时间再尝试一下吧。（如果问题还存在话，欢迎继续反馈
> 
> 我3.56更新也遇到一样的问题。https://api.github.com/repos/elecv2/elecv2p/git/trees/master?recursive=1 这个地址浏览器访问是正常的

> 更新的网络请求是从你服务器发出的，跟浏览器能不能访问没太大关系


  res = await $axios({
  url: 'https://api.github.com/repos/elecv2/elecv2p/git/trees/master?recursive=1',
  headers: {
    'User-Agent': 'Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_6_8; en-us) AppleWebKit/534.50 (KHTML, like Gecko) Version/5.1 Safari/534.50',
  },
  method: 'get'
})
给这个地址加上任意ua头后就能正常获得返回，而不是返回403。

**Comment by elecV2** [comment]
经过反复测试，还是没有办法复现这个问题。

正常情况下，当 ua 缺失时，$axios 请求会自动添加默认的 ua（可在 SETTING/设置 界面修改）。

目前能给的建议还是：多尝试几次

**Comment by LJwyang** [comment]
科学上网使用的软更新失败
[softu...js error][2022-03-08 20:21:08.542] task 36 fail, data {
  path: 'package.json',
  mode: '100644',
  type: 'blob',
  sha: '35a369637269626d9b97b4022e8cb095e2a46e36',
  size: 1052,
  url: 'https://api.github.com/repos/elecV2/elecV2P/git/blobs/35a369637269626d9b97b4022e8cb095e2a46e36'
}
[softu...js error][2022-03-08 20:21:08.253] task 35 fail, data {
  path: 'logs/update.log',
  mode: '100644',
  type: 'blob',
  sha: '8a308683258a7836d617e522302be001fb8527a2',
  size: 12936,
  url: 'https://api.github.com/repos/elecV2/elecV2P/git/blobs/8a308683258a7836d617e522302be001fb8527a2'
}
[softu...js error][2022-03-08 20:21:07.981] task 32 fail, data {
  path: 'index.js',
  mode: '100644',
  type: 'blob',
  sha: '3ab122993e03ab34b66ad10496325b8ffdd78feb',
  size: 1917,
  url: 'https://api.github.com/repos/elecV2/elecV2P/git/blobs/3ab122993e03ab34b66ad10496325b8ffdd78feb'
}
[softu...js error][2022-03-08 20:21:07.973] task 31 fail, data {
  path: 'func/task.js',
  mode: '100644',
  type: 'blob',
  sha: 'b622b8e2eafc8c8906535597f3cb3706b7beeba0',
  size: 16737,
  url: 'https://api.github.com/repos/elecV2/elecV2P/git/blobs/b622b8e2eafc8c8906535597f3cb3706b7beeba0'
}
[softu...js error][2022-03-08 20:21:07.552] 更新部分文件时出错，请检查网络后重试 force done by callback
[softu...js error][2022-03-08 20:21:07.552] task 29 fail, data {
  path: 'func/index.js',
  mode: '100644',
  type: 'blob',
  sha: 'd35464ab57e236250a4407394493770d54a0f81c',
  size: 282,
  url: 'https://api.github.com/repos/elecV2/elecV2P/git/blobs/d35464ab57e236250a4407394493770d54a0f81c'
}
[softup...js info][2022-03-08 20:21:03.538] 获取更新: https://raw.githubusercontent.com/elecV2/elecV2P/master/package.json
[softup...js info][2022-03-08 20:21:03.538] 同步文件: /usr/local/app/logs/readme.log
[softup...js info][2022-03-08 20:21:03.538] readme.log [>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 100%
[softup...js info][2022-03-08 20:21:03.248] 同步文件: /usr/local/app/func/schedule.js
[softup...js info][2022-03-08 20:21:03.247] schedule.js [>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 100%
[softup...js info][2022-03-08 20:21:02.979] 同步文件: /usr/local/app/func/crontask.js
[softup...js info][2022-03-08 20:21:02.978] crontask.js [>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 100%
[softup...js info][2022-03-08 20:21:02.973] 同步文件: /usr/local/app/func/exec.js
[softup...js info][2022-03-08 20:21:02.973] exec.js [>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 100%
[softup...js info][2022-03-08 20:21:02.967] 同步文件: /usr/local/app/func/crt.js
[softup...js info][2022-03-08 20:21:02.966] crt.js [>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 100%
[softup...js info][2022-03-08 20:21:02.730] 同步文件: /usr/local/app/efss/tasksub.json
[softup...js info][2022-03-08 20:21:02.730] tasksub.json [>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 100%
[softup...js info][2022-03-08 20:21:02.545] 同步文件: /usr/local/app/efss/favend.png
[softup...js info][2022-03-08 20:21:02.545] favend.png [>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 100%
[softup...js info][2022-03-08 20:21:02.530] 同步文件: /usr/local/app/efss/rewritesub.json
[softup...js info][2022-03-08 20:21:02.530] rewritesub.json [>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 100%
[softup...js info][2022-03-08 20:21:02.518] 同步文件: /usr/local/app/efss/readme.md
[softup...js info][2022-03-08 20:21:02.517] readme.md [>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 100%
[softup...js info][2022-03-08 20:21:02.511] 同步文件: /usr/local/app/Readme.md
[softup...js info][2022-03-08 20:21:02.510] Readme.md [>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 100%
[softup...js info][2022-03-08 20:21:02.273] 同步文件: /usr/local/app/config.js
[softup...js info][2022-03-08 20:21:02.273] config.js [>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 100%
[softup...js info][2022-03-08 20:21:02.073] 获取更新: https://raw.githubusercontent.com/elecV2/elecV2P/master/efss/readme.md
[softup...js info][2022-03-08 20:21:02.070] 获取更新: https://raw.githubusercontent.com/elecV2/elecV2P/master/efss/favend.png
[softup...js info][2022-03-08 20:21:02.066] 获取更新: https://raw.githubusercontent.com/elecV2/elecV2P/master/config.js
[softup...js info][2022-03-08 20:21:02.065] 根据 CONFIG.noupdate 设置: Todo 跳过 Todo.md 更新
[softup...js info][2022-03-08 20:21:02.059] 获取更新: https://raw.githubusercontent.com/elecV2/elecV2P/master/Readme.md
[softup...js info][2022-03-08 20:21:02.059] 根据 CONFIG.noupdate 设置: Docker 跳过 Docker/readme.md 更新
[softup...js info][2022-03-08 20:21:02.059] 根据 CONFIG.noupdate 设置: Docker 跳过 Docker/hooks/pre_build 更新
[softup...js info][2022-03-08 20:21:02.059] 根据 CONFIG.noupdate 设置: Docker 跳过 Docker/hooks/post_checkout 更新
[softup...js info][2022-03-08 20:21:02.059] 根据 CONFIG.noupdate 设置: Docker 跳过 Docker/docker-compose.yaml 更新
[softup...js info][2022-03-08 20:21:02.058] 根据 CONFIG.noupdate 设置: Docker 跳过 Docker/docker-compose.dsock.yaml 更新
[softup...js info][2022-03-08 20:21:02.058] 根据 CONFIG.noupdate 设置: Docker 跳过 Docker/docker-compose.arm64.yaml 更新
[softup...js info][2022-03-08 20:21:02.058] 根据 CONFIG.noupdate 设置: Docker 跳过 Docker/docker-compose.arm32.yaml 更新
[softup...js info][2022-03-08 20:21:02.058] 根据 CONFIG.noupdate 设置: Docker 跳过 Docker/Dockerfile.arm64 更新
[softup...js info][2022-03-08 20:21:02.058] 根据 CONFIG.noupdate 设置: Docker 跳过 Docker/Dockerfile.arm32 更新
[softup...js info][2022-03-08 20:21:02.057] 根据 CONFIG.noupdate 设置: Docker 跳过 Docker/Dockerfile 更新
[softup...js info][2022-03-08 20:21:02.057] 根据 CONFIG.noupdate 设置: ^\. 跳过 .gitignore 更新
[softup...js info][2022-03-08 20:21:02.057] 根据 CONFIG.noupdate 设置: ^\. 跳过 .github/workflows/main.yml 更新
[softup...js info][2022-03-08 20:21:02.056] 根据 CONFIG.noupdate 设置: ^\. 跳过 .dockerignore 更新
[soft...js result][2022-03-08 20:21:01.667] softupdat77e.js 返回值为空
[softup...js info][2022-03-08 20:21:01.411] 开始获取更新文件列表...
[softup...js info][2022-03-08 20:21:01.410] 没有设置 webhook token, 跳过发送任务保存的网络请求
[softup...js info][2022-03-08 20:21:01.410] 所有默认依赖已安装
[softup...js info][2022-03-08 20:21:01.410] module rss installed
[softup...js info][2022-03-08 20:21:01.410] module pm2 installed
[softup...js info][2022-03-08 20:21:01.409] module node-cron installed
[softup...js info][2022-03-08 20:21:01.409] module formidable installed
[softup...js info][2022-03-08 20:21:01.409] module cheerio installed
[softup...js info][2022-03-08 20:21:01.409] module axios installed
[softup...js info][2022-03-08 20:21:01.409] module anyproxy installed
[softup...js info][2022-03-08 20:21:01.408] module adm-zip installed
[softup...js info][2022-03-08 20:21:01.408] 开始检测默认依赖是否安装
[softup...js info][2022-03-08 20:21:01.408] 检测到有新的版本: 3.6.1
[softup...js info][2022-03-08 20:21:01.407] elecV2P 当前版本: 3.5.8 最新版本: 3.6.1
[softup...js info][2022-03-08 20:21:01.043] 开始获取 elecV2P 最新版本号...
[wbjsfile    info][2022-03-08 20:21:01.040] ::ffff:192.168.52.1 post softupdat77e.js totest

**Comment by elecV2** [comment]
最新版的 https://raw.githubusercontent.com/elecV2/elecV2P/master/script/JSFile/softupdate.js 应该已经解决了这个问题

假如问题依然存在，欢迎重开 issue
