### ISSUE TITLE
在post的时候，若data或者body为空时 会把url上的参数放进data中，导致请求失败

### ISSUE THREAD

**Issue by jim114042** [elecV2/elecV2P#163]
在 eaxios.js 中的代码

// 非 GET 请求 url 参数移动到 body 内
  if (request.method.toLowerCase() !== 'get' && !request.data && /\?/.test(request.url)) {
    request.data = request.url.split('?').pop()
  }

能否去除这段

**Comment by elecV2** [comment]
这个是因为某些请求body为空时，出现了错误，后来加上去的。
严格意义上来说，elecV2P 确实不应该（需要）做这种转换，但加了后解决了一些脚本问题，也没引起别的问题（到目前为止），所以就没管了。
如果有问题了的话，方不方便把这个出现问题的请求发过来，我测试一下。或者贴一下有无body时的不同返回结果。

**Comment by jim114042** [comment]
这个是请求参数 {"url":"https://fiction.fengdunovel.com/doReader/api/readtime?_token=36b*******************a&_sign=YzFmZDEyMTk1ZjZhOTVmNGM5ZWJmNDk0ODFiNTEwZT&_sv=v1&_ts=1644641352&reading_time=60","headers":{"Accept":"*/*","Accept-Encoding":"gzip, deflate, br","Accept-Language":"zh-Hans-CN;q=1","Connection":"keep-alive","Host":"fiction.fengdunovel.com:443","User-Agent":"FDReader/2.5.3 (iPhone; iOS 15.3.1; Scale/2.00)","Date":"Sat, 12 Feb 2022 04:49:11 GMT"}}

有body时 
{"req_id":0,"result_code":4002,"timestamp":"1644641351","result":{"error_code":4002,"title":"服务器凌乱啦"},"err_msg":"4002: sign invalid","is_ios":false}

无body时
{"error_msg":"Ok","is_ios":false,"result":{"encryptUserId":"3262812359873072297","today_reading_time":240},"result_code":2000,"timestamp":"1644641062"}

**Comment by elecV2** [comment]
好的，感谢反馈。下个版本应该会进行优化/修复
