### ISSUE TITLE
可否加上外部代理？配合ClashX等SSR客户端

### ISSUE THREAD

**Issue by ibearye** [elecV2/elecV2P#164]
系统请求由elecV2P代理，elecV2P请求转发到ClashX，可以SSR上网的同时也可以用到elecV2P的REWRITE的一些功能。

**Comment by elecV2** [comment]
之后可能会添加这方面的功能，但以目前的时间和精力暂时还搞不过来。
现在你可以把clash作为系统代理，把需要rewrite 的请求转发到elecV2P
