### ISSUE TITLE
v2p证书能否装到系统证书

### ISSUE THREAD

**Issue by wcn666** [elecV2/elecV2P#165]
安卓已经root。可以用小黄鸟抓到包。但是用v2p没网，可不可以把v2p证书安装到安卓系统证书里面呀？这样是否就可以用v2p抓包呀

**Comment by elecV2** [comment]
理论上应该是可以的。但很久没用过安卓了，我不知道具体怎么操作

**Comment by wcn666** [comment]
> 理论上应该是可以的。但很久没用过安卓了，我不知道具体怎么操作
> 
> 

我试着直接把rootCA复制到系统证书目录，但是不行，因为安卓证书是.0格式，因此我不知道要怎么弄，大佬有办法把这证书格式转化为通用吗？这样的话就可以实现v2p+boxjs的安卓版QX功能了，

**Comment by elecV2** [comment]
.0是什么格式？这个还得去学习一下

**Comment by wcn666** [comment]
> .0是什么格式？这个还得去学习一下
> 
> 

![image](https://user-images.githubusercontent.com/80608339/164579199-8e40a6f2-bd17-461c-b6cd-6c4c295fae3d.jpeg)
系统证书目录都是这种，安卓小黄鸟可以导出为系统证书格式，因此可以把小黄鸟证书装到系统证书，但是v2p证书格式为root.CA，我就不会，我没学过这些，所以希望大佬有时间的话可以解决一下，对于安卓用户是一大福音。

**Comment by wcn666** [comment]
> .0是什么格式？这个还得去学习一下
> 
> 

https://blog.csdn.net/weixin_35414484/article/details/117316403这是我看到的其他证书互相转换的，讲道理这个v2p证书应该也可以转换的求大佬解决

**Comment by wcn666** [comment]
大佬，还有就是，我能不能直接把小黄鸟导出的证书作为v2p证书，格式为.pem或者.0,我上传提示我差文件，我不懂这个，请问需要如何转换呀，这样的话应该也可以实现v2p抓包安卓https

**Comment by elecV2** [comment]
需要把 pem 格式转换为 crt的格式，得到 .crt 和 .key 两个文件，分别重命名为 rootCA.crt/rootCA.key 然后再上传

**Comment by wcn666** [comment]
> 需要把 pem 格式转换为 crt的格式，得到 .crt 和 .key 两个文件，分别重命名为 rootCA.crt/rootCA.key 然后再上传
> 
> 

请问这个转换麻烦嘛。我学医的，对这个小白，可以赞助求帮忙，如果这个能用就真的安卓抓包非常方便

**Comment by elecV2** [comment]
不难啊🤔。
网上搜一下 openssl 的转换命令，或者还有在线转换的（安全考虑，不建议）。

**Comment by wcn666** [comment]
> 不难啊🤔。
> 
> 网上搜一下 openssl 的转换命令，或者还有在线转换的（安全考虑，不建议）。
> 
> 

我没学过这些网络方面的课程，对我来说很难啊…我去试试，不行来求教大佬，

**Comment by elecV2** [comment]
rootCA.crt 转 .0 格式证书的方法

首先，在 rootCA.crt 同目录下执行命令 openssl x509 -in rootCA.crt -noout -subject_hash_old
得到一个长度为 8 的 hash 值，然后复制一份 rootCA.crt 文件，重命名为 hash值.0 比如 ab1234cd.0
