### ISSUE TITLE
为啥8002端口没有https的解密日志呢，证书安装到系统目录，手机也有网

### ISSUE THREAD

**Issue by qirenzhidao** [elecV2/elecV2P#168]
曾经有过抓成功的记录。我是端口常年开着的，我会偶尔出现过突然不解密https的情况，但之前重新关闭开启端口就好了。但今天怎么试都不行。8002端口压根没有https的任何记录，这是哪方面出了问题呢

**Comment by elecV2** [comment]
在 webUI 首页看一下 NODEJS的版本，如果是 18.0.0 话尝试降级一下，或者重装一下DOCKER

**Comment by qirenzhidao** [comment]
> 在 webUI 首页看一下 NODEJS的版本，如果是 18.0.0 话尝试降级一下，或者重装一下DOCKER

nodejs 16.10.0 

我是最新版3.6.6降级到3.4.9   因为最新版出现了这问题，我就docker-compose down删除了容器。 拉取3.4.9的镜像再up -d   依然不行。难道是证书的问题？我证书是没换过的，刚刚又尝试换了新的证书，手机重新下载更新证书，还是不行。难道是跟软件有关系吗？我是想抓的中青（最新版），中青有网，一切操作正常，就是8002没有https的记录。MITM全部解密或者按host解密，都没有任何一条https的log  用手机小黄鸟抓，是有https记录的

**Comment by qirenzhidao** [comment]
8002里全是 connect和get的记录，code200.都是http的

**Comment by qirenzhidao** [comment]
刚尝试了一下。 mitm全部解密，浏览器打开baidu.com。。。也并没有https的log

**Comment by qirenzhidao** [comment]
好像是跟软件有关系。中青最新版解密不出来
