### ISSUE TITLE
模仿issues94写 node执行

### ISSUE THREAD

**Issue by huanzhiyi** [elecV2/elecV2P#169]
https://github.com/elecV2/elecV2P/issues/94

文件名 jd_bean_change.env.js
$exec('node jd_bean_change.js', {
  cwd: 'script/JSFile',
  env: {
    JD_COOKIE: $store.get('CookiesJDV2P', 'string'),  
  },
  timeout: 0,
  cb(data, error){
    error ? console.error(error) : console.log(data)
  }
})

提示 $exec is not defined  运行版本3.6.8  定时任务 shell命令 node  jd_bean_change.env.js -cwd script/JSFile
请问这个问题如何解决

**Comment by elecV2** [comment]
定时任务 运行JS ，指令里面去掉 node

**Comment by huanzhiyi** [comment]
的确如此。 另外请问如何在v2p中 更好的运行js脚本，有些脚本未适配到v2p。如https://github.com/LinYuanovo/scripts/blob/main/dygy.js  请问用比较便捷的方法令这脚本在v2p中正常运行

**Comment by elecV2** [comment]
一般脚本可以尝试node 运行，在设置->环境变量相关设置添加cookie等其他信息。
如果node 也不行的话，就直接放弃吧

**Comment by huanzhiyi** [comment]
好的 明白 感谢解答

**Comment by huanzhiyi** [comment]
感谢您的来信！
