### ISSUE TITLE
一个脚本无限弹通知

### ISSUE THREAD

**Issue by minv5** [elecV2/elecV2P#17]
[utilsFeed notify][2020-12-11 10:15:16.356]: bark notify: 中青看点 获取Cookie: 成功🎉 a empty message.
没有任何通知内容。
[AnyProxy Log][2020-12-11 10:15:16]: received request to: POST kd.youth.cn/TaskCenter/sign
[AnyProxy Log][2020-12-11 10:15:16]: received request to: POST kd.youth.cn/TaskCenter/sign
[AnyProxy Log][2020-12-11 10:15:16]: received request to: POST kd.youth.cn/TaskCenter/sign
[runJSFile notify][2020-12-11 10:15:16.701]: run youth.js from rule
[youth.js  notify][2020-12-11 10:15:16.716]: 中青看点 获取阅读请求: 成功🎉  
[utilsFeed notify][2020-12-11 10:15:16.717]: bark notify: 中青看点 获取阅读请求: 成功🎉 a empty message.
没有任何通知内容。
[runJSFile notify][2020-12-11 10:15:16.732]: run youth.js from rule
[youth.js  notify][2020-12-11 10:15:16.747]: 中青看点 获取Cookie: 成功🎉  
[utilsFeed notify][2020-12-11 10:15:16.747]: bark notify: 中青看点 获取Cookie: 成功🎉 a empty message.
没有任何通知内容。
[AnyProxy Log][2020-12-11 10:15:16]: received request to: POST kd.youth.cn/TaskCenter/sign
[runJSFile notify][2020-12-11 10:15:16.897]: run youth.js from rule
[youth.js  notify][2020-12-11 10:15:16.912]: 中青看点 获取阅读请求: 成功🎉  
[utilsFeed notify][2020-12-11 10:15:16.914]: bark notify: 中青看点 获取阅读请求: 成功🎉 a empty message.
没有任何通知内容。
[AnyProxy ERROR][2020-12-11 10:15:17]: Error: connect ETIMEDOUT 198.18.0.196:80
[AnyProxy ERROR][2020-12-11 10:15:17]: Error: connect ETIMEDOUT 198.18.0.196:80
[AnyProxy ERROR][2020-12-11 10:15:17]: Error: connect ETIMEDOUT 198.18.0.196:80
[AnyProxy ERROR][2020-12-11 10:15:17]: Error: connect ETIMEDOUT 198.18.0.196:80
[AnyProxy ERROR][2020-12-11 10:15:17]: Error: connect ETIMEDOUT 198.18.0.196:80
[AnyProxy ERROR][2020-12-11 10:15:17]: Error: connect ETIMEDOUT 198.18.0.196:80
[AnyProxy ERROR][2020-12-11 10:15:17]: Error: connect ETIMEDOUT 198.18.0.196:80
[AnyProxy ERROR][2020-12-11 10:15:17]: Error: connect ETIMEDOUT 198.18.0.196:80
[AnyProxy ERROR][2020-12-11 10:15:17]: Error: connect ETIMEDOUT 198.18.0.196:80
[AnyProxy ERROR][2020-12-11 10:15:17]: Error: connect ETIMEDOUT 198.18.0.196:80
[AnyProxy ERROR][2020-12-11 10:15:17]: Error: connect ETIMEDOUT 198.18.0.196:80
[AnyProxy ERROR][2020-12-11 10:15:17]: Error: connect ETIMEDOUT 198.18.0.196:80
[AnyProxy ERROR][2020-12-11 10:15:17]: Error: connect ETIMEDOUT 198.18.0.196:80
[AnyProxy Log][2020-12-11 10:15:18]: received request to: POST kd.youth.cn/TaskCenter/sign
[AnyProxy Log][2020-12-11 10:15:18]: received request to: POST kd.youth.cn/TaskCenter/sign
[AnyProxy Log][2020-12-11 10:15:18]: received request to: POST kd.youth.cn/TaskCenter/sign
[AnyProxy Log][2020-12-11 10:15:18]: received request to: POST kd.youth.cn/TaskCenter/sign
[AnyProxy Log][2020-12-11 10:15:18]: received request to: POST kd.youth.cn/TaskCenter/sign
[AnyProxy Log][2020-12-11 10:15:18]: received request to: POST kd.youth.cn/TaskCenter/sign
[AnyProxy Log][2020-12-11 10:15:18]: received request to: POST kd.youth.cn/TaskCenter/sign
[AnyProxy Log][2020-12-11 10:15:18]: received request to: POST kd.youth.cn/TaskCenter/sign
[AnyProxy Log][2020-12-11 10:15:18]: received request to: POST kd.youth.cn/TaskCenter/sign
[AnyProxy Log][2020-12-11 10:15:18]: received request to: POST kd.youth.cn/TaskCenter/sign
[AnyProxy Log][2020-12-11 10:15:18]: received request to: POST kd.youth.cn/TaskCenter/sign
[AnyProxy Log][2020-12-11 10:15:18]: received request to: POST kd.youth.cn/TaskCenter/sig

**Comment by minv5** [comment]
Error: Cannot read property 'read_score' of undefined
    at evalmachine.<anonymous>:537:31
    at evalmachine.<anonymous>:725:5292
    at /usr/local/app/script/context.js:113:23
    at <anonymous>
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at runNextTicks (node:internal/process/task_queues:62:3)
    at listOnTimeout (node:internal/timers:525:9)
    at processTimers (node:internal/timers:499:7)
[youth.js   error][2020-12-11 10:16:58.932]: $httpClient post {"url":"https://ios.baertt.com/v5/article/complete.json","headers":{"User-Agent":"Mozilla/5.0 (iPhone; CPU iPhone OS 13_7 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148","Content-Type":"application/x-www-form-urlencoded"},"body":"p=9NwGV8Ov71o%3DgW5NEpb6rjb84bkaCQyOq-myT0C-Ktb_nHSVk1s5Pk1lOQlYKzDUPU9y0FiOH2nIRqKp1NEljKT7rNHR8sm-zNM1uYF037ZLhJ3Xl0xswFUmY-cQ_hr0wixkQsFjVI3HBBKV9Vi7Arv9ucr9IYetIj9Zqs0mPLwQax27ryeUONkX-X3wt0uoM_BEK7EZTs2jxIQ2zgkoAElwJDPsMZYsJsw9bQLIpt1Sam7XtbrH0pb2WQ8hRUrjzM5F0Am1MdW1Wpqw1oQSrI2c6fiaqAVX2bydZGBMtfgzeTASzB_nk4I6ndCAjzTzGYM0UBo5nOzKZBJqYMvEEGsTN3yY2tqgBzQepFj_ztx0Yh6CXyiuJwxNBwx44jTVgxcA8fkJNNszrD_AwGhgSw2sxFCKzwnnjjQZObWU6sG8mETG6BcK4w2Re_eAMgAzo1lb2DO2DTarThscxB9Xoiar8EHUXz8WPb6_OqifmtjHvfFAo_onuqtfzO-sRgX_T8ZPoyUmtp4bhXOf34vuFfqwV2JAP0Tr9YHnBD3kR-am480_N_qcHS8-k3or_pghS3rix9SlT2CsojNZ0x45m8ET266A5J0c-yGtPevRUP_KZG5TqoyDgncAfTbHcsDNeNt24bZy1ij-g7OcYTt1yRBkqYjfOz5M07yIkFlyb2vIOvfRhbSe4jArPBn0zIO6Q3_oef9BzY_Ezzh5wFO82XzbH_fkezNdAvM23FAu3TKno6ps2eGlPNJBnE0Yw9oVPVuj8hY0Foh8h27x4sRlLeN84gfxWX-M39WxwlfTDEi6Ci6qcZjCH4d24UPIY9IQFWyWOj6EMWjjqtKtmb82lsMt-PjuHotOtg%3D%3D","method":"post"} timeout of 5000ms exceeded
[youth.js   error][2020-12-11 10:16:58.935]: $httpClient post https://ios.baertt.com/v5/article/complete.json cb error: TypeError: Cannot read property 'read_score' of undefined
    at evalmachine.<anonymous>:537:31
    at evalmachine.<anonymous>:725:5292
    at /usr/local/app/script/context.js:113:23
    at <anonymous>
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at runNextTicks (node:internal/process/task_queues:62:3)
    at listOnTimeout (node:internal/timers:525:9)
    at processTimers (node:internal/timers:499:7)
[youth.js   error][2020-12-11 10:16:58.937]: $httpClient post {"url":"https://ios.baertt.com/v5/article/complete.json","headers":{"User-Agent":"Mozilla/5.0 (iPhone; CPU iPhone OS 13_7 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148","Content-Type":"application/x-www-form-urlencoded"},"body":"p=9NwGV8Ov71o%3DgW5NEpb6rjb84bkaCQyOq-myT0C-Ktb_nHSVk1s5Pk1lOQlYKzDUPU9y0FiOH2nIRqKp1NEljKT7rNHR8sm-zNM1uYF037ZLhJ3Xl0xswFUmY-cQ_hr0wixkQsFjVI3HBBKV9Vi7Arv9ucr9IYetIj9Zqs0mPLwQax27ryeUONkX-X3wt0uoM_BEK7EZTs2jxIQ2zgkoAElwJDPsMZYsJsw9bQLIpt1Sam7XtbrH0pb2WQ8hRUrjzM5F0Am1MdW1Wpqw1oQSrI2c6fiaqAVX2bydZGBMtfgzeTASzB_nk4I6ndCAjzTzGYM0UBo5nOzKZBJqYMvEEGsTN3yY2tqgBzQepFj_ztx0Yh6CXyiuJwxNBwx44jTVgxcA8fkJNNszrD_AwGhgSw2sxFCKzwnnjjQZObWU6sG8mETG6BcK4w2Re_eAMgAzo1lb2DO2DTarThscxB9Xoiar8EHUXz8WPb6_OqifmtjHvfFAo_onuqtfzO-sRgX_T8ZPoyUmtp4bhXOf34vuFfqwV2JAP0Tr9YHnBD3kR-am480_N_qcHS8-k3or_pghS3rix9SlT2CsojNZ0x45m8ET266A5J0c-yGtPevRUP_KZG5TqoyDgncAfTbHcsDNeNt24bZy1ij-g7OcYTt1yRBkqYjfOz5M07yIkFlyb2vIOvfRhbSe4jArPBn0zIO6Q3_oef9BzY_Ezzh5wFO82XzbH_fkezNdAvM23FAu3TKno6ps2eGlPNJBnE0Yw9oVPVuj8hY0Foh8h27x4sRlLeN84gfxWX-M39WxwlfTDEi6Ci6qcZjCH4d24UPIY9IQFWyWOj6EMWjjqtKtmb82lsMt-PjuHotOtg%3D%3D","method":"post"} timeout of 5000ms exceeded
[youth.js   error][2020-12-11 10:16:58.939]: $httpClient post https://ios.baertt.com/v5/article/complete.json cb error: TypeError: Cannot read property 'read_score' of undefined
    at evalmachine.<anonymous>:537:31
    at evalmachine.<anonymous>:725:5292
    at /usr/local/app/script/context.js:113:23
    at <anonymous>
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at runNextTicks (node:internal/process/task_queues:62:3)
    at listOnTimeout (node:internal/timers:525:9)
    at processTimers (node:internal/timers:499:7)
[youth.js   error][2020-12-11 10:16:58.940]: $httpClient post {"url":"https://ios.baertt.com/v5/article/complete.json","headers":{"User-Agent":"Mozilla/5.0 (iPhone; CPU iPhone OS 13_7 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148","Content-Type":"application/x-www-form-urlencoded"},"body":"p=9NwGV8Ov71o%3DgW5NEpb6rjb84bkaCQyOq-myT0C-Ktb_nHSVk1s5Pk1lOQlYKzDUPU9y0FiOH2nIRqKp1NEljKT7rNHR8sm-zNM1uYF037ZLhJ3Xl0xswFUmY-cQ_hr0wixkQsFjVI3HBBKV9Vi7Arv9ucr9IYetIj9Zqs0mPLwQax27ryeUONkX-X3wt0uoM_BEK7EZTs2jxIQ2zgkoAElwJDPsMZYsJsw9bQLIpt1Sam7XtbrH0pb2WQ8hRUrjzM5F0Am1MdW1Wpqw1oQSrI2c6fiaqAVX2bydZGBMtfgzeTASzB_nk4I6ndCAjzTzGYM0UBo5nOzKZBJqYMvEEGsTN3yY2tqgBzQepFj_ztx0Yh6CXyiuJwxNBwx44jTVgxcA8fkJNNszrD_AwGhgSw2sxFCKzwnnjjQZObWU6sG8mETG6BcK4w2Re_eAMgAzo1lb2DO2DTarThscxB9Xoiar8EHUXz8WPb6_OqifmtjHvfFAo_onuqtfzO-sRgX_T8ZPoyUmtp4bhXOf34vuFfqwV2JAP0Tr9YHnBD3kR-am480_N_qcHS8-k3or_pghS3rix9SlT2CsojNZ0x45m8ET266A5J0c-yGtPevRUP_KZG5TqoyDgncAfTbHcsDNeNt24bZy1ij-g7OcYTt1yRBkqYjfOz5M07yIkFlyb2vIOvfRhbSe4jArPBn0zIO6Q3_oef9BzY_Ezzh5wFO82XzbH_fkezNdAvM23FAu3TKno6ps2eGlPNJBnE0Yw9oVPVuj8hY0Foh8h27x4sRlLeN84gfxWX-M39WxwlfTDEi6Ci6qcZjCH4d24UPIY9IQFWyWOj6EMWjjqtKtmb82lsMt-PjuHotOtg%3D%3D","method":"post"} timeout of 5000ms exceeded
[youth.js   error][2020-12-11 10:16:58.942]: $httpClient post https://ios.baertt.com/v5/article/complete.json cb error: TypeError: Cannot read property 'read_score' of undefined
    at evalmachine.<anonymous>:537:31
    at evalmachine.<anonymous>:725:5292
    at /usr/local/app/script/context.js:113:23
    at <anonymous>
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at runNextTicks (node:internal/process/task_queues:62:3)
    at listOnTimeout (node:internal/timers:525:9)
    at processTimers (node:internal/timers:499:7)
[youth.js   error][2020-12-11 10:16:58.945]: $httpClient post {"url":"https://ios.baertt.com/v5/article/complete.json","headers":{"User-Agent":"Mozilla/5.0 (iPhone; CPU iPhone OS 13_7 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148","Content-Type":"application/x-www-form-urlencoded"},"body":"p=9NwGV8Ov71o%3DgW5NEpb6rjb84bkaCQyOq-myT0C-Ktb_nHSVk1s5Pk1lOQlYKzDUPU9y0FiOH2nIRqKp1NEljKT7rNHR8sm-zNM1uYF037ZLhJ3Xl0xswFUmY-cQ_hr0wixkQsFjVI3HBBKV9Vi7Arv9ucr9IYetIj9Zqs0mPLwQax27ryeUONkX-X3wt0uoM_BEK7EZTs2jxIQ2zgkoAElwJDPsMZYsJsw9bQLIpt1Sam7XtbrH0pb2WQ8hRUrjzM5F0Am1MdW1Wpqw1oQSrI2c6fiaqAVX2bydZGBMtfgzeTASzB_nk4I6ndCAjzTzGYM0UBo5nOzKZBJqYMvEEGsTN3yY2tqgBzQepFj_ztx0Yh6CXyiuJwxNBwx44jTVgxcA8fkJNNszrD_AwGhgSw2sxFCKzwnnjjQZObWU6sG8mETG6BcK4w2Re_eAMgAzo1lb2DO2DTarThscxB9Xoiar8EHUXz8WPb6_OqifmtjHvfFAo_onuqtfzO-sRgX_T8ZPoyUmtp4bhXOf34vuFfqwV2JAP0Tr9YHnBD3kR-am480_N_qcHS8-k3or_pghS3rix9SlT2CsojNZ0x45m8ET266A5J0c-yGtPevRUP_KZG5TqoyDgncAfTbHcsDNeNt24bZy1ij-g7OcYTt1yRBkqYjfOz5M07yIkFlyb2vIOvfRhbSe4jArPBn0zIO6Q3_oef9BzY_Ezzh5wFO82XzbH_fkezNdAvM23FAu3TKno6ps2eGlPNJBnE0Yw9oVPVuj8hY0Foh8h27x4sRlLeN84gfxWX-M39WxwlfTDEi6Ci6qcZjCH4d24UPIY9IQFWyWOj6EMWjjqtKtmb82lsMt-PjuHotOtg%3D%3D","method":"post"} timeout of 5000ms exceeded
root@OpenWrt:~#

**Comment by minv5** [comment]
![image](https://user-images.githubusercontent.com/54812955/101853172-2499e580-3b9a-11eb-87df-1fbd66c2055c.png)

**Comment by elecV2** [comment]
1. 别把这个网络请求代理到 anyproxy 端口
2. 或者注释掉（修改）获取 cookie 的相关规则，需要时再添加。

（此类脚本使用及基础规则设置问题，今后不再解答。）
