### ISSUE TITLE
只要结尾不是js的，都会报“脚本文件名错误”

### ISSUE THREAD

**Issue by maryjeck** [elecV2/elecV2P#172]
只要结尾不是js的，都会报“脚本文件名错误”，请修复啊

后面只有转战青龙解决的

**Comment by elecV2** [comment]
脚本管理哪一块确实只能处理JS脚本，其他文件按道理应该也不会显示才对。

如果要处理其他格式的文件，在EFSS界面设置对应文件目录，然后右键选择编辑
