### ISSUE TITLE
重写里现在支持</script>window.back</script>类似这种动作的代码么

### ISSUE THREAD

**Issue by qirenzhidao** [elecV2/elecV2P#174]
重写里现在支持</script>window.back</script>类似这种动作的代码么

圈x是可以这样的，不知道v2p可以支持不

**Comment by elecV2** [comment]
暂时还不支持。

目前的话，你可以考虑写个简单的脚本来插入这段代码，类似于 
$done($response.body+'<script>window.back()</script>')

**Comment by qirenzhidao** [comment]
> 暂时还不支持。 目前的话，你可以考虑写个简单的脚本来插入这段代码，类似于 $done($response.body+'<script>window.back()</script>')

感谢，我想过这个思路，写个这种的js，我再试试
