### ISSUE TITLE
一直报错websocket 连接失败

### ISSUE THREAD

**Issue by goooxyz** [elecV2/elecV2P#176]
[websocket  error][2022-12-09 23:44:21.280] websocket 连接失败，请检查网络后尝试刷新页面
[websocket  error][2022-12-09 23:43:57.739] websocket 已断开，将在 45 秒后尝试重连（如果不是手动断开或网络问题，可能是某个脚本运行出错，导致 elecV2P 重启，请根据 errors.log 和当前时间，找到相应脚本进行修改）

**Comment by elecV2** [comment]
可能是网络问题（小概率），也可能elecV2P 没有启动，或启动失败（大概率）。建议在后台使用 docker 或 pm 命令查看一下 elecV2P 的状态
