### ISSUE TITLE
提个建议，希望能采纳

### ISSUE THREAD

**Issue by shange1993** [elecV2/elecV2P#177]
就是对接的目录太多了，能不能搞个一个用户数据的目录，类似和青龙那样，搞个data目录，在把用户数据目录全部放到这里面，以后就对接这一个目录就好了

**Comment by elecV2** [comment]
好建议，不过修改起来很麻烦，暂时改不了。

目前可以根据配置文件说明文档 https://github.com/elecV2/elecV2P-dei/blob/master/docs/10-config.md 中的path_lists/script 相关部分，手动修改 config.json 配置文件，将用户数据目录修改为指定目录，比如 data/lists, data/script, data/store 等，然后保存重启。

或者搜索一下 软链接和硬链接 相关的知识，可以把不同目录的数据硬链接（备份）到同一个目录下。

（建议已记录，以后有时间再完成
