### ISSUE TITLE
提个新功能建议

### ISSUE THREAD

**Issue by DYS7516461** [elecV2/elecV2P#178]
建议可以根据mitm设置生成安卓pac文件，类似于分流列表页面，生成一个订阅链接，根据mitm中启用的域名生成pac文件，毕竟抓手机包的用户可能比较多，但是并不是所有用户都安装了分流软件，我现在暂时通过efss文件管理+临时token实现了远程pac文件订阅

**Comment by DYS7516461** [comment]
暂时没有实现动态根据mitm设置修改pac文件

**Comment by elecV2** [comment]
已记录，之后版本更新（春节后

**Comment by elecV2** [comment]
最新版 v3.7.7+ 已增加该功能，相关说明文档参考：https://github.com/elecV2/elecV2P-dei/blob/master/docs/Advanced.md 相关部分
