### ISSUE TITLE
是否能接入boxjs

### ISSUE THREAD

**Issue by q123458384** [elecV2/elecV2P#18]
首先感谢作者的无私奉献。
我一直把这个项目当成电脑版本的quanx来使用，主要是运行一些定时js脚本任务。
不知道能否接入boxjs
实现自动抓取部分cookie
boxjs项目地址：https://github.com/chavyleung/boxjs-doc

因为是行外人，不太清楚是否有可实现性

**Comment by elecV2** [comment]
可以自己添加规则实现，具体参考https://github.com/elecV2/elecV2P-dei/blob/master/examples/JSTEST/boxjs.ev.js

更详细的步骤还得自行谷歌。

> 首先感谢作者的无私奉献。
> 我一直把这个项目当成电脑版本的quanx来使用，主要是运行一些定时js脚本任务。
> 不知道能否接入boxjs
> 实现自动抓取部分cookie
> boxjs项目地址：https://github.com/chavyleung/boxjs-doc
> 
> 因为是行外人，不太清楚是否有可实现性

**Comment by q123458384** [comment]
> 可以自己添加规则实现，具体参考https://github.com/elecV2/elecV2P-dei/blob/master/examples/JSTEST/boxjs.ev.js 更详细的步骤还得自行谷歌。
> […](#)
> 首先感谢作者的无私奉献。 我一直把这个项目当成电脑版本的quanx来使用，主要是运行一些定时js脚本任务。 不知道能否接入boxjs 实现自动抓取部分cookie boxjs项目地址：https://github.com/chavyleung/boxjs-doc 因为是行外人，不太清楚是否有可实现性

按照脚本说明设置后打开boxjs.com提示错误
```AnyProxy Inner Error
Error: getaddrinfo EAI_AGAIN boxjs.com
at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:67:26)
```

测试环境win10 edge(chrome内核版) 使用swithyOmega插件 添加V2P的代理地址 设定为全局
// 在 JSMANAGE 中上传该文件
// RULES 添加: host boxjs.com JS boxjs.ev.js 网络请求前
// MITM  添加: boxjs.com (已经安装证书)
// rewrite 添加： https://raw.githubusercontent.com/elecV2/elecV2P-dei/master/examples/JSTEST/boxjs.ev.js

通过anyproxy 代理面板，别的网页可以正常访问并有抓包数据
boxjs.com 转态码500

**Comment by elecV2** [comment]
﻿

boxjs 首次启动时要从另外一个网站下载一些基础数据（cdn.jsdeliver.xxx) 可能要科学上网才能访问。尝试在 webUI SETTING  eAxios 相关设置那里填一下代理，再访问吧。

另外，在 JSMANAGE 那里，用模拟请求 服务器 axios 看一下能不能访问外网。

如果还有错误，把 elecV2P 运行的这一段日志都发我看一下。

 PS: rewrite 的规则不需要。

**Comment by q123458384** [comment]
> ﻿ boxjs 首次启动时要从另外一个网站下载一些基础数据（cdn.jsdeliver.xxx) 可能要科学上网才能访问。尝试在 webUI SETTING eAxios 相关设置那里填一下代理，再访问吧。 另外，在 JSMANAGE 那里，用模拟请求 服务器 axios 看一下能不能访问外网。 如果还有错误，把 elecV2P 运行的这一段日志都发我看一下。 PS: rewrite 的规则不需要。
> […](#)
> 可以自己添加规则实现，具体参考https://github.com/elecV2/elecV2P-dei/blob/master/examples/JSTEST/boxjs.ev.js 更详细的步骤还得自行谷歌。 … 首先感谢作者的无私奉献。 我一直把这个项目当成电脑版本的quanx来使用，主要是运行一些定时js脚本任务。 不知道能否接入boxjs 实现自动抓取部分cookie boxjs项目地址：https://github.com/chavyleung/boxjs-doc 因为是行外人，不太清楚是否有可实现性 按照脚本说明设置后打开boxjs.com提示错误 Error: getaddrinfo EAI_AGAIN boxjs.com at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:67:26) 测试环境win10 edge(chrome内核版) 使用swithyOmega插件 添加V2P的代理地址 设定为全局 // 在 JSMANAGE 中上传该文件 // RULES 添加: host boxjs.com JS boxjs.ev.js 网络请求前 // MITM 添加: boxjs.com (已经安装证书) // rewrite 添加： https://raw.githubusercontent.com/elecV2/elecV2P-dei/master/examples/JSTEST/boxjs.ev.js 通过anyproxy 代理面板，别的网页可以正常访问并有抓包数据 boxjs.com 转态码500 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

V2P是运行在N1的docker容器中的，N1所在路由器设置了代理，是可以科学上网的。

服务器 axios get google.com 也有有数据返回，电脑edge浏览器通过 http://V2Pip:8101 代理，也可以正常访问墙内外网站。



错入日志
[AnyProxy Log][2020-12-17 17:55:06]: will bypass the man-in-the-middle proxy
[AnyProxy Log][2020-12-17 17:55:07]: received https CONNECT request fonts.gstatic.com
[AnyProxy Log][2020-12-17 17:55:07]: will bypass the man-in-the-middle proxy

[AnyProxy ERROR][2020-12-17 17:55:08]: Error: getaddrinfo EAI_AGAIN boxjs.com

**Comment by elecV2** [comment]
那就没办法了，尝试先在 MITM 中删除其他域名证书然后重启。

实在不行，再尝试删除 docker 重建一次 (记得先备份重要数据)。

再不行，就放弃吧。
﻿

**Comment by q123458384** [comment]
才刚装的=、=，只有一个域名
getaddrinfo EAI_AGAIN 这个百度了下搜不到一样的资料

改天我换个环境测试一下吧~~谢谢解答



> 那就没办法了，尝试先在 MITM 中删除其他域名证书然后重启。 实在不行，再尝试删除 docker 重建一次 (记得先备份重要数据)。 再不行，就放弃吧。 ﻿
> […](#)
> ﻿ boxjs 首次启动时要从另外一个网站下载一些基础数据（cdn.jsdeliver.xxx) 可能要科学上网才能访问。尝试在 webUI SETTING eAxios 相关设置那里填一下代理，再访问吧。 另外，在 JSMANAGE 那里，用模拟请求 服务器 axios 看一下能不能访问外网。 如果还有错误，把 elecV2P 运行的这一段日志都发我看一下。 PS: rewrite 的规则不需要。 … 可以自己添加规则实现，具体参考https://github.com/elecV2/elecV2P-dei/blob/master/examples/JSTEST/boxjs.ev.js 更详细的步骤还得自行谷歌。 … 首先感谢作者的无私奉献。 我一直把这个项目当成电脑版本的quanx来使用，主要是运行一些定时js脚本任务。 不知道能否接入boxjs 实现自动抓取部分cookie boxjs项目地址：https://github.com/chavyleung/boxjs-doc 因为是行外人，不太清楚是否有可实现性 按照脚本说明设置后打开boxjs.com提示错误 Error: getaddrinfo EAI_AGAIN boxjs.com at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:67:26) 测试环境win10 edge(chrome内核版) 使用swithyOmega插件 添加V2P的代理地址 设定为全局 // 在 JSMANAGE 中上传该文件 // RULES 添加: host boxjs.com JS boxjs.ev.js 网络请求前 // MITM 添加: boxjs.com (已经安装证书) // rewrite 添加： https://raw.githubusercontent.com/elecV2/elecV2P-dei/master/examples/JSTEST/boxjs.ev.js 通过anyproxy 代理面板，别的网页可以正常访问并有抓包数据 boxjs.com 转态码500 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. V2P是运行在N1的docker容器中的，N1所在路由器设置了代理，是可以科学上网的。 服务器 axios get google.com 也有有数据返回，电脑edge浏览器通过 http://V2Pip:8101 代理，也可以正常访问墙内外网站。 错入日志 [AnyProxy Log][2020-12-17 17:55:06]: will bypass the man-in-the-middle proxy [AnyProxy Log][2020-12-17 17:55:07]: received https CONNECT request fonts.gstatic.com [AnyProxy Log][2020-12-17 17:55:07]: will bypass the man-in-the-middle proxy [AnyProxy ERROR][2020-12-17 17:55:08]: Error: getaddrinfo EAI_AGAIN boxjs.com — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
