### ISSUE TITLE
当前webUI版本低于后台v3.7.8

### ISSUE THREAD

**Issue by jim114042** [elecV2/elecV2P#181]
当前webUI版本低于后台v3.7.8   
webUI版本一直显示v3.7.7

这个如何升级？我是从3.7.6升级的， 用的下面命令升级的
docker-compose pull elecv2p && docker-compose up -d
升级完后重启也没用，一直提示webUI版本低于后台

**Comment by elecV2** [comment]
前端的版本号更新后忘了同步到 docker，刚才已经修复了。可能需要重新更新下，就用上面的命令

docker-compose pull elecv2p && docker-compose up -d
