### ISSUE TITLE
RULES规则集中无记录的时候，点保存报错

### ISSUE THREAD

**Issue by ztxtop** [elecV2/elecV2P#185]
在RULES规则集中新增一条规则保存后，再次删除仅有的一条规则，保存操作就无法正常执行

**Comment by elecV2** [comment]
Get.(待修复在 2023年9月12日，22:04，ztxtop ***@***.***> 写道：﻿
在RULES规则集中新增一条规则保存后，再次删除仅有的一条规则，保存操作就无法正常执行
