### ISSUE TITLE
能不能适配一下苹果M芯片机型

### ISSUE THREAD

**Issue by itaosson** [elecV2/elecV2P#187]
拉库都正常，进入webui，首先任务列表初始任务，脚本管理里面一个初始脚本也没有。测试一下抓包，也是不行。按理说arm架构，n1正常，我M2芯片的macmini装了10多遍了，还是没搞定。感觉应该是芯片太特殊了。麻烦佬百忙之中给看看

**Comment by elecV2** [comment]
这跟芯片应该没什么关系。能用 nodejs 就能跑。

看你是docker 安装还是 nodejs 安装的。docker的话映射目录使用空目录。实在没有脚本和任务的话，自己新建就好了。不能新建的话可能是目录没有权限，尝试在改下权限，或在其他目录安装

不能抓包，看下MITM 开了没，根证书有没有信任什么的
