### ISSUE TITLE
docker版如何更新到最新版

### ISSUE THREAD

**Issue by jinshuqishi2019** [elecV2/elecV2P#188]
你好，我是使用docker安装的，检测更新都是没有更新，版本停留在3.7.8，但是我看你仓库已经更新到3.8.0，请教docker如何更新最新版，谢谢。

**Comment by elecV2** [comment]
﻿
﻿
﻿
﻿
3.8.0 的版本还没时间搞，现在docker最新的就是3.7.8

**Comment by jinshuqishi2019** [comment]
我需要node升级到20版，因为一些包需要这个版本以上才行。
你方便的话，可以构建一个升级nodejs的docker，版本还是3.7.8吗？
