### ISSUE TITLE
chavy.boxjs无法保存数据

### ISSUE THREAD

**Issue by crossgg** [elecV2/elecV2P#189]
v2p版本：3.8.0，安装方式：docker

用的作者提供的`https://raw.githubusercontent.com/elecV2/elecV2P-dei/master/examples/JSTEST/boxjs.ev.js`可以正常使用，但是版本太老了，只有0.7.69。

用chavy 的`https://raw.githubusercontent.com/chavyleung/scripts/master/box/chavy.boxjs.js`，版本为“'0.19.2'”，无法订阅（点击没反应），设置的开关点击后也无效。在v2p面板的store里面也没有储存数据。

**Comment by elecV2** [comment]
﻿
这个好像之前有人提过。应该是最新的那个 ENV 函数改了。尝试手动替换下文件最后的那个 ENV 函数

**Comment by crossgg** [comment]
> 这个好像之前有人提过。应该是最新的那个 ENV 函数改了。尝试手动替换下文件最后的那个 ENV 函数

把chavy.boxjs.js的`env`改成您的`EnvJs`    页面只有个`BoxJs`字样没有别的内容。

目前V2P最好的用途是可以用别人的rewrite脚本抓包自动获取Cookie等数据，可能是因为脚本都是基于新的chavy.boxjs.js编写。
用您的“boxjs.ev.js” 能提示数据获取成功，但是在store里面没有数据。
不是这个原因的话boxjs的版本对我倒是没有任何影响

**Comment by elecV2** [comment]
> > 这个好像之前有人提过。应该是最新的那个 ENV 函数改了。尝试手动替换下文件最后的那个 ENV 函数
> 
> 把chavy.boxjs.js的`env`改成您的`EnvJs` 页面只有个`BoxJs`字样没有别的内容。
> 
> 目前V2P最好的用途是可以用别人的rewrite脚本抓包自动获取Cookie等数据，可能是因为脚本都是基于新的chavy.boxjs.js编写。 用您的“boxjs.ev.js” 能提示数据获取成功，但是在store里面没有数据。 不是这个原因的话boxjs的版本对我倒是没有任何影响

看了下，是ENV的环境检测函数变了。尝试在原版 chavy.boxjs.js 文件的开头添加下面一行代码：

`
$environment = {'surge-version': true}
`

![image](https://github.com/user-attachments/assets/3d2ee3bc-cf4d-4e47-840d-62adc766c71b)

**Comment by crossgg** [comment]
> `$environment = {'surge-version': true}`

感谢，通过这个办法数据可以正常保存了。
目前测试了几个只支持qx脚本的重写，提示`更新token成功! a empty message` 查看数据是空的。
测试了几个支持loon+qx+surge的重写脚本，可以正常保存数据
