### ISSUE TITLE
不能抓包了

### ISSUE THREAD

**Issue by alililala** [elecV2/elecV2P#191]
![image](https://github.com/user-attachments/assets/a4eda0f8-1635-4080-95e5-2a50d1e4d6d0)
升级最新的3.8.1版本后报这个错

**Comment by elecV2** [comment]
测试没发现有这个问题，重试或重装吧

**Comment by alililala** [comment]
> 测试没发现有这个问题，重试或重装吧

重装了还是问题依旧

**Comment by elecV2** [comment]
看了下是 node 23新版本的兼容问题，手动降级到 node 22 的版本，或者等晚上的更新

**Comment by alililala** [comment]
> 看了下是 node 23新版本的兼容问题，手动降级到 node 22 的版本，或者等晚上的更新

果然，更新后好了。没问题了。关了吧。
