### ISSUE TITLE
是否会增加py脚本运行呢？

### ISSUE THREAD

**Issue by minv5** [elecV2/elecV2P#20]
如题

**Comment by elecV2** [comment]
使用 Shell 指令可以直接运行。参考 JSMANAGE 中自带的 python-install.js
﻿
> 如题

**Comment by minv5** [comment]
所有这些运行日志是自动限时间删除还是？

**Comment by elecV2** [comment]
默认不删
﻿

**Comment by minv5** [comment]
> 默认不删 ﻿
> […](#)
> 所有这些运行日志是自动限时间删除还是？ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

这样日志越来越多大，会影响吗？
