### ISSUE TITLE
Android下运行elecV2P的问题

### ISSUE THREAD

**Issue by DoveBoy** [elecV2/elecV2P#21]
## 准备工作：
目前使用Android上的Termux搭建了一个平台跑elecV2P,git clone整个项目到`/sdcard/Github/Nodejs/`文件夹下，wifi代理设置为手动`127.0.0.1:8001`，`./anyproxy/certificate`下的证书已经复制到`/sdcard/Github/Nodejs/elecV2P/rootCA/`文件夹下，同时`rootCA.crt`已经安装到手机系统中。设置已经按照教程做好了，使用Nodejs方式运行(yarn start)，因主页面端口80无法访问，自行修改了`config.js`配置文件中的`webst: 8080`。测试能够使用Chrome Canary浏览器正常访问后台管理页面(以下简称webui)、代理请求查看端口8002(以下简称AnyProxy)
![image](https://user-images.githubusercontent.com/19201447/103165321-1f52c100-4851-11eb-9177-075163e6b3b8.png)
![image](https://user-images.githubusercontent.com/19201447/103165332-3d202600-4851-11eb-8572-3b8579ac3e82.png)
![image](https://user-images.githubusercontent.com/19201447/103165379-f1ba4780-4851-11eb-930a-a5adabb4e1b6.png)
![image](https://user-images.githubusercontent.com/19201447/103165529-0ef01580-4854-11eb-9346-e25e5544c084.png)
![image](https://user-images.githubusercontent.com/19201447/103165485-7bb6e000-4853-11eb-9d2b-a901e7408b25.png)
## 具体操作
尝试使用elecV2P抓取[企鹅阅读](https://raw.githubusercontent.com/ziye12/JavaScript/master/qqread.js)的cookie，webui中rewrite已按照脚本说明设置好，且对应的js能够正常访问。mitm中mitm host也已设置正确，cfilter中分流列表也做了设置。
访问QQ app中企鹅阅读小程序后，返回AnyProxy可以看到抓包情况
![image](https://user-images.githubusercontent.com/19201447/103165585-cdac3580-4854-11eb-9c9e-865bc7e7a655.png)
![image](https://user-images.githubusercontent.com/19201447/103165602-fdf3d400-4854-11eb-8ea9-9c0308c7e666.png)
![image](https://user-images.githubusercontent.com/19201447/103165611-1c59cf80-4855-11eb-9887-cf6199c2f724.png)
![image](https://user-images.githubusercontent.com/19201447/103165646-807c9380-4855-11eb-8b03-aea5287624be.png)
## 问题
目前出现以下几个问题，请开发者解答一下
1.AnyProxy中，抓包的网址code全部为200，是否正常？
2.AnyProxy中，选择查看抓取的url后，只有第一次可以在网页的右面看到详细信息，之后不管怎么重启elecV2P服务都不会再显示了，这个情况是什么原因？
![image](https://user-images.githubusercontent.com/19201447/103165703-fed93580-4855-11eb-8333-b18508b746b4.png)
3.已经完全按照TG频道中的教程做的，为什么cookie的解密信息依旧看不到？（rootCA.crt证书已安装，mitm中解密域名也设置了）
4.Termux日志中并不会出现类似抓取xxx cookie成功的提示
![image](https://user-images.githubusercontent.com/19201447/103165767-9474c500-4856-11eb-841c-66868bd04559.png)

恳请开发者能够解答一下，非常希望在Android上通过Termux搭建平台使用上elec2V2P，通过elec2V2P抓包，非常方便

**Comment by elecV2** [comment]
你之前的 elecV2P 可能并没有完全关闭，看到还有端口是占用，重启手机吧。

如果都是 connet 请求说明 https 解密没有成功，具体什么原因我也没法知道，看你说第一次可以成功，只能建议还是重启手机。

﻿看到 anyproxy 有个 websocket proxy  的错误，anyproxy 的 代理端口应该是 http 的，得稍微注意。

200 是最正常请求。

**Comment by DoveBoy** [comment]
@elecV2 测试中发现，虽然webUI界面可以正常访问，但是实际Termux后端并不会出现日志，只停留在`port:8001`那段，使用`Ctrl+C`并不是完全终止进程，测试需要强制停止Termux重开后再次`yarn start`才能开启新的进程。目前可以用elecV2P按照步骤抓取企鹅阅读的cookie，同时webUI中jsmanager刷新可以看到读取的cookie（内容有缺失body获取不到）。同样的操作步骤，TG中示例的JD_DailyBonus.js完全获取不到,原因找不到，请大佬解答。另外cookie解密的关键跟什么步骤有关？已经完全按照教程的操作，似乎有时并不能解密

**Comment by elecV2** [comment]
在一些版本的 nodejs 下无法终止是已知 bug，下一个版本应该会修复。

不同平台登录的 cookie 格式可能不一样，不一定通用，对照脚本中获取 cookie 的相关代码，和 8002 界面的解密内容，比较一下。

解密每个步骤都很关键，有一个步没生效就解密失败，多对照每个步骤多尝试吧，熟能生巧。

**Comment by DoveBoy** [comment]
@elecV2 已知JD的cookie在全平台是一样的，已和8002界面比较过，`api.m.jd.com`会附带cookie信息。webUI界面在mitm以及cfilter下都同时设置了hostname`api.m.jd.com`，但是jsmanager界面依旧无法自动获取到JD的cookie。
另外，一般脚本获取cookie说明中都会提示需要填写三个参数，以[企鹅阅读](https://raw.githubusercontent.com/ziye12/JavaScript/master/qqread.js)为例：url的前半部分`https:\/\/mqqapi\.reader\.qq\.com\/mqq\/user\/init`和`https:\/\/mqqapi\.reader\.qq\.com\/mqq\/addReadTimeWithBid?`以及script-request-header后的部分`https://raw.githubusercontent.com/ziye12/JavaScript/master/qqread.js`填写到相应位置。至于`hostname=mqqapi.reader.qq.com`这个是只需要填写到mitm中？还是说mitm和cfilter同时都要填写？(TG上的教程似乎是都要填？)
![image](https://user-images.githubusercontent.com/19201447/103183204-cbe18100-48eb-11eb-85f4-3fffe8fcc8a3.png)

**Comment by elecV2** [comment]
都填，重点是要把那个域名的网络请求代理到 anyproxy ，anyproxy 才能根据 url 匹配到重写规则，从而调用相应的 JS 获取 cookie。

根据你的描述看不出什么问题，多研究，多了解（相关的网络知识），多尝试吧。

**Comment by DoveBoy** [comment]
@elecV2 安卓上使用WiFi联网环境下，在WiFi设置中，代理为手动，地址`127.0.0.1`，端口`8001`。使用移动网络联网下，APN设置cmnet，代理`127.0.0.1`，端口`8001`。测试发现JD获取不到cookie，只有企鹅阅读可以。感觉自己的设置没有问题，./anyproxy/certificate/下的rootCA.crt证书也已安装到手机中，实在是不知道是什么原因。

**Comment by VectorZhao** [comment]
@DoveBoy 请问，wifi代理手动设置完就上不了网了啊。这是怎么回事？ 谢谢

**Comment by elecV2** [comment]
> @DoveBoy 请问，wifi代理手动设置完就上不了网了啊。这是怎么回事？ 谢谢

可能是证书问题，信息太少无法确定。自己对照说明文档，再多尝试几遍吧。
