### ISSUE TITLE
是否考虑增加script文件夹的自定义路径

### ISSUE THREAD

**Issue by kookpua** [elecV2/elecV2P#23]
比如我使用dropbox多台电脑同步,在一台关闭的时候使用另一台就不用重复设定脚本和cookie了

感谢楼主~

**Comment by elecV2** [comment]
暂时不会考虑。

如果有这个需求，可以搜索一下 目录映射 相关的知识。

也可以直接修改源码 utils/file.js 里的相关内容（问题未知）
﻿
> 比如我使用dropbox多台电脑同步,在一台关闭的时候使用另一台就不用重复设定脚本和cookie了
> 
> 感谢楼主~
