### ISSUE TITLE
安卓代理抓包

### ISSUE THREAD

**Issue by kingsleyzhnlanf** [elecV2/elecV2P#24]
![image](https://user-images.githubusercontent.com/76804516/103444620-e6797880-4ca4-11eb-9623-68f2ca3a2fb1.png)
使用elecV2P(安卓)抓包聚看点，出现上面错误，不清楚是否是脚本的原因
![image](https://user-images.githubusercontent.com/76804516/103444638-293b5080-4ca5-11eb-880b-5e7fc2509e9b.png)
这句话意思是这样嘛
![image](https://user-images.githubusercontent.com/76804516/103444642-35bfa900-4ca5-11eb-9a56-ac3e089d6a04.png)

**Comment by elecV2** [comment]
是。

webUI 界面。把文章再看几遍，自己多尝试。（实在不行就放弃吧。）

**Comment by kingsleyzhnlanf** [comment]
> 是。 webUI 界面。把文章再看几遍，自己多尝试。（实在不行就放弃吧。）
> […](#)
> 使用elecV2P(安卓)抓包聚看点，出现上面错误，不清楚是否是脚本的原因 这句话意思是这样嘛 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

脚本问题，换一个可以运行了
