### ISSUE TITLE
最近几个脚本都是京东服务器访问数据为空，请检查自身设备网络情况

### ISSUE THREAD

**Issue by minv5** [elecV2/elecV2P#25]
![image](https://user-images.githubusercontent.com/54812955/104276618-37c50b80-54e0-11eb-89d6-9e88323a34f1.png)

**Comment by elecV2** [comment]
服务器的问题这边没办法解决，个别脚本的使用出错不在本项目讨论范围内，自行根据错误提示修改一下脚本吧。

**Comment by minv5** [comment]
> 服务器的问题这边没办法解决，个别脚本的使用出错不在本项目讨论范围内，自行根据错误提示修改一下脚本吧。

这种错误，我问了脚本作者本人都无法解释，还怎么修改脚本啊，毕竟这运行js脚本也是项目的其中一大部分，对于我来说，出现这种问题，得不到解答真的很难受，你这会发的也含含糊糊的，毕竟出现问题要解决问题的吧

**Comment by daxinnan** [comment]
> > 服务器的问题这边没办法解决，个别脚本的使用出错不在本项目讨论范围内，自行根据错误提示修改一下脚本吧。
> 
> 这种错误，我问了脚本作者本人都无法解释，还怎么修改脚本啊，毕竟这运行js脚本也是项目的其中一大部分，对于我来说，出现这种问题，得不到解答真的很难受，你这会发的也含含糊糊的，毕竟出现问题要解决问题的吧

请问解决了吗，我还有个问题老哥，环境变量是写在docker-compose.yaml文件里还是在JSMANAGE里写
