### ISSUE TITLE
TypeError: Cannot read property 'length' of null

### ISSUE THREAD

**Issue by kingsleyzhnlanf** [elecV2/elecV2P#26]
![image](https://user-images.githubusercontent.com/76804516/104298070-87b2cb00-54fe-11eb-885f-1de63f9ade73.png)

**Comment by elecV2** [comment]
这种一般是脚本代码或网络问题，按照错误提示更改就好了。（脚本问题一般都不是我这边可以解决的，不在讨论范畴）
