### ISSUE TITLE
docker主要运行shell指令py，服务器断电重启后，任务是还在，但是js安装的py环境丢失，需要手动再次运行js安装

### ISSUE THREAD

**Issue by githooo** [elecV2/elecV2P#27]
发现任务是执行状态，但是执行失败，缺少环境了，不知道是不是操作不当。

**Comment by elecV2** [comment]
docker 如果是新创建的确实会丢失，之后可能考虑加入重启后自动运行一次某些脚本的选项。

如果缺少就再重新安装一次吧。

> 发现任务是执行状态，但是执行失败，缺少环境了，不知道是不是操作不当。

**Comment by elecV2** [comment]
3.0.2 更新，可在 webUI -> SETTING 界面添加初始化运行脚本，应该可以解决这个问题。
