### ISSUE TITLE
task 任务保存无效

### ISSUE THREAD

**Issue by q123458384** [elecV2/elecV2P#29]
在task定时任务界面
修改了任务，点击保存当前任务列表，保存后刷新又复原成原来未修改前的了。
但是重启容器，又会变成修改后的。
2021.1.19更新镜像后还是有这个问题。

**Comment by elecV2** [comment]
可能的原因是你修改了任务但并没有重新执行，后台跑的任务依旧是你修改前的。
﻿
> 在task定时任务界面
> 修改了任务，点击保存当前任务列表，保存后刷新又复原成原来未修改前的了。
> 但是重启容器，又会变成修改后的。
> 2021.1.19更新镜像后还是有这个问题。

**Comment by q123458384** [comment]
> 可能的原因是你修改了任务但并没有重新执行，后台跑的任务依旧是你修改前的。 ﻿
> […](#)
> 在task定时任务界面 修改了任务，点击保存当前任务列表，保存后刷新又复原成原来未修改前的了。 但是重启容器，又会变成修改后的。 2021.1.19更新镜像后还是有这个问题。

应该是这个原因。暂停后保存OK 了
