### ISSUE TITLE
增加代理认证模块

### ISSUE THREAD

**Issue by ktownag** [elecV2/elecV2P#3]
请问怎样增加代理认证模块？
这里有说明：https://github.com/alibaba/anyproxy/pull/137
请问该怎样操作

**Comment by elecV2** [comment]
> 请问怎样增加代理认证模块？
> 这里有说明：[alibaba/anyproxy#137](https://github.com/alibaba/anyproxy/pull/137)
> 请问该怎样操作

这不属于本工具的使用范畴，如有需要，请自行研究。
