### ISSUE TITLE
能否在TASK界面增加一个远程自动更新JS到本地的功能？

### ISSUE THREAD

**Issue by Mark-1215** [elecV2/elecV2P#30]
能否在TASK界面增加一个远程自动更新JS到本地的功能？
如题可以根据时间表达式来定义什么时候更新，或者在运行前更新。

**Comment by q123458384** [comment]
> 能否在TASK界面增加一个远程自动更新JS到本地的功能？
> 如题可以根据时间表达式来定义什么时候更新，或者在运行前更新。

定时任务加一个curl命令或者wget撒？

**Comment by elecV2** [comment]
远程 JS 已经可以实现自动更新。
如果你非要在某个时间定时更新的话，可以写一个简单的 JS：

`
$download(url, { folder: 'script/JSFile' })
`

然后设置一个定时任务运行就好了。

**Comment by Mark-1215** [comment]
感谢感谢。
