### ISSUE TITLE
能否在空闲之余增加一个企业微信推送接口？

### ISSUE THREAD

**Issue by shengmean** [elecV2/elecV2P#31]
感谢大佬辛苦付出，软件很好用，但是因为手机是安卓的，没有bark，sever酱常常没有响应，自从换了企业微信以来，非常稳定且样式好看，请大佬空闲之余，增加企业微信通知接口。

**Comment by elecV2** [comment]
不会添加这个。

学一下用 IFTTT 或者自行学习修改脚本去实现这个功能。

> 感谢大佬辛苦付出，软件很好用，但是因为手机是安卓的，没有bark，sever酱常常没有响应，自从换了企业微信以来，非常稳定且样式好看，请大佬空闲之余，增加企业微信通知接口。

**Comment by Mark-1215** [comment]
我也强烈建议大佬能增加一个企业微信推送功能(非企业微信机器人)，现在的确很好用，优点是可以分类信息，服务稳定，不需要点进内页，Sever酱常常没有响应经常出现故障，而且还没有长消息功能，都需要点进去才可以看到完整的内容，bark支持长消息直接查看，但是限制长度了，且没有安卓版本。
官方API https://work.weixin.qq.com/api/doc/90000/90135/90236
LXK大佬的 文件写法 https://github.com/LXK9301/jd_scripts/blob/master/sendNotify.js  详见 460-545行。

**Comment by elecV2** [comment]
@shengmean @Mark-1215 

3.0.9 版本已添加自定义通知，自行根据 API 说明文档和例程进行设置。
