### ISSUE TITLE
新版本更新后 shell 环境搭建不了 错误日志如下

### ISSUE THREAD

**Issue by githooo** [elecV2/elecV2P#32]
[new1-...js error][2021-01-24 10:52:14.200] ERROR: Failed to open apk database: temporary error (try again later)
[new1-...js error][2021-01-24 10:52:14.196] ERROR: Unable to lock database: Resource temporarily unavailable

我谷歌了下是 dockfile中用户权限问题，望解决，而且我从dockerhub里也没看到上个版本，拉取了更早之前的老版本是没问题的。

**Comment by elecV2** [comment]
Dockerfile 已经很多个版本没有改动了，不大可能是这个问题。

如果能正常启动，尝试手动进入 docker 内部修改一下权限。

如果是 ARM 平台，这个用户权限问题暂时还没想好怎么改。

> [new1-...js error][2021-01-24 10:52:14.200] ERROR: Failed to open apk database: temporary error (try again later)
> [new1-...js error][2021-01-24 10:52:14.196] ERROR: Unable to lock database: Resource temporarily unavailable
> 
> 我谷歌了下是 dockfile中用户权限问题，望解决，而且我从dockerhub里也没看到上个版本，拉取了更早之前的老版本是没问题的。

**Comment by xlight** [comment]
给你个思路
`docker -exec <container> rm /lib/apk/db/lock `
