### ISSUE TITLE
能否考虑容器内部自动同步github代码

### ISSUE THREAD

**Issue by vay1314** [elecV2/elecV2P#34]
非常感谢作者开发的工具
现在有这个小问题，比如现在容器安装的py环境和依赖库，下次更新镜像，更新容器后py环境和依赖是不是就会没有。那能不能请容器内改成自动同步github的代码。

**Comment by elecV2** [comment]
同步哪个 github 代码？

关于更新镜像自动添加环境依赖的问题，在 webUI SETTING 界面添加初始化运行脚本就好了，你也可以自己再写一个下载文件的脚本，然后初始化运行。

> 非常感谢作者开发的工具
> 现在有这个小问题，比如现在容器安装的py环境和依赖库，下次更新镜像，更新容器后py环境和依赖是不是就会没有。那能不能请容器内改成自动同步github的代码。

**Comment by vay1314** [comment]
> 关于更新自动添加环境依赖的问题，在webUI设置界面添加初始化运行脚本就好了，你也可以自己再写一个下载文件的脚本，然后初始化运行。
> […](#)
> 非常感谢作者开发的工具 现在有这个小问题，比如现在容器安装的py环境和依赖库，下次更新镜像，更新容器后py环境和依赖是不是就会没有。那能不能请容器内改成自动同步github的代码。

同步elecV2P的github代码，docker镜像每次更新不是更改这些代码吗？我首次运行py环境安装时，安装了很久，如果初始化脚本添加py环境安装，更新容器后task运行py程序，也会失败吧。

**Comment by elecV2** [comment]
你要的功能可以自己写一个脚本实现，或者进入容器手动同步。
并不是有新的版本就要更新。
初始化安装就是用于更新容器后添加一些运行环境，既然安装了，为什么会运行失败？
先尝试多用一用吧。

> 关于更新自动添加环境依赖的问题，在webUI设置界面添加初始化运行脚本就好了，你也可以自己再写一个下载文件的脚本，然后初始化运行。
> …
> 非常感谢作者开发的工具 现在有这个小问题，比如现在容器安装的py环境和依赖库，下次更新镜像，更新容器后py环境和依赖是不是就会没有。那能不能请容器内改成自动同步github的代码。
> 
> 同步elecV2P的github代码，docker镜像每次更新不是更改这些代码吗？我首次运行py环境安装时，安装了很久，如果初始化脚本添加py环境安装，更新容器后task运行py程序，也会失败吧。
