### ISSUE TITLE
浏览器误访问anyproxy代理端口导致几秒内出现数万个访问，内存占用激增nas服务器卡死崩溃

### ISSUE THREAD

**Issue by zhengfan2014** [elecV2/elecV2P#35]
如题，使用docker安装
 80 -> 7080
 8001 -> 7081 
 8002 -> 7082 
在浏览器访问nas的ip:7081时，7082的anyproxy观测到了数万的nas的ip:7081 的访问请求
[![yJ7FiT.md.png](https://s3.ax1x.com/2021/02/06/yJ7FiT.md.png)](https://imgchr.com/i/yJ7FiT)
内存从75%瞬间上涨到85%，占用内存从几十M翻了10倍多到400多M，nas卡死
[![yJ7kJU.md.png](https://s3.ax1x.com/2021/02/06/yJ7kJU.md.png)](https://imgchr.com/i/yJ7kJU)
希望能在设置增加 屏蔽浏览器对代理端口的get请求，或者增加代理端口的get请求限制频率。

**Comment by elecV2** [comment]
这个要求目前做不到。

出现这种情况应该是你的代理设置有问题，代理发出的请求又回到了代理端口，造成循环网络请求，修改一下相关代理设置吧。

> 如题，使用docker安装
> 80 -> 7080
> 8001 -> 7081
> 8002 -> 7082
> 在浏览器访问nas的ip:7081时，7082的anyproxy观测到了数万的nas的ip:7081 的访问请求
> 
> 内存从75%瞬间上涨到85%，占用内存从几十M翻了10倍多到400多M，nas卡死
> 
> 希望能在设置增加 屏蔽浏览器对代理端口的get请求，或者增加代理端口的get请求限制频率。

**Comment by zhengfan2014** [comment]
> 这个要求目前做不到。 出现这种情况应该是你的代理设置有问题，代理发出的请求又回到了代理端口，造成循环网络请求，修改一下相关代理设置吧。
> […](#)
> 如题，使用docker安装 80 -> 7080 8001 -> 7081 8002 -> 7082 在浏览器访问nas的ip:7081时，7082的anyproxy观测到了数万的nas的ip:7081 的访问请求 内存从75%瞬间上涨到85%，占用内存从几十M翻了10倍多到400多M，nas卡死 希望能在设置增加 屏蔽浏览器对代理端口的get请求，或者增加代理端口的get请求限制频率。

那应该如何正确设置以避免循环网络请求？😂

**Comment by elecV2** [comment]
谷歌。

（把你原来的设置随便改一个就好了。）
