### ISSUE TITLE
关于添加一个REPL环境，实时执行和回显

### ISSUE THREAD

**Issue by kylinpoet** [elecV2/elecV2P#37]
你好，感谢你提供的优秀项目，请问下能添加一个REPL环境吗？

**Comment by elecV2** [comment]
执行什么？JS 有回显，其他命令，看一下 说明文档  [Advanced - 高级篇（开启 minishell 等）](https://github.com/elecV2/elecV2P-dei/tree/master/docs/Advanced.md)

**Comment by kylinpoet** [comment]
额。。就是这个，没好好看文档。谢谢。
