### ISSUE TITLE
isnode无法判断环境

### ISSUE THREAD

**Issue by 1217079729** [elecV2/elecV2P#38]
![image](https://user-images.githubusercontent.com/7964969/108294543-00c5d200-71d1-11eb-8e72-15c8a837373a.png)

很多脚本都是用isNode判断环境的，发现$.isNode()无法正确判断环境 导致脚本不能正常使用，望修复。。

**Comment by elecV2** [comment]
这本来就不是 node 环境啊？直接运行脚本默认判断是使用 surge/quanx 或 elecV2P 的环境。如果要用 node 环境跑就使用shell 指令：node xxxx.js 

> 
> 很多脚本都是用isNode判断环境的，发现$.isNode()无法正确判断环境 导致脚本不能正常使用，望修复。。
