### ISSUE TITLE
windows server2012下v2p自动结束进程

### ISSUE THREAD

**Issue by DYS0327** [elecV2/elecV2P#39]
windows server2012 r2安装node14运行v2p，在运行cron定时任务时，启动定时任务，脚本正常执行，但是关闭定时任务后，大概一分钟左右，v2p会自动结束进程，还要用node重新运行v2p

**Comment by DYS0327** [comment]
我是用cmd运行的，在手动开启关闭一下定时任务后，cmd窗口会自动关闭，但是手动开启倒计时任务并不会出现这个问题。

**Comment by DYS0327** [comment]
![image](https://user-images.githubusercontent.com/55141555/108597972-c1f96d00-73c6-11eb-8787-1a0d78531059.png)
服务器是2h4g的，测试过程中任务管理器一直开启，排除了服务器卡死导致v2p关闭，现在找不到问题所在

**Comment by elecV2** [comment]
看一下日志文件有什么提示没。errors.log 和 elecV2Proc.log

> 我是用cmd运行的，在手动开启关闭一下定时任务后，cmd窗口会自动关闭，但是手动开启倒计时任务并不会出现这个问题。

**Comment by DYS0327** [comment]
> 看一下日志文件有什么提示没。errors.log和elecV2Proc.log
> […](#)
> 我是用cmd运行的，在手动开启关闭一下定时任务后，cmd窗口会自动关闭，但是手动开启倒计时任务并不会出现这个问题。
elecV2Proc.log里面是空的，errors.log里面的日志没有这个时间段的记录，最晚的一条日志是在21点15，这个问题大概是在21点40出现的
![image](https://user-images.githubusercontent.com/55141555/108598579-62509100-73c9-11eb-8b74-a27253c88587.png)

**Comment by DYS0327** [comment]
> 看一下日志文件有什么提示没。errors.log和elecV2Proc.log
> […](#)
> 我是用cmd运行的，在手动开启关闭一下定时任务后，cmd窗口会自动关闭，但是手动开启倒计时任务并不会出现这个问题。

而且在闪退前，cmd窗口没有任何异常输出，窗口直接关闭了

**Comment by elecV2** [comment]
这个描述没办法确定问题，我也没有同样设备去进行测试。

看日志你执行了 softupdate 这个脚本，这个脚本在最后会重启一次服务或服务器（还是信息太少，没办法确定是否是这个问题）

如果复现这个问题，欢迎提供更多的相关信息。

> 而且在闪退前，cmd窗口没有任何异常输出，窗口直接关闭了
