### ISSUE TITLE
 Error response from daemon: driver failed programming external connectivity on endpoint elecv2p (24a5538fa827fe6e83605f0580c8942c1e33e3ca5386408cd5bbfc8f753587f6): Error starting userland proxy: listen tcp 0.0.0.0:80: bind: address already in use.

### ISSUE THREAD

**Issue by minv5** [elecV2/elecV2P#4]
这种错误改怎么解决呢？

**Comment by elecV2** [comment]
80端口已占用。
1. 关掉占用端口的应用。
2. 换一个端口。说明文档应该有写步骤
> 这种错误改怎么解决呢？

**Comment by minv5** [comment]
不知道作者有没有tg的群？

**Comment by minv5** [comment]
> 80端口已占用。 1. 关掉占用端口的应用。 2. 换一个端口。说明文档应该有写步骤
> […](#)
> 这种错误改怎么解决呢？

**Comment by elecV2** [comment]
﻿无。暂时没计划
> 不知道作者有没有tg的群？

**Comment by minv5** [comment]
> ﻿无。暂时没计划
> […](#)
> 不知道作者有没有tg的群？

这个n1是否可用，空间够吗？

**Comment by elecV2** [comment]
﻿没测试过。
40/50 个定时任务，常驻内存130M左右。空载30M。(仅供参考，不同系统和nodejs 版本可能有所不同)

> ﻿无。暂时没计划
> …
> 不知道作者有没有tg的群？
> 
> 这个n1是否可用，空间够吗？

**Comment by minv5** [comment]
> 80端口已占用。 1. 关掉占用端口的应用。 2. 换一个端口。说明文档应该有写步骤
> […](#)
> 这种错误改怎么解决呢？

没找到这个修改端口的命令，是这个端口自己随便设置都可以吗？

**Comment by elecV2** [comment]
那你直接改 config.js 中的代码吧，里面有注释，改完后再启动。

只要能访问，任一端口都可以。
﻿
> 80端口已占用。 1. 关掉占用端口的应用。 2. 换一个端口。说明文档应该有写步骤
> …
> 这种错误改怎么解决呢？
> 
> 没找到这个修改端口的命令，是这个端口自己随便设置都可以吗？

**Comment by minv5** [comment]
> 那你直接改 config.js 中的代码吧，里面有注释，改完后再启动。 只要能访问，任一端口都可以。 ﻿
> […](#)
> 80端口已占用。 1. 关掉占用端口的应用。 2. 换一个端口。说明文档应该有写步骤 … 这种错误改怎么解决呢？ 没找到这个修改端口的命令，是这个端口自己随便设置都可以吗？

纯小白，不懂，是要fork到自己的库里面修改吗？

**Comment by elecV2** [comment]
你是docker运行还是 nodejs? 
docker 的话直接改80对应的映射端口就好了。 80:80 改为 8010:80 (8010 也可以改其他任意端口)。

nodejs 的话，windows 用文本编辑器。
linux，花三五分钟学一下 nano 的文本编辑指令。关键字：linux nano 编辑


> 那你直接改 config.js 中的代码吧，里面有注释，改完后再启动。 只要能访问，任一端口都可以。 ﻿
> …
> 80端口已占用。 1. 关掉占用端口的应用。 2. 换一个端口。说明文档应该有写步骤 … 这种错误改怎么解决呢？ 没找到这个修改端口的命令，是这个端口自己随便设置都可以吗？
> 
> 纯小白，不懂，是要fork到自己的库里面修改吗？

**Comment by minv5** [comment]
docker: Error response from daemon: driver failed programming external connectivity on endpoint elecv2p (bcb5a974e610026ca802c99f3223ae80f06d8762303a885fc73072fdf1cb5fbd): Error starting userland proxy: listen tcp 0.0.0.0:81: bind: address already in use.
我直接改81也是说的占用

**Comment by minv5** [comment]
我是在n1上的op里面的docker里面弄得

**Comment by minv5** [comment]
docker run --restart=always -d --name elecv2p -p 81:80 -p 8001:8001 -p 8002:8002 elecv2/elecv2p
我改成了这样

**Comment by elecV2** [comment]
这些属于常用端口，如果你机器有其他服务的话，基本都占用的。占用了你就换下一个嘛。12521 1333 996 2345 886 ……, 总有能用的。
另外可以搜一下指令，查看是一下哪些应用占用的哪些端口。

> docker run --restart=always -d --name elecv2p -p 81:80 -p 8001:8001 -p 8002:8002 elecv2/elecv2p
> 我改成了这样

**Comment by minv5** [comment]
root@OpenWrt:~# netstat -nlp |grep docker-proxy|awk '{print $4}'|sort
:::9999
root@OpenWrt:~# docker ps
CONTAINER ID        IMAGE                        COMMAND             CREATED             STATUS              PORTS                    NAMES
0d1bdfeefafd        portainer/portainer:latest   "/portainer"        10 days ago         Up 3 hours          0.0.0.0:9999->9000/tcp   strange_noether

查了一下这80的端口没有被占用过啊

**Comment by elecV2** [comment]
你直接用 netstat -nlp  看所有的。

N1 上的，80是肯定被占用的。不然也不会提示你占用了。机器比你和我更懂它自己，看到显示的错误，跟着改就行了。

> root@OpenWrt:# netstat -nlp |grep docker-proxy|awk '{print $4}'|sort
> :::9999
> root@OpenWrt:# docker ps
> CONTAINER ID IMAGE COMMAND CREATED STATUS PORTS NAMES
> 0d1bdfeefafd portainer/portainer:latest "/portainer" 10 days ago Up 3 hours 0.0.0.0:9999->9000/tcp strange_noether
> 
> 查了一下这80的端口没有被占用过啊

**Comment by minv5** [comment]
> 你直接用 netstat -nlp 看所有的。 N1 上的，80是肯定被占用的。不然也不会提示你占用了。机器比你和我更懂它自己，看到显示的错误，跟着改就行了。
> […](#)
> root@OpenWrt:# netstat -nlp |grep docker-proxy|awk '{print $4}'|sort :::9999 root@OpenWrt:# docker ps CONTAINER ID IMAGE COMMAND CREATED STATUS PORTS NAMES 0d1bdfeefafd portainer/portainer:latest "/portainer" 10 days ago Up 3 hours 0.0.0.0:9999->9000/tcp strange_noether 查了一下这80的端口没有被占用过啊

嗯嗯，我修改好了，也下载完成，但是怎么进入呢？

**Comment by elecV2** [comment]
看你装了个portainer，你怎么进 portainer，怎么进这个，端口改为你设置的80对应端口就好了。

浏览器里输入 N1 IP地址:8010(80对应端口)，应该就可以打开主页了。

之后，就按里面的教程操作。
﻿
> 你直接用 netstat -nlp 看所有的。 N1 上的，80是肯定被占用的。不然也不会提示你占用了。机器比你和我更懂它自己，看到显示的错误，跟着改就行了。
> …
> root@OpenWrt:# netstat -nlp |grep docker-proxy|awk '{print $4}'|sort :::9999 root@OpenWrt:# docker ps CONTAINER ID IMAGE COMMAND CREATED STATUS PORTS NAMES 0d1bdfeefafd portainer/portainer:latest "/portainer" 10 days ago Up 3 hours 0.0.0.0:9999->9000/tcp strange_noether 查了一下这80的端口没有被占用过啊
> 
> 嗯嗯，我修改好了，也下载完成，但是怎么进入呢？

**Comment by minv5** [comment]
我的端口改成了625，打开以后是空白页面

**Comment by elecV2** [comment]
你TG 私聊我吧，elecv8 。我先出去一下，可能晚点回你。

> 我的端口改成了625，打开以后是空白页面
