### ISSUE TITLE
通过token访问的方式点击日志界面不会自动带入token访问

### ISSUE THREAD

**Issue by Oscar1011** [elecV2/elecV2P#40]
其他会打开新页面的交互方式似乎都会这样。

**Comment by Oscar1011** [comment]
导致的结果就是无法访问其他页面。使用上来说很麻烦。。

**Comment by elecV2** [comment]
新页面应该就 logs 和 efss 吧？手动添加一下吧（之后版本会修复）

> 其他会打开新页面的交互方式似乎都会这样。

**Comment by Oscar1011** [comment]
好的，等大佬更新
