### ISSUE TITLE
是否考虑在控制台增加npm 依赖库的配置用于自动安装依赖

### ISSUE THREAD

**Issue by Oscar1011** [elecV2/elecV2P#41]
可以更方便添加其他有依赖的脚本。
虽然现在也能通过组合操作的方式实现。
但是编辑的话得去文件里修改才可以，也不好控制安装操作。

**Comment by elecV2** [comment]
不是很明白这个需求。

要使用 npm install 或 yarn add 命令的话，可以设置一个倒计时任务 0 shell 指令 npm/yarn xxx 。

也可以写一个简单的脚本：

$exec('npm install xxx')

测试运行，或者保存后添加到初始化运行脚本（重启后自动运行）

> 可以更方便添加其他有依赖的脚本。
> 虽然现在也能通过组合操作的方式实现。
> 但是编辑的话得去文件里修改才可以，也不好控制安装操作。

**Comment by Oscar1011** [comment]
脚本用的多了，需要的依赖肯定也会增加。放在一条命令里不太好管理的感觉

**Comment by elecV2** [comment]
暂时就只能这么解决了，之后再看吧。
> 脚本用的多了，需要的依赖肯定也会增加。放在一条命令里不太好管理的感觉

**Comment by q123458384** [comment]
> 暂时就只能这么解决了，之后再看吧。
> […](#)
> 脚本用的多了，需要的依赖肯定也会增加。放在一条命令里不太好管理的感觉

作者您好，能否小的更新通过git的代码更新，像lxk的JD容器一样。
不然每次更新 里面的环境都会掉
