### ISSUE TITLE
可以开源下web管理后台前端代码不呢,我想添加个批量添加任务的功能

### ISSUE THREAD

**Issue by renhaoweixiao** [elecV2/elecV2P#42]
由于拷贝任务繁多,一个一个输入特别慢,,所以我想给web前端页面添加一个按批量导入task的功能,您方便的话可以开源下前端代码不呢

**Comment by elecV2** [comment]
目前没有这个计划。

批量添加参考：https://github.com/elecV2/elecV2P-dei/blob/master/examples/JSTEST/exam-tasksub.js

> 由于拷贝任务繁多,一个一个输入特别慢,,所以我想给web前端页面添加一个按批量导入task的功能,您方便的话可以开源下前端代码不呢

**Comment by renhaoweixiao** [comment]
> 目前没有这个计划。 批量添加参考：https://github.com/elecV2/elecV2P-dei/blob/master/examples/JSTEST/exam-tasksub.js
> […](#)
> 由于拷贝任务繁多,一个一个输入特别慢,,所以我想给web前端页面添加一个按批量导入task的功能,您方便的话可以开源下前端代码不呢

通过远程`hookurl`多次调用`taskadd`即可对不

**Comment by elecV2** [comment]
基本逻辑是那样的。实际使用可能需要根据情况适当调整。
> 通过远程hookurl多次调用taskadd即可对不

**Comment by renhaoweixiao** [comment]
> 基本逻辑是那样的。实际使用可能需要根据情况适当调整。
> […](#)
> 通过远程hookurl多次调用taskadd即可对不

可以了谢谢
