### ISSUE TITLE
加入自定义推送链接重启v2p就启动不了

### ISSUE THREAD

**Issue by enews** [elecV2/elecV2P#45]
日志错误如下:
[elecV2Proc error][2021-02-25 16:58:48.832] Caught exception TypeError: req.url.replaceAll is not a function
    at custPush (D:\V2P\utils\feed.js:161:23)
    at feedPush (D:\V2P\utils\feed.js:228:5)
    at Object.push (D:\V2P\utils\feed.js:235:5)
    at feedAddItem (D:\V2P\utils\feed.js:259:17)
    at Task.start (D:\V2P\func\task.js:26:7)
    at D:\V2P\func\task.js:65:25
    at Object.<anonymous> (D:\V2P\func\task.js:68:2)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)

设置看截图
![1234](https://user-images.githubusercontent.com/9135007/109128933-00a67300-778b-11eb-8747-51d675ac91e9.png)

**Comment by elecV2** [comment]
﻿
看不出什么什么导致的问题，你自己修改过代码吗？

尝试备份下数据，然后拉一下最新的代码吧。
> 日志错误如下:
> [elecV2Proc error][2021-02-25 16:58:48.832] Caught exception TypeError: req.url.replaceAll is not a function
> at custPush (D:\V2P\utils\feed.js:161:23)
> at feedPush (D:\V2P\utils\feed.js:228:5)
> at Object.push (D:\V2P\utils\feed.js:235:5)
> at feedAddItem (D:\V2P\utils\feed.js:259:17)
> at Task.start (D:\V2P\func\task.js:26:7)
> at D:\V2P\func\task.js:65:25
> at Object. (D:\V2P\func\task.js:68:2)
> at Module._compile (internal/modules/cjs/loader.js:999:30)
> at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
> at Module.load (internal/modules/cjs/loader.js:863:32)
> 
> 设置看截图

**Comment by enews** [comment]
> 
> ﻿ 看不出什么什么导致的问题，你自己修改过代码吗？ 尝试备份下数据，然后拉一下最新的代码吧。
> […](#)
> 日志错误如下: [elecV2Proc error][2021-02-25 16:58:48.832] Caught exception TypeError: req.url.replaceAll is not a function at custPush (D:\V2P\utils\feed.js:161:23) at feedPush (D:\V2P\utils\feed.js:228:5) at Object.push (D:\V2P\utils\feed.js:235:5) at feedAddItem (D:\V2P\utils\feed.js:259:17) at Task.start (D:\V2P\func\task.js:26:7) at D:\V2P\func\task.js:65:25 at Object. (D:\V2P\func\task.js:68:2) at Module._compile (internal/modules/cjs/loader.js:999:30) at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10) at Module.load (internal/modules/cjs/loader.js:863:32) 设置看截图

我没修改过代码, 我用了最新的版本的代码也一样,开启自定义推送后还是启动不了, 报错还是一样

**Comment by enews** [comment]
运行环境是win7 nodejs,  推送格式我安装说明改为json也是一样

**Comment by enews** [comment]
修改utils\feed.js中161行至169行, 把replaceAll 替换为replace后成功启动,并且推送也正常

**Comment by elecV2** [comment]
启动不了你怎么改的？

看一下 script/Lists/config.json CONFIG_FEED 那块有没有问题

> 运行环境是win7 nodejs, 推送格式我安装说明改为json也是一样

**Comment by enews** [comment]
另外自动清除日志的js脚本能适配下windows平台么? 我看命令是rm -rf, 我不知道这个在windows nodejs下面是否能正常执行.
还希望加入停止测试脚本的功能,有些测试脚本执行一次2小时, 没找到停止按钮, 只能重启服务.

**Comment by enews** [comment]
另外还有个bug, 比如个脚本执行时间是1-2小时, 根据任务不同,执行时间不一样, 假如第一次还没执行完毕, 第二次时间到了, 这个时候第二次就会开始执行, 这样就会造成脚本重复运行, 容易黑号, 希望能加入判断, 如果第一次没执行完毕, 要么直接关闭, 要么等下次, 如果这里能加入个配置项就更好了

**Comment by elecV2** [comment]
？？？你 node 该升级了。

window 命令 自行谷歌然后替换。

长时间脚本一般作者都会有提醒吧？随时停止的按钮技术上做不到。


时间间隔不应该你自己去判断设置吗？或者自己改脚本设置一个判断存储变量

> 修改utils\feed.js中161行至169行, 把replaceAll 替换为replace后成功启动,并且推送也正常

**Comment by enews** [comment]
> 
> ？？？你 node 该升级了。 window 命令 自行谷歌然后替换。 长时间脚本一般作者都会有提醒吧？随时停止的按钮技术上做不到。 时间间隔不应该你自己去判断设置吗？或者自己改脚本设置一个判断存储变量
> […](#)
> 修改utils\feed.js中161行至169行, 把replaceAll 替换为replace后成功启动,并且推送也正常

win7 能支持的nodejs 版本最高是多少? 我装的是12.20.2, 好像没看到支持的更高版本了.

好吧, nodejs 下面的限制还真多, 这些在桌面程序上都不存在, 只不过boxjs支持不方便
