### ISSUE TITLE
// @grant silent ; 屏蔽脚本通知和输出无效

### ISSUE THREAD

**Issue by enews** [elecV2/elecV2P#47]
有个挂机脚本, 会每隔几秒输出日志, 我在js文件开头加入// @grant silent ;一样会提示

![222](https://user-images.githubusercontent.com/9135007/109441486-4e172e80-7a70-11eb-81c2-ce12bf0aaa58.png)
![333](https://user-images.githubusercontent.com/9135007/109441483-4c4d6b00-7a70-11eb-8a21-89ca040c86d0.png)

**Comment by elecV2** [comment]
silent 好像只屏蔽了通知（待修复）

如果只是屏蔽日志的话，试一下用 quiet

// @grant  quiet

> 有个挂机脚本, 会每隔几秒输出日志, 我在js文件开头加入// @grant silent ;一样会提示
> 
>

**Comment by enews** [comment]
> 
> silent 好像只屏蔽了通知（待修复） 如果只是屏蔽日志的话，试一下用 quiet // @grant quiet
> […](#)
> 有个挂机脚本, 会每隔几秒输出日志, 我在js文件开头加入// @grant silent ;一样会提示

quiet 我刚才试了, 是没输出了, 但是我看日志收到一个脚本finished的输出, 不知道是脚本结束了还是其他的

**Comment by enews** [comment]
只有晚点看了, 挂机脚本短时间看不出来.
另外日志也没有了, 能不能不输出, 但是文件日志里面有

**Comment by enews** [comment]
刚才看了挂机脚本, 没结束, 正常运行, 就是没日志输出
