### ISSUE TITLE
提一个小问题

### ISSUE THREAD

**Issue by lmh77** [elecV2/elecV2P#48]
从订阅链接中添加任务时，使用替换功能，点击添加替换后，UI界面运行状态会变成停止，但实际还在运行，刷新后显示正在运行状态

**Comment by lmh77** [comment]
再加个建议就是，logs界面做成efss那样列表形式更容易查看日志

**Comment by elecV2** [comment]
﻿这个问题晚点回去看一下。

logs 那个暂时不会改。要那么看的话，可以直接把 efss 目录设置为 ./logs
> 从订阅链接中添加任务时，使用替换功能，点击添加替换后，UI界面运行状态会变成停止，但实际还在运行，刷新后显示正在运行状态

**Comment by lmh77** [comment]
OK这方法不错，居然没想到
