### ISSUE TITLE
大佬 可以给Task 任务添加两个功能按钮吗

### ISSUE THREAD

**Issue by KodoShinichi** [elecV2/elecV2P#49]
大佬 可以给Task 任务添加两个功能按钮吗：一个全部停止任务按钮， 一个全部删除任务按钮。      只是建议 如果不好实现就算了。

**Comment by elecV2** [comment]
算了
> 大佬 可以给Task 任务添加两个功能按钮吗：一个全部停止任务按钮， 一个全部删除任务按钮。 只是建议 如果不好实现就算了。

**Comment by EvanDbg** [comment]
可以删除task.list 然后重启v2p
