### ISSUE TITLE
红牛请教评论区各位大佬 ，portainer里面 能看到容器也是运行中的 但就是连接不上端口 

### ISSUE THREAD

**Issue by 546220777** [elecV2/elecV2P#51]
我是N1盒子openwrt里面搞的  但就是访问不了付费求大佬指点

**Comment by zikywang** [comment]
你试试HTTP 而不是https

**Comment by 546220777** [comment]
> 你试试HTTP 而不是https

就是http啊 我是按照那个推荐的命令直接搞的  不知道搞对没

**Comment by rokun7** [comment]
同问，n1的openwrt里面，安装了，容器也运行了，就是访问不了控制面板

**Comment by 546220777** [comment]
> 同问，n1的openwrt里面，安装了，容器也运行了，就是访问不了控制面板
我这个解决了  你试下直接用这条命令
docker run --restart=always -d --name elecv2p -e TZ=Asia/Shanghai -p 8100:80 -p 8101:8001 -p 8102:8002 -v /elecv2p/JSFile:/usr/local/app/script/JSFile -v /elecv2p/Store:/usr/local/app/script/Store -v /elecv2p/Lists:/usr/local/app/script/Lists elecv2/elecv2p:arm64

**Comment by rokun7** [comment]
楼上正解，谢谢
