### ISSUE TITLE
限制可访问此后台管理页面的 IP打开后日志不能查看

### ISSUE THREAD

**Issue by Mark-1215** [elecV2/elecV2P#52]
限制可访问此后台管理页面的 IP打开后日志不能查看，
我使用http://xxxxxxxx/?token=xxxxxx可以正常访问V2P，但是日志页面不行，望修复下。

**Comment by elecV2** [comment]
访问日志界面的时候也加上 token, /logs?token=xxxx
> 限制可访问此后台管理页面的 IP打开后日志不能查看，
> 我使用http://xxxxxxxx/?token=xxxxxx可以正常访问V2P，但是日志页面不行，望修复下。

**Comment by Mark-1215** [comment]
日志列表页面可以看，日志详情看不了。
http://xxxxxx/logs/xxxxx.js.log?token=xxxxx 这样可以看指定日志，建议加个判断，增加上token

**Comment by elecV2** [comment]
﻿从 /logs?token=xxx 的界面点进去都可以直接查看。（之后的版本应该会优化一下
> 日志列表页面可以看，日志详情看不了。
> http://xxxxxx/logs/xxxxx.js.log?token=xxxxx 这样可以看指定日志，建议加个判断，增加上token

**Comment by Mark-1215** [comment]
从http://xxxx/?token=xxxxxx#overview直接进入http://xxxxx/logs没自动附带token。
不是大问题，后面有空优化一下吧~
