### ISSUE TITLE
求大佬出个用boxjs跑脚本的教程

### ISSUE THREAD

**Issue by aaxx255** [elecV2/elecV2P#53]
好像都在跟圈X和S什么什么的。研究了下，实在是没弄明白。
教程记得加二维码！😂

**Comment by rokun7** [comment]
手机没有圈x，这个可以通过抓包获取cookie吗，有教程吗，谢谢

**Comment by daomengRen** [comment]
> 手机没有圈x，这个可以通过抓包获取cookie吗，有教程吗，谢谢

同求
