### ISSUE TITLE
更新后，无法解析jdsharedresourcescdn.azureedge.net

### ISSUE THREAD

**Issue by jinshuqishi2019** [elecV2/elecV2P#54]
宿主机能够下载https://jdsharedresourcescdn.azureedge.net/jdresource/jd_xtg.js
但是v2p里面不能下载，进入容器，无法解析jdsharedresourcescdn.azureedge.net，应该是dns解析出现问题，将resolv.conf里面注释nameserver 127.0.0.11后，添加8.8.8.8，能够解析和下载，希望解决这个网络问题。

**Comment by elecV2** [comment]
这不关更新什么事吧？nameserver 这部分从来就没动过。
网络相关问题检查一下自己的设置吧
> 宿主机能够下载https://jdsharedresourcescdn.azureedge.net/jdresource/jd_xtg.js
> 但是v2p里面不能下载，进入容器，无法解析jdsharedresourcescdn.azureedge.net，应该是dns解析出现问题，将resolv.conf里面注释nameserver 127.0.0.11后，添加8.8.8.8，能够解析和下载，希望解决这个网络问题。

**Comment by jinshuqishi2019** [comment]
我修改了宿主机的resolv.conf，daemon.json，在yaml添加了dns，也是不能改变镜像里面的DNS，也不知道进一步的做法，只能临时性修改容器的resolv.conf。

**Comment by elecV2** [comment]
﻿根据你自己的使用环境搜索一下解决方案，实在不行直接把 resolve 这个文件做一个存储映射
> 我修改了宿主机的resolv.conf，daemon.json，在yaml添加了dns，也是不能改变镜像里面的DNS，也不知道进一步的做法，只能临时性修改容器的resolv.conf。
