### ISSUE TITLE
请问面板有密码访问的设置方法吗？

### ISSUE THREAD

**Issue by sngxpro** [elecV2/elecV2P#55]
想要实现密码登陆才能访问，
否则ip暴露后就比较危险了。
谢谢。

**Comment by elecV2** [comment]
﻿不会添加这个。可以屏蔽所有 IP, 然后自己通过 token 访问

(网络部署，风险自负
> 想要实现密码登陆才能访问，
> 否则ip暴露后就比较危险了。
> 谢谢。

**Comment by sngxpro** [comment]
收到，感谢答复

**Comment by tanmx** [comment]
@sngxpro 使用nginx反代，nginx可以添加密码

**Comment by sngxpro** [comment]
已得到回复
