### ISSUE TITLE
elecV2P 软更新失败 timeout of 5000ms exceeded

### ISSUE THREAD

**Issue by RockZhou8** [elecV2/elecV2P#57]
[softup...js info][2021-04-09 21:28:30.855] 开始获取最新版本号...
[softup...js info][2021-04-09 21:28:31.459] 当前版本: 3.2.8 最新版本: 3.2.9
[softup...js info][2021-04-09 21:28:31.459] 检测到有新的版本: 3.2.9
[softup...js info][2021-04-09 21:28:31.459] 向 webhook 端口发送保存当前任务列表的指令
[softup...js info][2021-04-09 21:28:31.460] 开始获取更新文件列表
[softup...js info][2021-04-09 21:28:31.466] You don't have permission to access.<br>IP: 127.0.0.1 is recorded.<br><br>Powered BY elecV2P: https://github.com/elecV2/elecV2P
[softu...js error][2021-04-09 21:28:36.462] elecV2P 软更新失败 timeout of 5000ms exceeded

**Comment by elecV2** [comment]
网络问题。

更新需要访问 https://api.github.com/ 和 https://raw.githubusercontent.com/ 这两个网址。修改一下系统 hosts 文件或添加代理
> [softup...js info][2021-04-09 21:28:30.855] 开始获取最新版本号...
> [softup...js info][2021-04-09 21:28:31.459] 当前版本: 3.2.8 最新版本: 3.2.9
> [softup...js info][2021-04-09 21:28:31.459] 检测到有新的版本: 3.2.9
> [softup...js info][2021-04-09 21:28:31.459] 向 webhook 端口发送保存当前任务列表的指令
> [softup...js info][2021-04-09 21:28:31.460] 开始获取更新文件列表
> [softup...js info][2021-04-09 21:28:31.466] You don't have permission to access.
> IP: 127.0.0.1 is recorded.
> 
> Powered BY elecV2P: https://github.com/elecV2/elecV2P
> [softu...js error][2021-04-09 21:28:36.462] elecV2P 软更新失败 timeout of 5000ms exceeded
