### ISSUE TITLE
elecv2p 3.23软更新 更新失败 

### ISSUE THREAD

**Issue by imi6** [elecV2/elecV2P#58]
![QQ截图20210409213642](https://user-images.githubusercontent.com/56383294/114188526-d0521700-997b-11eb-8cba-86dde632f257.png)
一直卡住这个地方不动

**Comment by elecV2** [comment]
﻿这算是个 bug, 晚点会修复一下。
暂时的话在 store softupdate_CONFIG 中的noupdate 添加关键字 Docker 再尝试更新一次。
或者直接使用 Docker 更新
> 
> 一直卡住这个地方不动

**Comment by imi6** [comment]
具体在哪个地方添加呢？

**Comment by imi6** [comment]
等修复吧 我先用docker更新了

**Comment by elecV2** [comment]
> 等修复吧 我先用docker更新了

OK。
随便说明一下，bug 已修复（应该）。
先清空/更改 webUI->JSMANAGE->store/cookie 管理 softupdate_CONFIG 中的内容，然后使用最新的 softupdate.js 进行更新
