### ISSUE TITLE
3.29 JS开始推送下载路径问题

### ISSUE THREAD

**Issue by paopaoya** [elecV2/elecV2P#59]
映射路径/mnt/mmcblk2p4/elecV2P/JSFile
映射路径下JS，当前服务器 JS 文件页面可以显示
新下载文件时路径变了
/mnt/mmcblk2p4/elecV2P/JSFile/usr/local/app/script/JSFile
新下载文件路径js，当前服务器 JS 文件页面不显示，且task页面不可用

**Comment by elecV2** [comment]
感谢反馈，确定是个昨晚新加 bug，修复中，晚点再更新一下（10-30分钟）

**Comment by paopaoya** [comment]
感谢大佬
