### ISSUE TITLE
ANYPROXY 端口 web 一访问，CPU就上99%，而且网页一直进不去，转圈圈

### ISSUE THREAD

**Issue by id77** [elecV2/elecV2P#6]
也会导致其他端口也无法使用。

就凌晨拉取最新的Docker elecv2/elecv2p:arm64，今天打开8101端口就出现这种情况。

![image](https://user-images.githubusercontent.com/9592236/100955907-64d1e600-3552-11eb-9796-fb6bd4e3248b.png)
![image](https://user-images.githubusercontent.com/9592236/100956229-fe999300-3552-11eb-9ef1-85680416e22f.png)

**Comment by elecV2** [comment]
ANYPROXY 的代理端口，正常是不能直接通过 web 访问的。
Docker 更新后，如果不是使用自用证书，需要重新下载安装信任新的根证书。

其他问题提供的错误信息太含糊，无法判断原因。

> 也会导致其他端口也无法使用。
> 
> 就凌晨拉取最新的Docker elecv2/elecv2p:arm64，今天打开8101端口就出现这种情况。
> 
>
