### ISSUE TITLE
请问下作者大佬，同个json订阅地址中更新 GitHub的脚本可以更新成功（阿里云）gitee以及国内vps自建的下载链接更新失败提示Network error。

### ISSUE THREAD

**Issue by aouyyy** [elecV2/elecV2P#60]
如题
[以下是测试截图

**Comment by aouyyy** [comment]
![Uploading photo_2021-04-11_00-53-17.jpg…]()

**Comment by aouyyy** [comment]
![photo_2021-04-11_00-53-17](https://user-images.githubusercontent.com/82176807/114278073-8c850d80-9a60-11eb-96d8-ef13875f1013.jpg)
![photo_2021-04-11_00-29-49](https://user-images.githubusercontent.com/82176807/114281757-cd861d80-9a72-11eb-926d-f55eb5cf1ef8.jpg)

**Comment by elecV2** [comment]
gitee 对某些 raw 有访问频率限制，至于国内自建为什么错误，我没办法知道。
像这类问题，都可以自己直接在浏览器中打订阅链接，看一下是什么错误原因。
>

**Comment by aouyyy** [comment]
订阅链接 手机/电脑打开是直接下载 宝塔面板远程下载也是成功的。  嗯  我自己再研究下  谢谢大佬解答。

**Comment by LevineWoo** [comment]
> 订阅链接 手机/电脑打开是直接下载 宝塔面板远程下载也是成功的。 嗯 我自己再研究下 谢谢大佬解答。

我也是这样，自己家的软路由、国内的VPS，对gitee也都是失败的，但github的raw就是成功的。也只有v2p才这样。
