### ISSUE TITLE
关于rules和rewrite的问题。

### ISSUE THREAD

**Issue by LevineWoo** [elecV2/elecV2P#61]
想问个问题。这个rewrite的请求时间是请求前还是返回后？
只是订阅rewrite不生效，但是在rules里添加规则才生效,修改时间也得是网络请求前才行。

**Comment by elecV2** [comment]
后。
（我记得说明文档里有写清楚这个吧）﻿
> 想问个问题。这个rewrite的请求时间是请求前还是返回后？
> 只是订阅rewrite不生效，但是在rules里添加规则才生效,修改时间也得是网络请求前才行。

**Comment by LevineWoo** [comment]
> 后。 （我记得说明文档里有写清楚这个吧）﻿
> […](#)
> 想问个问题。这个rewrite的请求时间是请求前还是返回后？ 只是订阅rewrite不生效，但是在rules里添加规则才生效,修改时间也得是网络请求前才行。

看到了，全是数据返回前，难怪全部不生效，实际应用是要网络请求前这样才能抓包的。
