### ISSUE TITLE
3.29 BUG之后 更新问题

### ISSUE THREAD

**Issue by a2323010404** [elecV2/elecV2P#62]
作者大佬你好， 本人用win10 docker   V2P软更新脚本出错

-
![微信截图_20210412112840](https://user-images.githubusercontent.com/80669127/114337199-46749a80-9b83-11eb-930b-d97f8b7dd132.png)

**Comment by elecV2** [comment]
﻿看日志是网络问题，实在不行就使用 docker 命令升级
> 作者大佬你好， 本人用win10 docker V2P软更新脚本出错
>

**Comment by a2323010404** [comment]
我把镜像删除了 重新下载还是一样的问题    

docker run --restart=always \
  -d --name elecv2p \
  -e TZ=Asia/Shanghai \
  -p 8100:80 -p 8101:8001 -p 8102:8002 \
  -v /elecv2p/JSFile:/usr/local/app/script/JSFile \
  -v /elecv2p/Lists:/usr/local/app/script/Lists \
  -v /elecv2p/Store:/usr/local/app/script/Store \
  -v /elecv2p/Shell:/usr/local/app/script/Shell \
  -v /elecv2p/rootCA:/usr/local/app/rootCA \
  -v /elecv2p/efss:/usr/local/app/efss \
  elecv2/elecv2p

win10 docker 用这个拉取 运行不对么

**Comment by elecV2** [comment]
研究了下，可能是 axios 代理导致的问题。
（是个 bug，下个版本应该会修复）

暂时的解决方案
1. 不用代理 改 hosts 连接 raw.githubxxxxxx
或者 
2. cf 反代 raw.githubxxx 这个域名，然后修改一下 softupdate.js 的 CONFIG

总之，softupdate.js 需要 elecV2P 可以正常访问 raw.githubxxxxx 这个网站

**Comment by a2323010404** [comment]
好的   谢谢大佬  我试了改HOSTS  没效果   
我还是等下个版本更新吧

**Comment by elecV2** [comment]
该问题应该已修复，如果还有此类问题，欢迎重开 issue。
