### ISSUE TITLE
node index.js 运行出错 小白表示不会解决

### ISSUE THREAD

**Issue by yu1chaofan** [elecV2/elecV2P#65]
git clone elecV2P后直接运行node index.js报错
![IMG_20210418_141707](https://user-images.githubusercontent.com/32660987/115136670-e171e680-a053-11eb-9313-a745fdff5e7f.jpg)
出错后我运行了yarn add pack.json后又报错
![IMG_20210418_142908](https://user-images.githubusercontent.com/32660987/115136687-fcdcf180-a053-11eb-8944-e8581f0e68a4.jpg)
大佬我不知道咋解决了

环境是termux里面的ubuntu20.04

**Comment by elecV2** [comment]
升级一下 node 版本。要求 12.0.0 以上。（推荐 14.xx
