### ISSUE TITLE
如何设置消息推送内容过滤，太多“会话切换”了

### ISSUE THREAD

**Issue by spldmanager** [elecV2/elecV2P#66]
每分钟推送一个：
会话切换
a empty message.
没有任何通知内容

webUI->setting里面设置日志等级为error也没用
是需要自己写脚本来过滤吗？如果写了notify.js，那还需要在setting中打开通知吗？

**Comment by elecV2** [comment]
这个会话切换应该是哪个脚本里的通知吧？先找一下脚本里面有没有开关。

通知不是日志。

用了notify.js 的话其他通知都可以关掉。

> ﻿每分钟推送一个：
> 会话切换
> a empty message.
> 没有任何通知内容
> 
> webUI->setting里面设置日志等级为error也没用
> 是需要自己写脚本来过滤吗？如果写了notify.js，那还需要在setting中打开通知吗？

**Comment by spldmanager** [comment]
> 这个会话切换应该是哪个脚本里的通知吧？先找一下脚本里面有没有开关。 通知不是日志。 用了notify.js 的话其他通知都可以关掉。
> […](#)
> ﻿每分钟推送一个： 会话切换 a empty message. 没有任何通知内容 webUI->setting里面设置日志等级为error也没用 是需要自己写脚本来过滤吗？如果写了notify.js，那还需要在setting中打开通知吗？

感谢，找了下是"切换会话"这个脚本在不间断运行，应该是切换用户和COOKIE的，暂时把它停止了
