### ISSUE TITLE
bot设置后，聊天框已提示部署成功，可以交互了，但运行指令会报错error code ：1003

### ISSUE THREAD

**Issue by sngxpro** [elecV2/elecV2P#67]
机器人已经跑起来了，证明应该不是api错误或者网络不通啊，

但是运行指令就会error code：1003，

1.0还是2.0的版本都是报错，

没搞懂是哪里弄错了，

方便时可以指点一下吗

**Comment by elecV2** [comment]
1003 意思是 cf worker 不能通过 IP 直连 elec V2P 服务器，需要域名连接
> 机器人已经跑起来了，证明应该不是api错误或者网络不通啊，
> 
> 但是运行指令就会error code：1003，
> 
> 1.0还是2.0的版本都是报错，
> 
> 没搞懂是哪里弄错了，
> 
> 方便时可以指点一下吗

**Comment by sngxpro** [comment]
非常感谢，这就盘他！爱你！
