### ISSUE TITLE
添加任务时不能保存带参数的命令

### ISSUE THREAD

**Issue by ronghuaxueleng** [elecV2/elecV2P#68]
![微信截图_20210420161014](https://user-images.githubusercontent.com/9460517/115361197-ed47df00-a1f2-11eb-940e-368b0c310e68.png)
如图这要的配置保存后刷新页面，后面的参数就没有了

**Comment by elecV2** [comment]
确实有这个问题（感谢反馈，下个版本修复

（参数实际上应该是生效的
> 
> 如图这要的配置保存后刷新页面，后面的参数就没有了
