### ISSUE TITLE
有概率出现请求 timeout of 5000ms exceeded

### ISSUE THREAD

**Issue by id77** [elecV2/elecV2P#7]
task 会脚本出现
```log
[jd_joy...js info][2020/12/3 08:00:01]: 
🔔宠汪汪积分兑换奖品, 开始!
[jd_joy...js info][2020/12/3 08:00:01]: 
开始【京东账号1】脱衣服

[jd_jo...js error][2020/12/3 08:00:07]: $httpClient {"url":"https://jdjoy.jd.com/gift/getHomeInfo","headers":{"Host":"jdjoy.jd.com","Cookie":"脱敏","reqSource":"h5","Connection":"keep-alive","Accept":"*/*","User-Agent":"jdapp;iPhone;9.2.5;14.2;%E4%BA%AC%E4%B8%9C/9.2.5 CFNetwork/1206 Darwin/20.1.0","Referer":"https://jdjoy.jd.com/pet/index","Accept-Language":"zh-cn","Accept-Encoding":"gzip, deflate, br","Content-Type":"application/x-www-form-urlencoded"}} timeout of 5000ms exceeded
[jd_joy...js info][2020/12/3 08:00:07]: "request config error"
[jd_joy...js info][2020/12/3 08:00:07]: 宠汪汪积分兑换奖品 API请求失败，请检查网路重试
[jd_joy...js info][2020/12/3 08:00:07]: 宠汪汪积分兑换奖品getExchangeRewards异常,undefined
[jd_joy...js info][2020/12/3 08:00:07]: 
开始【京东账号2】脱裤子

[jd_joy...js info][2020/12/3 08:00:10]: 当前积分 20243

[jd_joy...js info][2020/12/3 08:00:10]: 宠物等级 16

[jd_joy...js info][2020/12/3 08:00:10]: 京东昵称 幾米orz

[jd_joy...js info][2020/12/3 08:00:10]: 当前京豆库存:127
[jd_joy...js info][2020/12/3 08:00:10]: saleInfoId:192
[jd_joy...js info][2020/12/3 08:00:10]: 当前账户积分:20243
当前京豆库存:127
满足兑换条件,开始为您兑换京豆

[jd_joy...js info][2020/12/3 08:00:11]: 兑换500成功,【宠物等级】16
【消耗积分】8000个
【剩余积分】12243个

[jd_j...js notify][2020/12/3 08:00:11]: 宠汪汪积分兑换奖品 兑换500京豆成功 【京东账号2】脱裤子
【宠物等级】16
【积分详情】消耗积分 8000, 剩余积分 12243 
[jd_joy...js info][2020/12/3 08:00:11]: 
==============📣系统通知📣==============
宠汪汪积分兑换奖品
兑换500京豆成功
【京东账号2】脱裤子
【宠物等级】16
【积分详情】消耗积分 8000, 剩余积分 12243
[jd_joy...js info][2020/12/3 08:00:11]: 
🔔宠汪汪积分兑换奖品, 结束! 🕛 9.586 秒
```

rules 规则的脚本调用也会出现
```log
[utilsFile  error][2020/12/3 09:53:56]: store key dd_autoCharge no exist.
[utilsFile  error][2020/12/3 09:53:56]: store key dd_notifyTime no exist.
[utilsFile  error][2020/12/3 09:53:56]: store key jx_showLog no exist.
[utilsFile  error][2020/12/3 09:53:56]: store key jx_autoCharge no exist.
[utilsFile  error][2020/12/3 09:53:56]: store key jx_notifyTime no exist.
[boxjs...js error][2020/12/3 09:53:59]: Error: Script execution timed out after 5000ms
    at Script.runInContext (node:vm:143:18)
    at Script.runInNewContext (node:vm:148:17)
    at Object.runInNewContext (node:vm:303:38)
    at runJS (/usr/local/app/script/runJSFile.js:118:23)
    at runJSFile (/usr/local/app/script/runJSFile.js:174:10)
    at requestDetail.requestOptions.headers.User-Agent (/usr/local/app/script/rule.js:231:21)
    at new Promise ()
    at Object.beforeSendRequest (/usr/local/app/script/rule.js:230:14)
    at beforeSendRequest.next ()
    at onFulfilled (/usr/local/app/node_modules/co/index.js:65:19)
[utilsFile  error][2020/12/3 09:39:20]: no list useragent.list
[utilsFile  error][2020/12/3 09:39:22]: no list rewrite.list
[utilsFile  error][2020/12/3 09:39:22]: no list useragent.list
[utilsFeed  error][2020/12/3 09:39:28]: Client network socket disconnected before secure TLS connection was established
[utilsFile  error][2020/12/3 10:17:15]: no list useragent.list
[utilsFile  error][2020/12/3 10:17:18]: no list rewrite.list
[utilsFile  error][2020/12/3 10:17:18]: no list useragent.list
[utilsFile  error][2020/12/3 10:36:41]: no list useragent.list
```

不知道 eAxios 相关设置 的 TIMEOUT: 5000 是否跟这个 5000有关联？
我修改这个5000为其他值（20000）也没用。依旧报 5000ms 错误。

rules 规则的脚本一般不会出现超时的情况吧？

**Comment by elecV2** [comment]
timeout 通常是被请求的网络服务器短时间内处理大量请求，无法正常返回数据。

rules 的脚本执行时间暂时无法更改。

> task 会脚本出现
> 
> [jd_joy...js info][2020/12/3 08:00:01]: 
> 🔔宠汪汪积分兑换奖品, 开始!
> [jd_joy...js info][2020/12/3 08:00:01]: 
> 开始【京东账号1】脱衣服
> 
> [jd_jo...js error][2020/12/3 08:00:07]: $httpClient {"url":"https://jdjoy.jd.com/gift/getHomeInfo","headers":{"Host":"jdjoy.jd.com","Cookie":"脱敏","reqSource":"h5","Connection":"keep-alive","Accept":"*/*","User-Agent":"jdapp;iPhone;9.2.5;14.2;%E4%BA%AC%E4%B8%9C/9.2.5 CFNetwork/1206 Darwin/20.1.0","Referer":"https://jdjoy.jd.com/pet/index","Accept-Language":"zh-cn","Accept-Encoding":"gzip, deflate, br","Content-Type":"application/x-www-form-urlencoded"}} timeout of 5000ms exceeded
> [jd_joy...js info][2020/12/3 08:00:07]: "request config error"
> [jd_joy...js info][2020/12/3 08:00:07]: 宠汪汪积分兑换奖品 API请求失败，请检查网路重试
> [jd_joy...js info][2020/12/3 08:00:07]: 宠汪汪积分兑换奖品getExchangeRewards异常,undefined
> [jd_joy...js info][2020/12/3 08:00:07]: 
> 开始【京东账号2】脱裤子
> 
> [jd_joy...js info][2020/12/3 08:00:10]: 当前积分 20243
> 
> [jd_joy...js info][2020/12/3 08:00:10]: 宠物等级 16
> 
> [jd_joy...js info][2020/12/3 08:00:10]: 京东昵称 幾米orz
> 
> [jd_joy...js info][2020/12/3 08:00:10]: 当前京豆库存:127
> [jd_joy...js info][2020/12/3 08:00:10]: saleInfoId:192
> [jd_joy...js info][2020/12/3 08:00:10]: 当前账户积分:20243
> 当前京豆库存:127
> 满足兑换条件,开始为您兑换京豆
> 
> [jd_joy...js info][2020/12/3 08:00:11]: 兑换500成功,【宠物等级】16
> 【消耗积分】8000个
> 【剩余积分】12243个
> 
> [jd_j...js notify][2020/12/3 08:00:11]: 宠汪汪积分兑换奖品 兑换500京豆成功 【京东账号2】脱裤子
> 【宠物等级】16
> 【积分详情】消耗积分 8000, 剩余积分 12243 
> [jd_joy...js info][2020/12/3 08:00:11]: 
> ==============📣系统通知📣==============
> 宠汪汪积分兑换奖品
> 兑换500京豆成功
> 【京东账号2】脱裤子
> 【宠物等级】16
> 【积分详情】消耗积分 8000, 剩余积分 12243
> [jd_joy...js info][2020/12/3 08:00:11]: 
> 🔔宠汪汪积分兑换奖品, 结束! 🕛 9.586 秒
> rules 规则的脚本调用也会出现
> 
> [utilsFile  error][2020/12/3 09:53:56]: store key dd_autoCharge no exist.
> [utilsFile  error][2020/12/3 09:53:56]: store key dd_notifyTime no exist.
> [utilsFile  error][2020/12/3 09:53:56]: store key jx_showLog no exist.
> [utilsFile  error][2020/12/3 09:53:56]: store key jx_autoCharge no exist.
> [utilsFile  error][2020/12/3 09:53:56]: store key jx_notifyTime no exist.
> [boxjs...js error][2020/12/3 09:53:59]: Error: Script execution timed out after 5000ms
>     at Script.runInContext (node:vm:143:18)
>     at Script.runInNewContext (node:vm:148:17)
>     at Object.runInNewContext (node:vm:303:38)
>     at runJS (/usr/local/app/script/runJSFile.js:118:23)
>     at runJSFile (/usr/local/app/script/runJSFile.js:174:10)
>     at requestDetail.requestOptions.headers.User-Agent (/usr/local/app/script/rule.js:231:21)
>     at new Promise ()
>     at Object.beforeSendRequest (/usr/local/app/script/rule.js:230:14)
>     at beforeSendRequest.next ()
>     at onFulfilled (/usr/local/app/node_modules/co/index.js:65:19)
> [utilsFile  error][2020/12/3 09:39:20]: no list useragent.list
> [utilsFile  error][2020/12/3 09:39:22]: no list rewrite.list
> [utilsFile  error][2020/12/3 09:39:22]: no list useragent.list
> [utilsFeed  error][2020/12/3 09:39:28]: Client network socket disconnected before secure TLS connection was established
> [utilsFile  error][2020/12/3 10:17:15]: no list useragent.list
> [utilsFile  error][2020/12/3 10:17:18]: no list rewrite.list
> [utilsFile  error][2020/12/3 10:17:18]: no list useragent.list
> [utilsFile  error][2020/12/3 10:36:41]: no list useragent.list
> 不知道 eAxios 相关设置 的 TIMEOUT: 5000 是否跟这个 5000有关联？
> 我修改这个5000为其他值（20000）也没用。依旧报 5000ms 错误。
> 
> rules 规则的脚本一般不会出现超时的情况吧？

**Comment by id77** [comment]
> timeout 通常是被请求的网络服务器短时间内处理大量请求，无法正常返回数据。
> 
> rules 的脚本执行时间暂时无法更改。
> 
> > task 会脚本出现
> > 
> > [jd_joy...js info][2020/12/3 08:00:01]: 
> > 🔔宠汪汪积分兑换奖品, 开始!
> > [jd_joy...js info][2020/12/3 08:00:01]: 
> > 开始【京东账号1】脱衣服
> > 
> > [jd_jo...js error][2020/12/3 08:00:07]: $httpClient {"url":"https://jdjoy.jd.com/gift/getHomeInfo","headers":{"Host":"jdjoy.jd.com","Cookie":"脱敏","reqSource":"h5","Connection":"keep-alive","Accept":"*/*","User-Agent":"jdapp;iPhone;9.2.5;14.2;%E4%BA%AC%E4%B8%9C/9.2.5 CFNetwork/1206 Darwin/20.1.0","Referer":"https://jdjoy.jd.com/pet/index","Accept-Language":"zh-cn","Accept-Encoding":"gzip, deflate, br","Content-Type":"application/x-www-form-urlencoded"}} timeout of 5000ms exceeded
> > [jd_joy...js info][2020/12/3 08:00:07]: "request config error"
> > [jd_joy...js info][2020/12/3 08:00:07]: 宠汪汪积分兑换奖品 API请求失败，请检查网路重试
> > [jd_joy...js info][2020/12/3 08:00:07]: 宠汪汪积分兑换奖品getExchangeRewards异常,undefined
> > [jd_joy...js info][2020/12/3 08:00:07]: 
> > 开始【京东账号2】脱裤子
> > 
> > [jd_joy...js info][2020/12/3 08:00:10]: 当前积分 20243
> > 
> > [jd_joy...js info][2020/12/3 08:00:10]: 宠物等级 16
> > 
> > [jd_joy...js info][2020/12/3 08:00:10]: 京东昵称 幾米orz
> > 
> > [jd_joy...js info][2020/12/3 08:00:10]: 当前京豆库存:127
> > [jd_joy...js info][2020/12/3 08:00:10]: saleInfoId:192
> > [jd_joy...js info][2020/12/3 08:00:10]: 当前账户积分:20243
> > 当前京豆库存:127
> > 满足兑换条件,开始为您兑换京豆
> > 
> > [jd_joy...js info][2020/12/3 08:00:11]: 兑换500成功,【宠物等级】16
> > 【消耗积分】8000个
> > 【剩余积分】12243个
> > 
> > [jd_j...js notify][2020/12/3 08:00:11]: 宠汪汪积分兑换奖品 兑换500京豆成功 【京东账号2】脱裤子
> > 【宠物等级】16
> > 【积分详情】消耗积分 8000, 剩余积分 12243 
> > [jd_joy...js info][2020/12/3 08:00:11]: 
> > ==============📣系统通知📣==============
> > 宠汪汪积分兑换奖品
> > 兑换500京豆成功
> > 【京东账号2】脱裤子
> > 【宠物等级】16
> > 【积分详情】消耗积分 8000, 剩余积分 12243
> > [jd_joy...js info][2020/12/3 08:00:11]: 
> > 🔔宠汪汪积分兑换奖品, 结束! 🕛 9.586 秒
> > rules 规则的脚本调用也会出现
> > 
> > [utilsFile  error][2020/12/3 09:53:56]: store key dd_autoCharge no exist.
> > [utilsFile  error][2020/12/3 09:53:56]: store key dd_notifyTime no exist.
> > [utilsFile  error][2020/12/3 09:53:56]: store key jx_showLog no exist.
> > [utilsFile  error][2020/12/3 09:53:56]: store key jx_autoCharge no exist.
> > [utilsFile  error][2020/12/3 09:53:56]: store key jx_notifyTime no exist.
> > [boxjs...js error][2020/12/3 09:53:59]: Error: Script execution timed out after 5000ms
> >     at Script.runInContext (node:vm:143:18)
> >     at Script.runInNewContext (node:vm:148:17)
> >     at Object.runInNewContext (node:vm:303:38)
> >     at runJS (/usr/local/app/script/runJSFile.js:118:23)
> >     at runJSFile (/usr/local/app/script/runJSFile.js:174:10)
> >     at requestDetail.requestOptions.headers.User-Agent (/usr/local/app/script/rule.js:231:21)
> >     at new Promise ()
> >     at Object.beforeSendRequest (/usr/local/app/script/rule.js:230:14)
> >     at beforeSendRequest.next ()
> >     at onFulfilled (/usr/local/app/node_modules/co/index.js:65:19)
> > [utilsFile  error][2020/12/3 09:39:20]: no list useragent.list
> > [utilsFile  error][2020/12/3 09:39:22]: no list rewrite.list
> > [utilsFile  error][2020/12/3 09:39:22]: no list useragent.list
> > [utilsFeed  error][2020/12/3 09:39:28]: Client network socket disconnected before secure TLS connection was established
> > [utilsFile  error][2020/12/3 10:17:15]: no list useragent.list
> > [utilsFile  error][2020/12/3 10:17:18]: no list rewrite.list
> > [utilsFile  error][2020/12/3 10:17:18]: no list useragent.list
> > [utilsFile  error][2020/12/3 10:36:41]: no list useragent.list
> > 不知道 eAxios 相关设置 的 TIMEOUT: 5000 是否跟这个 5000有关联？
> > 我修改这个5000为其他值（20000）也没用。依旧报 5000ms 错误。
> > 
> > rules 规则的脚本一般不会出现超时的情况吧？
> 

怀疑是跟服务器有关，我QX这边也出现一样的问题
![image](https://user-images.githubusercontent.com/9592236/100971385-c190c900-3571-11eb-8af2-d9c3b29376f6.jpeg)
