### ISSUE TITLE
TG Bot 搭建后，正常反馈搭建成功，正常切换和退出各种环境，但是对进一步的命令没有反馈了

### ISSUE THREAD

**Issue by sngxpro** [elecV2/elecV2P#71]
如题，搞不清楚到底原因在哪里

**Comment by sngxpro** [comment]
这些是正常的

![image](https://user-images.githubusercontent.com/69911266/115380225-f3df5200-a204-11eb-87aa-6211320f2b77.png)

这些就没了反应

![image](https://user-images.githubusercontent.com/69911266/115380522-386aed80-a205-11eb-9215-1ec31838a937.png)

**Comment by elecV2** [comment]
直接访问服务器的 webhook，看下能不能正常返回数据
http://elecv2p服务器地址/webhook?token=你的webhook token&type=status

另外，最好附带一下你的 CONFIG_E2VP 内容（关键信息注意替换），不然很难看出哪里有问题

**Comment by sngxpro** [comment]
![image](https://user-images.githubusercontent.com/69911266/115383660-b381d300-a208-11eb-960d-f23430853cb2.png)

直接访问是正常的，顺利返回信息。

我的config内容如下：

`let CONFIG_EV2P = {
  name: 'elecV2P',                           // bot 名称。可省略
  url: "http://v2p.*.后缀:2086/",          // elecV2P 服务器地址
  wbrtoken: 'd0b51e5b-a4aa-4f6f-8869-*********',      // elecV2P 服务器 webhook token
  token: "177611****:AAFC_0bOGtcmk7AMiyE99KiW*********",     // teleram bot token
  slice: -1800,          // 截取日志最后 1800 个字符，以防太长无法传输
  userid: [97438****],            // 只对该列表中的 userid 发出的指令进行回应。默认: 回应所有用户的指令
  shell: {
    timeout: 1000*6,     // shell exec 超时时间，单位: ms
    contexttimeout: 1000*60*5,               // shell 模式自动退出时间，单位: ms
  },
  store: 'elecV2PBot_CONFIG',   // 是否储存当前 CONFIG 设置到 kv 库（下次使用时会自动读取并覆盖上面的设置，即上面的更改无效（方便更新)。建议调试时留空，调试完成后再设置回 'elecV2PBot_CONFIG' ）
  storeforce: true,     // true: 使用当前设置强制覆盖 cf kv 库中的数据，false: kv 库中有配置相关数据则读取，没有则使用当前进行保存
  timeout: 5000,         // runjs 请求超时时间，以防请求时间过长，导致反复请求，bot 被卡死
}`


感谢指导！

**Comment by elecV2** [comment]
看着好像没问题，可能有问题的地方在那个端口。cloudflare 会限制某些端口的访问

来源：
https://support.cloudflare.com/hc/zh-cn/articles/200169156-%E8%AF%86%E5%88%AB%E4%B8%8E-Cloudflare-%E7%9A%84%E4%BB%A3%E7%90%86%E5%85%BC%E5%AE%B9%E7%9A%84%E7%BD%91%E7%BB%9C%E7%AB%AF%E5%8F%A3

尝试一下全域名访问（在主机上套一层 nginx

**Comment by sngxpro** [comment]
@elecV2 好的
