### ISSUE TITLE
树莓派4b 64位系统，使用docker arm64镜像，8100打开页面空白，8102显示正常

### ISSUE THREAD

**Issue by bonbongo** [elecV2/elecV2P#72]
树莓派4b 是树莓派爱好者社区的64位系统，用ip:8100端口访问，网页标签栏有文字显示（elecV2P - customize personal network），但是网页内容一片空白，求解
![image](https://user-images.githubusercontent.com/48424622/115804484-a8e85900-a415-11eb-8c8c-00ccfce80351.png)

**Comment by shangjiazi** [comment]
你的问题解决了吗，我是ipad白屏，其他设备正常

**Comment by elecV2** [comment]
此类问题通常是浏览器或系统版本太低，建议升级一下。
