### ISSUE TITLE
3.3.0版本运行问题

### ISSUE THREAD

**Issue by DoveBoy** [elecV2/elecV2P#73]
安卓上使用termux直接用nodejs方式启动(个人修改了config.js下的webui端口为8080)，之前的版本都是正常使用，最新版3.3.0使用同样方法打开后，127.0.0.1:8080打不开，同时termux中能看到提示websock error deny请求解决办法。
![Screenshot_2021-04-25-13-27-17-06_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/19201447/115982111-1c7f9700-a5cb-11eb-956c-3fdf23bcc0ee.jpg)

**Comment by elecV2** [comment]
3.3.0 后修改了端口启用逻辑，可以修改script/Lists/config.json 里的内容

  "webUI": {
    "port": 8080
  }

**Comment by DoveBoy** [comment]
@elecV2 感谢解答，原来更改了端口启用的逻辑，难怪之前改动的config.js无效了，改了script/Lists/config.json正常了
