### ISSUE TITLE
更新了今天的3.3.3，打开控制页面显示根据相关法律政策,该内容无法显示

### ISSUE THREAD

**Issue by mengdie101** [elecV2/elecV2P#75]
外网内网访问都是这样，之前的版本没事，这是个什么问题啊
[截图](https://raw.githubusercontent.com/mengdie101/JD_scripts/master/backUp/Screenshot_2021-04-28-21-14-44-228_mark.via.jpg)

**Comment by shangjiazi** [comment]
这是你浏览器问题

**Comment by mengdie101** [comment]
> 这是你浏览器问题

可是我换了6个浏览器都不行，电脑手机都是这样
