### ISSUE TITLE
脚本通知有概率丢失

### ISSUE THREAD

**Issue by id77** [elecV2/elecV2P#8]
多账号的脚本，有时候只能收到其中一个账号的通知。查看日志，丢失的账号通知，是正常的。

但是手机没有正确收到推送。

**Comment by elecV2** [comment]
通知方式是 IFTTT?BARK?RSS?

如果是 IFTTT ，可以打开 IFTTT 软件看一下通知记录，是否都正常推送了。
IFTTT 如果没有 message 信息，而只有 title 默认会通知失败。可以在 message 那一栏加一些固定字符，比如通知时间，确保一定有内容触发通知。


> 多账号的脚本，有时候只能收到其中一个账号的通知。查看日志，丢失的账号通知，是正常的。
> 
> 但是手机没有正确收到推送。

**Comment by id77** [comment]
BARK
查看过BARK推送历史，的确没有

**Comment by elecV2** [comment]
看一下 Rss 有没有吧，如果没有就是没有通知，有的话可能是和 BARK 之间的通信有问题，也有可能是 BARK 限制短时间内的通知次数。

> BARK 
> 查看过BARK推送历史，的确没有 
> 
> > 在 2020年12月4日，下午2:47，elecV2 <notifications@github.com> 写道： 
> > 
> > ﻿ 
> > 
> > 通知方式是 IFTTT?BARK?RSS? 
> > 
> > 如果是 IFTTT ，可以打开 IFTTT 软件看一下通知记录，是否都正常推送了。 
> > IFTTT 如果没有 message 信息，而只有 title 默认会通知失败。可以在 message 那一栏加一些固定字符，比如通知时间，确保一定有内容触发通知。 
> > 
> > 
> > > 多账号的脚本，有时候只能收到其中一个账号的通知。查看日志，丢失的账号通知，是正常的。 
> > > 
> > > 但是手机没有正确收到推送。 
> > —

**Comment by id77** [comment]
> ![image](https://user-images.githubusercontent.com/9592236/101145795-3ee13a00-3655-11eb-84d9-51cf1c06e8b9.png)
![image](https://user-images.githubusercontent.com/9592236/101145833-499bcf00-3655-11eb-9269-20b294fc55e1.png)
> 
> 看一下 Rss 有没有吧，如果没有就是没有通知，有的话可能是和 BARK 之间的通信有问题，也有可能是 BARK 限制短时间内的通知次数。
> 
> 
> 
> > BARK 
> 
> > 查看过BARK推送历史，的确没有 
> 
> > 
> 
> > > 在 2020年12月4日，下午2:47，elecV2 <notifications@github.com> 写道： 
> 
> > > 
> 
> > > ﻿ 
> 
> > > 
> 
> > > 通知方式是 IFTTT?BARK?RSS? 
> 
> > > 
> 
> > > 如果是 IFTTT ，可以打开 IFTTT 软件看一下通知记录，是否都正常推送了。 
> 
> > > IFTTT 如果没有 message 信息，而只有 title 默认会通知失败。可以在 message 那一栏加一些固定字符，比如通知时间，确保一定有内容触发通知。 
> 
> > > 
> 
> > > 
> 
> > > > 多账号的脚本，有时候只能收到其中一个账号的通知。查看日志，丢失的账号通知，是正常的。 
> 
> > > > 
> 
> > > > 但是手机没有正确收到推送。 
> 
> > > — 
> 
>

**Comment by id77** [comment]
Feed 只能看到今天早上的记录。
我5点的双账号脚本通知不正常。

**Comment by elecV2** [comment]
直接网页打开 rss 链接，应该可以看到全部记录，默认不清理。

如果不是很影响，就别管了，正常来说是不会丢通知的。
> Feed 只能看到今天早上的记录。
> 我5点的双账号脚本通知不正常。

**Comment by id77** [comment]
> 
> 
> 直接网页打开 rss 链接，应该可以看到全部记录，默认不清理。
> 
> 
> 
> 如果不是很影响，就别管了，正常来说是不会丢通知的。
> 
> > Feed 只能看到今天早上的记录。
> 
> > 我5点的双账号脚本通知不正常。
> 
> 

认真对比了，feed的记录有下午的，只不过时间晚几个点。记录也挺全。

怀疑是Bark这里有问题，我换回IFTTT用一天看看

**Comment by id77** [comment]
你那个 elecv2/elecv2p:arm64 镜像，没添加 tzdata

```yaml
environment:
      - TZ=Asia/Shanghai
```

这个不生效，所以我feed时间不对

**Comment by id77** [comment]
换了IFTTT，还是丢通知

![image](https://user-images.githubusercontent.com/9592236/101232151-c036dc00-36ea-11eb-8642-b5ddb18ee7f2.png)

**Comment by elecV2** [comment]
﻿丢的是哪条？账号2的两条都丢了吗？
看一下 errors.log 有没有相关信息。

如果 rss 里有，而个别通知收不到，除了网络问题，暂时想不到其他原因。

> 换了IFTTT，还是丢通知
>

**Comment by id77** [comment]
> 
> 
> ﻿丢的是哪条？账号2的两条都丢了吗？
> 
> 看一下 errors.log 有没有相关信息。
> 
> 
> 
> 如果 rss 里有，而个别通知收不到，除了网络问题，暂时想不到其他原因。
> 
> 
> 
> > 换了IFTTT，还是丢通知
> 
> > 
> 
> 

萌宠账号1没通知

只看到助力码api请求失败。但是日志都已经有账号1完整的通知信息了的，feed也有账号1的记录。

问题是在于推送这块。

[jd_pet.js  error][2020/12/5 11:01:35]: $httpClient {"url":"http://api.turinglabs.net/api/v1/jd/pet/read/5/"} timeout of 5000ms exceeded
[jd_pet.js   info][2020/12/5 11:01:35]: "request config error"

**Comment by id77** [comment]
你看下，两个推送都开了，还能不一样。

![image](https://user-images.githubusercontent.com/9592236/101238545-ecb71c00-371b-11eb-9393-cf6b9dbc0848.png)
![image](https://user-images.githubusercontent.com/9592236/101238549-f3459380-371b-11eb-98f5-d5165b2c24f3.png)

**Comment by elecV2** [comment]
所有通知都是从 elecV2P 发送一条网络请求到第三方服务器，然后第三方服务器发生通知请求到手机通知中心。
像你漏通知这种情况这边没办法做什么。只能是你觉得哪个脚本可能没执行，或应该有通知，然后去看一下脚本对应日志，确定到底有没有执行，其他没有什么好的解决方法。
﻿

**Comment by id77** [comment]
docker logs elecv2p -f

查看日志，发现有些脚本没有具体log，只有`[runJSFile notify][2020-12-07 00:00:00.002]: run xxxx.js from task`

没有
`[xxxx...js notify][2020-12-07 00:05:42.644]: 日志内容`


已经更新过docker镜像了。我查看了京东签到，双账号一个通知都没发出，bark、ifttt均没有推送，但两账号签到都完成了。

**Comment by elecV2** [comment]
具体有没有log以执行的脚本为准，脚本里执行了 console.log 就有，没有执行就没有。

通知以脚本运行日志里的 [xxxx.js notify] 为准，如果没收到，就是漏了（无法解决）。如果没有[xxxxxx.js notify] 这条日志，说明没有通知。

另外看一下 SETTING 界面的日志级别，如果是 notify，其他 log 不会记录

> docker logs elecv2p -f
> 
> 查看日志，发现有些脚本没有具体log，只有[runJSFile notify][2020-12-07 00:00:00.002]: run xxxx.js from task
> 
> 没有
> [xxxx...js notify][2020-12-07 00:05:42.644]: 日志内容
> 
> 已经更新过docker镜像了。我查看了京东签到，双账号一个通知都没发出，bark、ifttt均没有推送，但两账号签到都完成了。
