### ISSUE TITLE
请问有些脚本并不能正常跑是什么原因呢？

### ISSUE THREAD

**Issue by LevineWoo** [elecV2/elecV2P#80]
比如：抖音极速版
https://raw.githubusercontent.com/ZhiYi-N/Private-Script/master/Scripts/dyjsb.js

ck是从手机上导过来的，qx上能正常跑，v2p就提示抖音极速版
⚠️异常:spam check not pass请重新获取readkey

想知道该如何解决呢？

**Comment by LevineWoo** [comment]
今天测试另一个顺丰的，也是同样的ck，qx能跑，v2p报错

[sfexpr...js info][2021-05-07 09:30:41.070] ❗️顺丰速运, 错误!
TypeError: Cannot read property 'taskTitleLevels' of undefined

https://raw.githubusercontent.com/chavyleung/scripts/master/sfexpress/sfexpress.js

**Comment by LevineWoo** [comment]
再试了一个，苏宁易购，也是出错的
https://github.com/chavyleung/scripts/tree/master/suning

**Comment by elecV2** [comment]
小部分原因是 elecV2P $request/$response headers 都是以小写字母开头，而其他软件都是以大写字母开头。（解决方法：自己手动改一下脚本

大部分原因可能是确实还不兼容，之后会专门处理一下这个问题。（欢迎反馈，记得带脚本地址/错误日志，最好能附上相应的 cookie （关键信息记得替换，主要就看一下内容格式

目前来说只能自己手动调试，根据错误日志找到相应的代码段，然后 console.log 一下结果，看是否符合预期，然后再做相应的判断和调整

**Comment by wsdjj** [comment]
问一下，脚本是修改那部分？
