### ISSUE TITLE
boxjs 更新后无法直接使用 原作者的脚本

### ISSUE THREAD

**Issue by q123458384** [elecV2/elecV2P#81]
v2p 版本 3.3.4

rules使用元作者的脚本：https://raw.githubusercontent.com/chavyleung/scripts/master/chavy.box.js   打开boxjs,只有boxjs几个字~无发进一步加载。

目前是用elecV2大佬的脚本：https://raw.githubusercontent.com/elecV2/elecV2P-dei/master/examples/JSTEST/boxjs.ev.js
还能正常使用，就是版本比较旧

**Comment by elecV2** [comment]
再尝试更新一下吧，正常来说应该不会出现这个问题。
> v2p 版本 3.3.4
> 
> rules使用元作者的脚本：https://raw.githubusercontent.com/chavyleung/scripts/master/chavy.box.js 打开boxjs,只有boxjs几个字~无发进一步加载。
> 
> 目前是用elecV2大佬的脚本：https://raw.githubusercontent.com/elecV2/elecV2P-dei/master/examples/JSTEST/boxjs.ev.js
