### ISSUE TITLE
你好后续能支持surge或者qx的脚本和REWRITE 吗

### ISSUE THREAD

**Issue by h605290713** [elecV2/elecV2P#82]
你好后续能支持surge或者qx的脚本和REWRITE 吗

**Comment by LevineWoo** [comment]
> 你好后续能支持surge或者qx的脚本和REWRITE 吗

qx能用的rewrite好像都可以。
surge不一定，qx的任务脚本就部份能跑，只是订阅的格式不一样，建议订阅少年歌行pro的v2p TASK。
https://raw.githubusercontent.com/sngxpro/QuanX/master/V2pTaskSub/sngxprov2p.json

**Comment by h605290713** [comment]
你好 我刚才用https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rewrite/QuantumultX/Advertising/Advertising.conf
这个 不能识别 然后用了 https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rewrite/QuantumultX/AllInOne/AllInOne.conf
这个 发现 只能之别 后面带脚本路径的规则

**Comment by LevineWoo** [comment]
> 你好 我刚才用https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rewrite/QuantumultX/Advertising/Advertising.conf
> 这个 不能识别 然后用了 https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rewrite/QuantumultX/AllInOne/AllInOne.conf
> 这个 发现 只能之别 后面带脚本路径的规则

啊这，你是想去广告啊？v2p更多是用来跑脚本的，一般用那种带脚本路径的那种来获取ck。so..

**Comment by h605290713** [comment]
> > 你好 我刚才用https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rewrite/QuantumultX/Advertising/Advertising.conf
> > 这个 不能识别 然后用了 https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rewrite/QuantumultX/AllInOne/AllInOne.conf
> > 这个 发现 只能之别 后面带脚本路径的规则
> 
> 啊这，你是想去广告啊？v2p更多是用来跑脚本的，一般用那种带脚本路径的那种来获取ck。so..

你这工具很强大 跑脚本太浪费了 哈哈
