### ISSUE TITLE
为何ipad打开网页是白屏呢

### ISSUE THREAD

**Issue by shangjiazi** [elecV2/elecV2P#83]
手机电脑是正常打开网页的，ipad换各种浏览器和清楚缓存也不行，白屏就一标题，

**Comment by shangjiazi** [comment]
> 手机电脑是正常打开网页的，ipad换各种浏览器和清楚缓存也不行，白屏就一标题，

另8102也是正常打开

**Comment by elecV2** [comment]
可能是系统或浏览器版本太低，尝试升级一下。
#72
