### ISSUE TITLE
3.3.7版本遇到了串JS的问题

### ISSUE THREAD

**Issue by enews** [elecV2/elecV2P#84]
本身应该执行东东农场, 但是执行的却是返利网, 我把返利网的JS删除了, 重启过V2P, 还是一样
![123](https://user-images.githubusercontent.com/9135007/118751267-98e85b80-b893-11eb-855b-120f0f840880.png)

**Comment by elecV2** [comment]
自行检查一下脚本里面的具体内容。

elecV2P 还没有那么智能，可以去跑一个不存在的脚本或代码。

**Comment by enews** [comment]
> 
> 自行检查一下脚本里面的具体内容。 elecV2P 还没有那么智能，可以去跑一个不存在的脚本或代码。

两个脚本完全不一样, 一个是加密的,一个是非加密的, 非加密的一眼就能看出来

**Comment by enews** [comment]
找到问题了, 不是v2p的问题
