### ISSUE TITLE
加密脚本执行不了

### ISSUE THREAD

**Issue by LevineWoo** [elecV2/elecV2P#85]
脚本：https://raw.githubusercontent.com/CenBoMin/GithubSync/main/ELONGCASH/elongcash.js
情况：qx能正常跑，v2p报错：

报错内容：
[taskRunJS   info][2021-05-25 11:00:01.151] run elongcash.js result: {}
[elongc...js info][2021-05-25 11:00:01.150] 🔔ELONGCASH, 结束! 🕛 1.138 秒
[elongc...js info][2021-05-25 11:00:01.149] ❌ ELONGCASH, 失败! 原因: ReferenceError: taskSignState is not defined!
[elongc...js info][2021-05-25 11:00:01.148] 🐲[ELONGCASH]:~ User1💲签到任务
[elongc...js info][2021-05-25 11:00:01.147] ⛔️服务器访问数据为空，请检查自身设备网络情况
[elongc...js info][2021-05-25 11:00:01.146] SyntaxError: Unexpected token  in JSON at position 0
[elongc...js info][2021-05-25 11:00:00.959] 🐲[ELONGCASH]:~ User1💲小猪扑满
[elongc...js info][2021-05-25 11:00:00.950] ⛔️服务器访问数据为空，请检查自身设备网络情况
[elongc...js info][2021-05-25 11:00:00.949] SyntaxError: Unexpected token  in JSON at position 0
[elongc...js info][2021-05-25 11:00:00.781] 🐲[ELONGCASH]:~ User1💲用户任务
[elongc...js info][2021-05-25 11:00:00.780] ⛔️服务器访问数据为空，请检查自身设备网络情况
[elongc...js info][2021-05-25 11:00:00.778] SyntaxError: Unexpected token  in JSON at position 0
[elongc...js info][2021-05-25 11:00:00.587] 🐲[ELONGCASH]:~ User1💲用户资讯
[elongc...js info][2021-05-25 11:00:00.584] 🐲[ELONGCASH]:~ System💲/执行脚本
开始执行 👤User1的脚本任务
[elongc...js info][2021-05-25 11:00:00.581] 用户1(ID:~~隐藏~~):~ 秘钥验证成功！🎉
[elongc...js info][2021-05-25 11:00:00.042] 🗝[ELONGCASH]:开始验证~用户1-脚本使用权限...
[elongc...js info][2021-05-25 11:00:00.039] 本次执行共1个账号
[elongc...js info][2021-05-25 11:00:00.037] 🐲[ELONGCASH]:~ System💲脚本账号数量
[elongc...js info][2021-05-25 11:00:00.034] Now login(UTC+8):5/25/2021, 7:00:00 PM
[elongc...js info][2021-05-25 11:00:00.031] * Author:CenBoMin
[elongc...js info][2021-05-25 11:00:00.013] 🔔ELONGCASH, 开始!
[taskTest    info][2021-05-25 10:47:19.042] 同程小猪 测试运行结果: {}
[taskRunJS   info][2021-05-25 10:47:19.457] run elongcash.js result: {}

**Comment by elecV2** [comment]
加密脚本除了等作者进行适配之外，暂时无解。（看不到脚本内容，无法判断是什么原因导致的问题
