### ISSUE TITLE
能不能增加一个自动更新订阅任务的功能

### ISSUE THREAD

**Issue by huaxinCLUB** [elecV2/elecV2P#89]
## 1. 看到了大佬内置的自动更新JS文件的功能
该功能只能实现JS的更新，不能根据订阅任务增删文件
## 2. 保存任务列表
该功能只能在重启 elecV2P后实现任务恢复
## 需求
**想要定时自动更新订阅任务，有好的实现方法吗？请大佬支路（小白一个）**

**Comment by elecV2** [comment]
可以自己写脚本，通过 webhook 提供的任务添加/删除接口去实现。
参考: https://github.com/elecV2/elecV2P-dei/tree/master/docs/09-webhook.md
