### ISSUE TITLE
无法起动

### ISSUE THREAD

**Issue by wang-max1** [elecV2/elecV2P#9]
用的ARM的镜像搭建成功后只要运行js就会断开，这个怎么解决啊
![image](https://user-images.githubusercontent.com/61648337/101246296-61567e80-374d-11eb-8282-62e0658c70cb.png)
还会提示这个
ReferenceError: errStack is not defined
    at /usr/local/app/utils/eaxios.js:105:7
    at processTicksAndRejections (node:internal/process/task_queues:93:5)

**Comment by elecV2** [comment]
远程 JS 吗？raw.githubxxx 需要代理才能访问，先尝试运行一下本地 JS 吧。

errStack 这个错误已提交修复，晚点更新一下。

> 用的ARM的镜像搭建成功后只要运行js就会断开，这个怎么解决啊
> 
> 还会提示这个
> ReferenceError: errStack is not defined
> at /usr/local/app/utils/eaxios.js:105:7
> at processTicksAndRejections (node:internal/process/task_queues:93:5)

**Comment by wang-max1** [comment]
本地也会报错  今什么时候更新，我再看看

**Comment by wang-max1** [comment]
> 远程JS吗？raw.githubxxx需要代理才能访问，先尝试运行一下本地JS吧。errStack这个错误已提交修复，晚点更新一下。
> […](#)
> 用过的ARM的架构构造成功后只要运行js就会替换，这个怎么解决啊就会提示这个ReferenceError：errStack未在processTicksAndRejections（/usr/local/app/utils/eaxios.js:105:7上定义（节点：内部/进程/任务队列：93：5）

我本地网络全局代理也不能远程啊，你这个怎么设置代理，有教程嘛

**Comment by elecV2** [comment]
已更新。错误日志发一下，或说明在操作什么的时候报什么错误。

SETTING 里面设置 eaxios，说明文档在每个页面的底下都有相关链接。

设置后先在 JSMANAGE 中远程推送一下看是否成功。

> 本地也会报错 今什么时候更新，我再看看

**Comment by wang-max1** [comment]
> SETTING里面设置eaxios，说明文档在每个页面的底下都有相关链接。设置后先在JSMANAGE中远程按下一下看是否成功。
> […](#)
> 本地也会报错今什么时候更新，我再看看

我换了一个openwrt版本就都正常了，无语了   这个必须开全局代理才能使用的吗？

**Comment by wang-max1** [comment]
> 已更新。错误日志发一下，或说明在操作什么的时候报什么错误。 SETTING 里面设置 eaxios，说明文档在每个页面的底下都有相关链接。 设置后先在 JSMANAGE 中远程推送一下看是否成功。
> […](#)
> 本地也会报错 今什么时候更新，我再看看
然后通过代理软件将 boxjs.com 分流到 anyproxy 服务器（默认为 127.0.0.1:8001） 这个怎么做到？用本地代理吗

**Comment by elecV2** [comment]
关于代理的分流/全局代理等网络知识，搜索一下，网络上有比较多的文章讲解。
代理分流通常要用到其他软件，比如 clash 这些。

> 已更新。错误日志发一下，或说明在操作什么的时候报什么错误。 SETTING 里面设置 eaxios，说明文档在每个页面的底下都有相关链接。 设置后先在 JSMANAGE 中远程推送一下看是否成功。
> …
> 本地也会报错 今什么时候更新，我再看看
> 然后通过代理软件将 boxjs.com 分流到 anyproxy 服务器（默认为 127.0.0.1:8001） 这个怎么做到？用本地代理吗

**Comment by wang-max1** [comment]
> 关于代理的分流/全局代理等网络知识，搜索一下，网络上有比较多的文章讲解。 代理分流通常要用到其他软件，比如 clash 这些。
> […](#)
> 已更新。错误日志发一下，或说明在操作什么的时候报什么错误。 SETTING 里面设置 eaxios，说明文档在每个页面的底下都有相关链接。 设置后先在 JSMANAGE 中远程推送一下看是否成功。 … 本地也会报错 今什么时候更新，我再看看 然后通过代理软件将 boxjs.com 分流到 anyproxy 服务器（默认为 127.0.0.1:8001） 这个怎么做到？用本地代理吗

更新命令是什么？要更新只能重搭吗？

**Comment by elecV2** [comment]
Docker image 更新等基础命令自行谷歌，不同搭建方式更新方式不一样。

如果更新想保存 JS 和cookie 等其他数据，重点看一下 docker 有关持久化存储(volumes) 的内容。

> 关于代理的分流/全局代理等网络知识，搜索一下，网络上有比较多的文章讲解。 代理分流通常要用到其他软件，比如 clash 这些。
> …
> 已更新。错误日志发一下，或说明在操作什么的时候报什么错误。 SETTING 里面设置 eaxios，说明文档在每个页面的底下都有相关链接。 设置后先在 JSMANAGE 中远程推送一下看是否成功。 … 本地也会报错 今什么时候更新，我再看看 然后通过代理软件将 boxjs.com 分流到 anyproxy 服务器（默认为 127.0.0.1:8001） 这个怎么做到？用本地代理吗
> 
> 更新命令是什么？要更新只能重搭吗？

**Comment by wang-max1** [comment]
> Docker image 更新等基础命令自行谷歌，不同搭建方式更新方式不一样。 如果更新想保存 JS 和cookie 等其他数据，重点看一下 docker 有关持久化存储(volumes) 的内容。
> […](#)
> 关于代理的分流/全局代理等网络知识，搜索一下，网络上有比较多的文章讲解。 代理分流通常要用到其他软件，比如 clash 这些。 … 已更新。错误日志发一下，或说明在操作什么的时候报什么错误。 SETTING 里面设置 eaxios，说明文档在每个页面的底下都有相关链接。 设置后先在 JSMANAGE 中远程推送一下看是否成功。 … 本地也会报错 今什么时候更新，我再看看 然后通过代理软件将 boxjs.com 分流到 anyproxy 服务器（默认为 127.0.0.1:8001） 这个怎么做到？用本地代理吗 更新命令是什么？要更新只能重搭吗？

TZ=Asia/Shanghai这个没生效，时间不同步的问题能不能修复下  每次创建都要改

**Comment by elecV2** [comment]
> > Docker image 更新等基础命令自行谷歌，不同搭建方式更新方式不一样。 如果更新想保存 JS 和cookie 等其他数据，重点看一下 docker 有关持久化存储(volumes) 的内容。
> > […](#)
> > 关于代理的分流/全局代理等网络知识，搜索一下，网络上有比较多的文章讲解。 代理分流通常要用到其他软件，比如 clash 这些。 … 已更新。错误日志发一下，或说明在操作什么的时候报什么错误。 SETTING 里面设置 eaxios，说明文档在每个页面的底下都有相关链接。 设置后先在 JSMANAGE 中远程推送一下看是否成功。 … 本地也会报错 今什么时候更新，我再看看 然后通过代理软件将 boxjs.com 分流到 anyproxy 服务器（默认为 127.0.0.1:8001） 这个怎么做到？用本地代理吗 更新命令是什么？要更新只能重搭吗？
> 
> TZ=Asia/Shanghai这个没生效，时间不同步的问题能不能修复下 每次创建都要改

应该是前几个版本就已修复的问题
