### ISSUE TITLE
报告bug

### ISSUE THREAD

**Issue by manlongdan** [elecV2/elecV2P#90]
X86 docker VERSION: 3.3.8
TASK订阅使用替换同名更新方式全部添加显示保存成功实际上没保存，使用跳过方式保存成功

**Comment by elecV2** [comment]
简单重测了一下，没发现你所说的问题。

确认一下你的操作步骤或网络是否正常。如果问题继续存在，麻烦发一下你的任务列表截图和使用的订阅链接，以及简单说一下你判断“实际上没保存”的依据是什么
> X86 docker VERSION: 3.3.8
> TASK订阅使用替换同名更新方式全部添加显示保存成功实际上没保存，使用跳过方式保存成功

**Comment by manlongdan** [comment]
> 简单重测了一下，没发现你所说的问题。 确认一下你的操作步骤或网络是否正常。 如果问题继续存在，麻烦发一下你的任务列表截图和使用的订阅链接，以及简单说一下你判断“实际上没保存”的依据是什么
> [...](#)
> X86 docker VERSION: 3.3.8 TASK订阅使用替换同名更新方式全部添加显示保存成功实际上没保存，使用跳过方式保存成功

![c1dbd44ee4d756b993640d1e99b6b48](https://user-images.githubusercontent.com/74487950/121804674-3019b680-cc7a-11eb-8e24-f358254a334e.png)
![32c25934c5c7926bc5d6b46fa5a19c9](https://user-images.githubusercontent.com/74487950/121804681-3ad44b80-cc7a-11eb-8003-2da50fb035b2.png)
![e0ca5e335ef4da6a2be22baff2ba21f](https://user-images.githubusercontent.com/74487950/121804685-40ca2c80-cc7a-11eb-8588-af6eafe3a46b.png)
![6e4b1150731f515bdc3d6975578ee3c](https://user-images.githubusercontent.com/74487950/121804691-47f13a80-cc7a-11eb-9453-ca281447c58a.png)



[elecV2P 定时任务订阅.zip](https://github.com/elecV2/elecV2P/files/6643766/elecV2P.zip)
感谢大佬回复，上面4张图是我的操作步骤，
1、导出任务列表
2、替换任务列表中链接
3、上传本地订阅
4、全部替换更新
5、检查链接已经成功替换
6、保存，提示保存成功，退出
7、重新进入页面，发现链接没有成功替换
中午的时候我是用订阅链接替换更新，因为订阅作者新增了脚本，保存成功后重新进页面发现订阅作者新增的脚本并没有成功添加，遂向大佬报告情况，附订阅作者链接 https://raw.githubusercontent.com/sngxpro/QuanX/master/V2pTaskSub/sngxprov2p.json

**Comment by elecV2** [comment]
还是没能复现你说的这个问题。

你保存成功到重新进入这中间隔了多久？有没有可能你设置了其他定时任务用于自动更新任务列表，从而把你所做的更改又“更”回去了。
如果不是这个原因的话，暂时无法定位是什么导致的你的问题（我这边操作一切正常

**Comment by manlongdan** [comment]
> 还是没能复现你说的这个问题。 你保存成功到重新进入这中间隔了多久？有没有可能你设置了其他定时任务用于自动更新任务列表，从而把你所做的更改又“更”回去了。 如果不是这个原因的话，暂时无法定位是什么导致的你的问题（我这边操作一切正常

**Comment by manlongdan** [comment]
感谢大佬，可能是我的硬件问题，下次更新可不可以增加一个一键清空已保存定时任务的按钮，或加个多选、全选删除的按钮
