### ISSUE TITLE
anyproxy抓不到包

### ISSUE THREAD

**Issue by zzy0711** [elecV2/elecV2P#92]
同一个app，其他软件像charles抓的到包，v2p带的anyproxy抓不到（所需证书均设为系统证书），app信息刷新不出来，一直在加载

**Comment by elecV2** [comment]
进 8002 端口或 后台查看请求记录，这种描述无法确定问题在哪里。

**Comment by zzy0711** [comment]
同一个app OS抓的到包，而且数据包解析很流畅，Android的数据量大一点就卡住，一直刷新，然后anyproxy web页面也不出包了，Android抓app基本上总有这种情况，顶多抓抓网页的包，app包基本上都抓不出

**Comment by elecV2** [comment]
没有相关设备，无法测试。抓包的话建议只代理需要的网络请求到 anyproxy，如果同时处理大量请求，可能会出现你所说的情况。
除了建议把 elecV2P 部署到好一点的设备上，和同时少处理一些网络请求外，暂时想不到好的解决方法。
