### ISSUE TITLE
v2p跑宠汪汪兑换脚本总是报错ReferenceError: require is not defined

### ISSUE THREAD

**Issue by LevineWoo** [elecV2/elecV2P#95]
脚本地址：https://raw.githubusercontent.com/photonmang/quantumultX/master/JDscripts/jd_joy_reward.js
v2p版本：3.4.0
尝试按脚本内容添加jdCookie.js内容，但不清楚具体格式。
这个报错提示也是其他脚本也会出现的，应该是常见问题，在青龙、v4等京东的docker镜像（应该也是node）能正常运行，是需要脚本作者单独适应v2p嘛？

**Comment by CenBoMin** [comment]
@LevineWoo 要用shell指令执行,但是jdCookie.js里面要手动填入数组,但是shell指令只能执行60秒,因此需要弄个js文档里面用$exec函数设定超时时间为0，可以参照我提出的问题

**Comment by elecV2** [comment]
TASK 中 **运行 JS** 默认使用的不是 node 环境，要使用 node 运行，选择 **Shell 指令** 然后填写 node xxxx.js。 #94
