### ISSUE TITLE
您好，请教一下宝塔如何做反向代理到这个V2P的端口呢？

### ISSUE THREAD

**Issue by 810517583** [elecV2/elecV2P#96]
您好，请教一下宝塔如何做反向代理到这个V2P的端口呢？

**Comment by elecV2** [comment]
没用过。总共就那三个端口，原理都差不多，网上搜一下相关教程吧。

如果是 nginx，可以参考: https://github.com/elecV2/elecV2P-dei/blob/master/examples/ev2p-nginx.conf

**Comment by 810517583** [comment]
我是反向代理后显示Not Found
