### ISSUE TITLE
V2P通知附带执行JS的log链接

### ISSUE THREAD

**Issue by CenBoMin** [elecV2/elecV2P#97]
由于直接看程序运行日志执行任务多的话,找起来有点眼花,所以想实现在接受通知的时候:

- **1.手机端点击通知,跳转链接直接查看log**
- **2.或者在最尾端可以附上log的链接直接点击查看**

效果可能是这样：

```
用户1任务执行通知🔔
<通知内容>
🤖 查看执行log:http://12345.v2p/logs/档案名.js.log
```

看了下文档可以用的这三个参数($title$, $body$, $url$),原本思考也许可以写notify.js来实现，但是不知道如何引用这个关键的**档案名**的这个参数来用...

或许可以请考虑在下个版本在"自定义通知"那边加入这个参数，应该挺实用的..

**Comment by elecV2** [comment]
主页名：__home
JS 名：__name (都是两个下滑线

测试：
console.log(`${__home}/logs/${__name}.log`)

**Comment by CenBoMin** [comment]
@elecV2 好的,我研究下...谢谢

**Comment by elecV2** [comment]
﻿好像我误会了，这样 __name 都是 notify.js

之后版本再看看吧^

**Comment by CenBoMin** [comment]
@elecV2 好的,谢谢..…^^

**Comment by CenBoMin** [comment]
> 主页名：__home JS 名：__name (都是两个下滑线 测试： console.log(`${__home}/logs/${__name}.log`)

我测试了下可以用在执行Shell指令的环境变量：**V2P_NOTIFY: `${__home}/logs/${__name}.log`**

```
$exec('node jd_bean_change.js', {
  cwd: 'script/JSFile',
  env: {
    ...process.env,
    JD_COOKIE: $store.get('CookiesJDV2P', 'string'),
    V2P_NOTIFY: `${__home}/logs/${__name}.log`
  },
  timeout: 0,
  cb(data, error){
    error ? console.error(error) : console.log(data)
  }
})
```
然后在sendNotify.js声明下环境变量V2P_NOTIFY引用到sendNotify函数即可..

**Comment by elecV2** [comment]
> > 主页名：__home JS 名：__name (都是两个下滑线 测试： console.log(`${__home}/logs/${__name}.log`)
> 
> 我测试了下可以用在执行Shell指令的环境变量：**V2P_NOTIFY: `${__home}/logs/${__name}.log`**
> 
> ```
> $exec('node jd_bean_change.js', {
>   cwd: 'script/JSFile',
>   env: {
>     ...process.env,
>     JD_COOKIE: $store.get('CookiesJDV2P', 'string'),
>     V2P_NOTIFY: `${__home}/logs/${__name}.log`
>   },
>   timeout: 0,
>   cb(data, error){
>     error ? console.error(error) : console.log(data)
>   }
> })
> ```
> 
> 然后在sendNotify.js声明下环境变量V2P_NOTIFY引用到sendNotify函数即可..

还能这么用？nb
